// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isFailureClusters } from "../components/FailureClusters"

/** GET /dlq/clusters */
export function isGetDlqClustersResponse(value: unknown): value is Api.ApiResponses["GET /dlq/clusters"] {
  return isFailureClusters(value)
}
