// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isDeadLetterDetail } from "../components/DeadLetterDetail"

/** GET /dlq/entries/{deadLetterId} */
export function isGetDlqEntriesDeadLetterIdResponse(value: unknown): value is Api.ApiResponses["GET /dlq/entries/{deadLetterId}"] {
  return isDeadLetterDetail(value)
}
