// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isMemoryConsentStatus } from "../components/MemoryConsentStatus"

/** GET /memory/consent-status */
export function isGetMemoryConsentStatusResponse(value: unknown): value is Api.ApiResponses["GET /memory/consent-status"] {
  return isMemoryConsentStatus(value)
}
