// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isOperatorBrief } from "../components/OperatorBrief"

/** GET /operations/brief */
export function isGetOperationsBriefResponse(value: unknown): value is Api.ApiResponses["GET /operations/brief"] {
  return isOperatorBrief(value)
}
