// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isRunUsage } from "../components/RunUsage"

/** GET /run/usage */
export function isGetRunUsageResponse(value: unknown): value is Api.ApiResponses["GET /run/usage"] {
  return isRunUsage(value)
}
