// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isRecoveryHome } from "../components/RecoveryHome"

/** GET /recovery/home */
export function isGetRecoveryHomeResponse(value: unknown): value is Api.ApiResponses["GET /recovery/home"] {
  return isRecoveryHome(value)
}
