// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isRunView } from "../components/RunView"

/** GET /run */
export function isGetRunResponse(value: unknown): value is Api.ApiResponses["GET /run"] {
  return isRunView(value)
}
