// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isRunView } from "../components/RunView"

/** GET /status */
export function isGetStatusResponse(value: unknown): value is Api.ApiResponses["GET /status"] {
  return isRunView(value)
}
