// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isWorkflowHealthScore } from "../components/WorkflowHealthScore"

/** GET /workflows/health */
export function isGetWorkflowsHealthResponse(value: unknown): value is Api.ApiResponses["GET /workflows/health"] {
  return isWorkflowHealthScore(value)
}
