// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape, isString } from "../../guards"

/** GET /workflows/schedule-preview */
export function isGetWorkflowsSchedulePreviewResponse(value: unknown): value is Api.ApiResponses["GET /workflows/schedule-preview"] {
  return isShape(value, {
    nextFires: arrayOf(isString),
    valid: isBoolean,
  })
}
