// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isTriggerIngestResponse } from "../components/TriggerIngestResponse"

/** POST /triggers/email/ingest */
export function isPostTriggersEmailIngestResponse(value: unknown): value is Api.ApiResponses["POST /triggers/email/ingest"] {
  return isTriggerIngestResponse(value)
}
