// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape } from "../../guards"
import { isValidationIssue } from "../components/ValidationIssue"

/** POST /validate */
export function isPostValidateResponse(value: unknown): value is Api.ApiResponses["POST /validate"] {
  return isShape(value, {
    issues: arrayOf(isValidationIssue),
    valid: isBoolean,
  })
}
