// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isInteger, isShape, isString } from "../../guards"

/** POST /workflows/rollback */
export function isPostWorkflowsRollbackResponse(value: unknown): value is Api.ApiResponses["POST /workflows/rollback"] {
  return isShape(value, {
    sourceVersion: isInteger,
    version: isInteger,
    versionId: isString,
    workflowId: isString,
  })
}
