// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape, isString } from "../../guards"

/** POST /recovery/cases/{caseId}/apply */
export function isPostRecoveryCasesCaseIdApplyResponse(value: unknown): value is Api.ApiResponses["POST /recovery/cases/{caseId}/apply"] {
  return isShape(value, {
    decision: isString,
    resolvedCaseIds: arrayOf(isString),
    resumed: isBoolean,
    runId: isString,
    sourceNodeId: isString,
  })
}
