// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isShape, literal } from "../../guards"

/** POST /dlq/resolve */
export function isPostDlqResolveResponse(value: unknown): value is Api.ApiResponses["POST /dlq/resolve"] {
  return isShape(value, {
    ok: literal(true),
  })
}
