// Command pricing renders the browser's static completion-price table from
// internal/ai, the runtime source of truth. It is part of make generate so a
// price update cannot leave cost previews and recorded usage on different
// rates.
package main

import (
	"bytes"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/johnny4young/janusly/internal/ai"
)

const outputPath = "web/src/lib/llm-pricing.generated.ts"

func main() {
	prices := ai.StaticModelPrices()
	models := make([]string, 0, len(prices))
	for model := range prices {
		models = append(models, model)
	}
	slices.Sort(models)

	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by go run ./cmd/pricing; DO NOT EDIT. */")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "export const GENERATED_MODEL_PRICING_SNAPSHOT_DATE = %s as const\n", strconv.Quote(ai.ModelPricingSnapshotDate))
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "export const GENERATED_MODEL_PRICES = Object.freeze({")
	for _, model := range models {
		price := prices[model]
		fmt.Fprintf(&out, "  %s: { inputUsdPer1M: %s, outputUsdPer1M: %s },\n",
			strconv.Quote(model), formatNumber(price.InputUsdPer1M), formatNumber(price.OutputUsdPer1M))
	}
	fmt.Fprintln(&out, "})")

	if err := os.WriteFile(outputPath, out.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write pricing:", err)
		os.Exit(1)
	}
	fmt.Printf("%s: %d models, snapshot %s\n", outputPath, len(models), ai.ModelPricingSnapshotDate)
}

func formatNumber(value float64) string {
	// Pricing has bounded decimal precision. Formatting the raw binary float
	// with -1 can expose representation artifacts (for example 0.1*3 as
	// 0.30000000000000004) in the generated TypeScript contract.
	formatted := strings.TrimRight(strconv.FormatFloat(value, 'f', 12, 64), "0")
	formatted = strings.TrimRight(formatted, ".")
	if formatted == "" || formatted == "-0" {
		return "0"
	}
	return formatted
}
