import { useShallow } from 'zustand/react/shallow'
import { useWorkflowStore } from '../store'

/**
 * Select the shell-owned state once. Keeping this list centralized prevents
 * unrelated store ticks from re-rendering the entire application workspace.
 */
export function useAppStore() {
  return useWorkflowStore(useShallow((state) => ({
    nodes: state.nodes,
    edges: state.edges,
    onNodesChange: state.onNodesChange,
    onEdgesChange: state.onEdgesChange,
    connect: state.connect,
    addNode: state.addNode,
    activeTab: state.activeTab,
    activeRecoveryCaseId: state.activeRecoveryCaseId,
    userId: state.userId,
    orgId: state.orgId,
    authReady: state.authReady,
    identityContext: state.identityContext,
    identityReady: state.identityReady,
    runId: state.runId,
    runDetail: state.runDetail,
    runNodes: state.runNodes,
    events: state.events,
    selectedNodeId: state.selectedNodeId,
    selectedEdgeId: state.selectedEdgeId,
    currentWorkflowId: state.currentWorkflowId,
    currentWorkflowName: state.currentWorkflowName,
    currentWorkflowSaved: state.currentWorkflowSaved,
    currentWorkflowVersion: state.currentWorkflowVersion,
    workflowDirty: state.workflowDirty,
    currentWorkflowInputs: state.currentWorkflowInputs,
    currentWorkflowOutputs: state.currentWorkflowOutputs,
    workflowRevision: state.workflowRevision,
    streamStatus: state.streamStatus,
    setAuth: state.setAuth,
    clearAuth: state.clearAuth,
    setAuthReady: state.setAuthReady,
    setIdentityContext: state.setIdentityContext,
    setIdentityPending: state.setIdentityPending,
    setActiveTab: state.setActiveTab,
    openRecoveryCase: state.openRecoveryCase,
    setWorkflowName: state.setWorkflowName,
    initializeWorkflowName: state.initializeWorkflowName,
    hydrateWorkflow: state.hydrateWorkflow,
    getWorkflowJson: state.getWorkflowJson,
    newWorkflow: state.newWorkflow,
    markWorkflowSaved: state.markWorkflowSaved,
    selectNode: state.selectNode,
    selectEdge: state.selectEdge,
    updateSelectedNodeConfig: state.updateSelectedNodeConfig,
    updateSelectedNodeType: state.updateSelectedNodeType,
    setRunId: state.setRunId,
    setRunDetail: state.setRunDetail,
    patchRunDetail: state.patchRunDetail,
    setRunNodes: state.setRunNodes,
    setEvents: state.setEvents,
    addEvents: state.addEvents,
    eventsCursor: state.eventsCursor,
    eventsHasMore: state.eventsHasMore,
    setEventsPagination: state.setEventsPagination,
    addToast: state.addToast,
    updateEdgeCondition: state.updateEdgeCondition,
    updateEdgeOnError: state.updateEdgeOnError,
    bumpPlatformVersion: state.bumpPlatformVersion,
  })))
}
