// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isInteger, isShape, isString, shape } from "../../guards"
import { isAuthoringMCPInputField } from "./AuthoringMCPInputField"
import { isToolCatalogEntry } from "./ToolCatalogEntry"

export function isAuthoringCapabilities(value: unknown): value is Api.AuthoringCapabilities {
  return isShape(value, {
    builtinTools: arrayOf(isToolCatalogEntry),
    credentials: arrayOf(shape({
      configured: isBoolean,
      expired: isBoolean,
      id: isString,
      kind: isString,
      name: isString,
      updatedAt: isString,
    }, {
      expiresAt: isString,
    })),
    mcpTools: arrayOf(shape({
      connectionAlias: isString,
      description: isString,
      inputFields: arrayOf(isAuthoringMCPInputField),
      toolName: isString,
      writeSide: isBoolean,
    })),
    primitives: arrayOf(shape({
      nodeType: isString,
      notes: isString,
      requiredConfig: arrayOf(isString),
    })),
    schemaVersion: isString,
    subworkflows: arrayOf(shape({
      latestVersion: isInteger,
      name: isString,
      status: isString,
      workflowId: isString,
    })),
    triggers: arrayOf(shape({
      id: isString,
      requiredConfig: arrayOf(isString),
    }, {
      endpoint: isString,
      nodeType: isString,
    })),
    version: isString,
    warnings: arrayOf(isString),
  })
}
