// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isBoolean, isShape, isString } from "../../guards"

export function isAuthoringExperienceRevocation(value: unknown): value is Api.AuthoringExperienceRevocation {
  return isShape(value, {
    id: isString,
    revoked: isBoolean,
  })
}
