// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape } from "../../guards"
import { isAuthoringExperienceRecord } from "./AuthoringExperienceRecord"

export function isAuthoringExperienceList(value: unknown): value is Api.AuthoringExperienceList {
  return isShape(value, {
    entries: arrayOf(isAuthoringExperienceRecord),
    truncated: isBoolean,
  })
}
