// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isInteger, isShape, isString, nullable } from "../../guards"
import { isDeadLetterRecovery } from "./DeadLetterRecovery"
import { isDeadLetterStatus } from "./DeadLetterStatus"

export function isDeadLetterSummary(value: unknown): value is Api.DeadLetterSummary {
  return isShape(value, {
    attempt: isInteger,
    createdAt: nullable(isString),
    errorJson: isAny,
    id: isString,
    nodeId: isString,
    nodeType: nullable(isString),
    orgId: isString,
    recovery: nullable(isDeadLetterRecovery),
    replayedAt: nullable(isString),
    runId: isString,
    status: isDeadLetterStatus,
    workflowName: nullable(isString),
  })
}
