// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isInteger, isShape, isString, nullable } from "../../guards"

export function isDeadLetterRecovery(value: unknown): value is Api.DeadLetterRecovery {
  return isShape(value, {
    comments: isAny,
    id: isString,
    lastOccurredAt: nullable(isString),
    metadataWorkflowId: nullable(isString),
    occurrenceCount: isInteger,
    owner: nullable(isString),
    resolutionReason: nullable(isString),
    severity: isString,
    slaTargetAt: nullable(isString),
    status: isString,
    workflowId: nullable(isString),
  })
}
