// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isInteger, isNull, isShape, isString, nullable } from "../../guards"
import { isDeadLetterStatus } from "./DeadLetterStatus"
import { isDrillOutcome } from "./DrillOutcome"
import { isDrillProvenance } from "./DrillProvenance"

export function isDeadLetterDetail(value: unknown): value is Api.DeadLetterDetail {
  return isShape(value, {
    attempt: isInteger,
    createdAt: nullable(isString),
    drill: nullable(isDrillProvenance),
    drillOutcome: nullable(isDrillOutcome),
    errorJson: isAny,
    id: isString,
    nodeId: isString,
    nodeJson: isAny,
    orgId: isString,
    replayClaimedAt: nullable(isString),
    replayedAt: nullable(isString),
    runId: isString,
    status: isDeadLetterStatus,
    suspectVersion: isNull,
    workflowJson: isAny,
  })
}
