// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isShape, isString, literal } from "../../guards"

export function isDrillProvenance(value: unknown): value is Api.DrillProvenance {
  return isShape(value, {
    fixtureId: isString,
    kind: literal("solution_pack_drill"),
    packId: isString,
    recoveryPath: literal("direct_failure", "runtime_failure", "stalled_node_reaper"),
  })
}
