// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isInteger, isShape, isString, shape } from "../../guards"

export function isFailureCluster(value: unknown): value is Api.FailureCluster {
  return isShape(value, {
    affectedWorkflows: arrayOf(shape({
      count: isInteger,
      workflowId: isString,
      workflowName: isString,
    })),
    category: isString,
    firstSeen: isString,
    frequency: isInteger,
    lastSeen: isString,
    recurredAfterRecovery: isBoolean,
    samples: arrayOf(shape({
      id: isString,
      runId: isString,
      source: isString,
    })),
    signature: isString,
    suggestedOwner: isString,
  })
}
