// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isShape, isString, literal, shape } from "../../guards"
import { isCanonicalWorkflowDoc } from "./CanonicalWorkflowDoc"
import { isRecoveryPassport } from "./RecoveryPassport"
import { isRecoveryPlaybook } from "./RecoveryPlaybook"
import { isSuggestionEvidence } from "./SuggestionEvidence"
import { isWorkflowSuggestion } from "./WorkflowSuggestion"

export function isPlaybookUseResponse(value: unknown): value is Api.PlaybookUseResponse {
  return isShape(value, {
    suggestion: shape({
      evidence: arrayOf(isSuggestionEvidence),
      mode: literal("playbook"),
      playbook: isRecoveryPlaybook,
      rationale: isString,
      recoveryPassport: isRecoveryPassport,
      suggestedWorkflow: isCanonicalWorkflowDoc,
      suggestions: arrayOf(isWorkflowSuggestion),
    }),
  })
}
