// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isInteger, isShape, isString, literal, shape } from "../../guards"

export function isQualificationSummary(value: unknown): value is Api.QualificationSummary {
  return isShape(value, {
    baselineCaseCount: isInteger,
    baselineDatasetValid: isBoolean,
    candidateAssertionCount: isInteger,
    candidateCaseCount: isInteger,
    coverageFailureCount: isInteger,
    datasetDigest: isString,
    datasetVersion: isString,
    failedCandidateAssertions: isInteger,
    failures: arrayOf(shape({
      actual: isString,
      dataset: literal("baseline", "candidate"),
      expected: isString,
      fixtureId: isString,
      reason: literal("baseline_dataset_invalid", "candidate_contract_missing", "detector_uncovered", "expected_mismatch"),
      sourceNodeId: isString,
    }, {
      violations: arrayOf(shape({
        action: isString,
        detectorId: isString,
        kind: isString,
        message: isString,
        sourceNodeId: isString,
      }, {
        details: arrayOf(isString),
      })),
    })),
    failuresTruncated: isBoolean,
    mode: isString,
    passedCandidateAssertions: isInteger,
    regressionCount: isInteger,
    status: isString,
  })
}
