// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { anyOf, isBoolean, isFiniteNumber, isString, recordOf } from "../../guards"

export function isRationaleMeta(value: unknown): value is Api.RationaleMeta {
  return recordOf(anyOf(isString, isFiniteNumber, isBoolean))(value)
}
