// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isShape, isString, literal } from "../../guards"

export function isReadinessIssue(value: unknown): value is Api.ReadinessIssue {
  return isShape(value, {
    code: isString,
    message: isString,
    severity: literal("info", "warn", "fail"),
  }, {
    edgeId: isString,
    nodeId: isString,
    suggestion: isString,
  })
}
