// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isFiniteNumber, isShape, isString } from "../../guards"

export function isRecallEntry(value: unknown): value is Api.RecallEntry {
  return isShape(value, {
    content: isString,
    id: isString,
    kind: isString,
    similarity: isFiniteNumber,
  }, {
    metadata: isAny,
    runId: isString,
    workflowId: isString,
  })
}
