// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isInteger, isShape } from "../../guards"

export function isRecoveryWins(value: unknown): value is Api.RecoveryWins {
  return isShape(value, {
    recovered: isInteger,
    windowDays: isInteger,
  })
}
