// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isFiniteNumber, isShape, isString, nullable } from "../../guards"
import { isMetricSeverity } from "./MetricSeverity"
import { isRationaleMeta } from "./RationaleMeta"

export function isRecoveryMetric(value: unknown): value is Api.RecoveryMetric {
  return isShape(value, {
    display: isString,
    rationale: isString,
    rationaleCode: isString,
    severity: isMetricSeverity,
    value: nullable(isFiniteNumber),
  }, {
    rationaleMeta: isRationaleMeta,
  })
}
