// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { literal } from "../../guards"

export function isRecoveryActorKind(value: unknown): value is Api.RecoveryActorKind {
  return literal("system", "user", "agent")(value)
}
