// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isFiniteNumber, isInteger, isShape, isString, literal, nullable, shape } from "../../guards"
import { isDrillOutcome } from "./DrillOutcome"
import { isNullableCount } from "./NullableCount"
import { isValidationBreakdown } from "./ValidationBreakdown"

export function isRecoveryValidationReport(value: unknown): value is Api.RecoveryValidationReport {
  return isShape(value, {
    byFailureMode: arrayOf(isValidationBreakdown),
    byRecoveryPath: arrayOf(isValidationBreakdown),
    generatedAt: isString,
    resolution: shape({
      automated: isInteger,
      operator: isInteger,
      operatorInterventionRatePercent: nullable(isFiniteNumber),
      unknown: isInteger,
    }),
    sampleCapped: isBoolean,
    sampleLimit: isInteger,
    samples: arrayOf(shape({
      failureMode: isString,
      fixtureId: isString,
      outcome: nullable(isDrillOutcome),
      packId: isString,
      recoveryPath: isString,
      resolutionMode: literal("operator", "automated", "unknown"),
      runCreatedAt: isString,
      runId: isString,
    })),
    timing: shape({
      averageElapsedMs: isNullableCount,
      medianElapsedMs: isNullableCount,
      p90ElapsedMs: isNullableCount,
      p95ElapsedMs: isNullableCount,
      sampleSize: isInteger,
    }),
    totals: shape({
      acceptedLoss: isInteger,
      awaitingAction: isInteger,
      completed: isInteger,
      completionRatePercent: nullable(isFiniteNumber),
      drills: isInteger,
      measurementIncomplete: isInteger,
      missingEvidence: isInteger,
      recovered: isInteger,
      recoveryRatePercent: nullable(isFiniteNumber),
      replayInProgress: isInteger,
    }),
    windowDays: isInteger,
  })
}
