// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isInteger, isShape, isString, literal, nullable } from "../../guards"
import { isRecoveryCaseState } from "./RecoveryCaseState"

export function isRecoveryCase(value: unknown): value is Api.RecoveryCase {
  return isShape(value, {
    action: literal("observe", "quarantine"),
    createdAt: isString,
    createdBy: nullable(isString),
    detailsJson: isAny,
    detectorId: isString,
    detectorKind: isString,
    id: isString,
    message: isString,
    orgId: isString,
    resolvedAt: nullable(isString),
    revision: isInteger,
    runId: isString,
    source: isString,
    sourceNodeId: isString,
    state: isRecoveryCaseState,
    updatedAt: isString,
    workflowId: nullable(isString),
    workflowVersionId: isString,
  })
}
