// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isFiniteNumber, isInteger, isShape, isString, nullable, shape } from "../../guards"
import { isCostProviderRow } from "./CostProviderRow"
import { isMetricSeverity } from "./MetricSeverity"
import { isRationaleMeta } from "./RationaleMeta"
import { isRecoveryMetric } from "./RecoveryMetric"

export function isRecoveryMetrics(value: unknown): value is Api.RecoveryMetrics {
  return isShape(value, {
    approvalsPending: isRecoveryMetric,
    clustersResolved: shape({
      capped: isBoolean,
      display: isString,
      rationale: isString,
      rationaleCode: isString,
      severity: isMetricSeverity,
      totalEntries: isInteger,
      value: nullable(isFiniteNumber),
    }, {
      rationaleMeta: isRationaleMeta,
    }),
    costByProvider: arrayOf(isCostProviderRow),
    costThisWindow: shape({
      cache: shape({
        creationTokens: isFiniteNumber,
        inputTokens: isFiniteNumber,
        readSharePercent: nullable(isFiniteNumber),
        readTokens: isFiniteNumber,
      }),
      display: isString,
      providers: arrayOf(isCostProviderRow),
      rationale: isString,
      rationaleCode: isString,
      severity: isMetricSeverity,
      value: nullable(isFiniteNumber),
    }, {
      rationaleMeta: isRationaleMeta,
    }),
    downtimeEndedMs: isFiniteNumber,
    mttr: isRecoveryMetric,
    mttrMs: nullable(isFiniteNumber),
    mttrTrend: arrayOf(shape({
      day: isString,
      seconds: isFiniteNumber,
    })),
    p95Latency: isRecoveryMetric,
    recurrence: shape({
      recurred: isInteger,
      resolved: isInteger,
      stayedFixedRate: nullable(isFiniteNumber),
      windowDays: isInteger,
    }),
    recurrenceRate: isRecoveryMetric,
    replayRate: isRecoveryMetric,
    slaAttainment: shape({
      display: isString,
      metSla: isInteger,
      rationale: isString,
      rationaleCode: isString,
      resolvedInWindow: isInteger,
      severity: isMetricSeverity,
      value: nullable(isFiniteNumber),
    }, {
      rationaleMeta: isRationaleMeta,
    }),
    successRate: isRecoveryMetric,
    terminalRuns: isInteger,
    timeToFirstAction: shape({
      avgSeconds: nullable(isFiniteNumber),
      display: isString,
      p95Seconds: nullable(isFiniteNumber),
      rationale: isString,
      rationaleCode: isString,
      sampleSize: isInteger,
      severity: isMetricSeverity,
      unit: isString,
      value: nullable(isFiniteNumber),
    }, {
      rationaleMeta: isRationaleMeta,
    }),
    valueEstimate: shape({
      assumptions: shape({
        baselineMttrSeconds: isFiniteNumber,
        hourlyCost: isFiniteNumber,
        minutesSavedPerRecovery: isFiniteNumber,
      }),
      dollarSaved: isFiniteNumber,
      hoursSaved: isFiniteNumber,
      mttrDeltaSeconds: nullable(isFiniteNumber),
    }),
    verifiedRecovery: shape({
      definitionVersion: isString,
      display: isString,
      metric: isString,
      p50Ms: nullable(isFiniteNumber),
      p90Ms: nullable(isFiniteNumber),
      rationale: isString,
      rationaleCode: isString,
      sampleSize: isInteger,
      severity: isMetricSeverity,
      unit: isString,
      value: nullable(isFiniteNumber),
    }, {
      rationaleMeta: isRationaleMeta,
    }),
    windowDays: isInteger,
  })
}
