// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isShape } from "../../guards"
import { isWorkflowRollout } from "./WorkflowRollout"

export function isRolloutEnvelope(value: unknown): value is Api.RolloutEnvelope {
  return isShape(value, {
    rollout: isWorkflowRollout,
  })
}
