// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isAny, isShape, isString, nullable } from "../../guards"

export function isRunEvent(value: unknown): value is Api.RunEvent {
  return isShape(value, {
    createdAt: nullable(isString),
    holdUntil: nullable(isString),
    id: isString,
    nodeId: nullable(isString),
    payload: isAny,
    runId: isString,
    type: isString,
  })
}
