// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { literal } from "../../guards"

export function isRunOutcomeStatus(value: unknown): value is Api.RunOutcomeStatus {
  return literal(null, "semantic_violation", "semantic_quarantined", "semantic_recovering", "semantic_recovered", "semantic_accepted_loss")(value)
}
