// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape, isString, nullable } from "../../guards"
import { isRunEvent } from "./RunEvent"
import { isRunNode } from "./RunNode"
import { isRunRecord } from "./RunRecord"

export function isRunView(value: unknown): value is Api.RunView {
  return isShape(value, {
    events: arrayOf(isRunEvent),
    eventsCursor: nullable(isString),
    eventsHasMore: isBoolean,
    nodes: arrayOf(isRunNode),
    run: isRunRecord,
  })
}
