// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isFiniteNumber, isShape, isString } from "../../guards"

export function isSuggestionEvidence(value: unknown): value is Api.SuggestionEvidence {
  return isShape(value, {
    kind: isString,
    snippet: isString,
    sourceRef: isString,
  }, {
    label: isString,
    weight: isFiniteNumber,
  })
}
