// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { anyOf, isString, literal, nullable, shape } from "../../guards"

export function isTriggerIngestResponse(value: unknown): value is Api.TriggerIngestResponse {
  return anyOf(shape({
    ok: literal(true),
    runId: isString,
    triggerEventId: isString,
  }), shape({
    duplicate: literal(true),
    ok: literal(true),
    runId: nullable(isString),
    triggerEventId: isString,
  }), shape({
    buffered: literal(true),
    ok: literal(true),
    reason: isString,
    triggerEventId: isString,
  }))(value)
}
