// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { literal } from "../../guards"

export function isValidationEvidenceLevel(value: unknown): value is Api.ValidationEvidenceLevel {
  return literal(null, "static", "writes_skipped", "provider_simulated", "live_canary")(value)
}
