// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isShape, isString, literal } from "../../guards"
import { isCanonicalWorkflowDoc } from "./CanonicalWorkflowDoc"
import { isRecoveryPassport } from "./RecoveryPassport"
import { isSuggestionEvidence } from "./SuggestionEvidence"
import { isWorkflowSuggestion } from "./WorkflowSuggestion"

export function isWorkflowPatchResponse(value: unknown): value is Api.WorkflowPatchResponse {
  return isShape(value, {
    evidence: arrayOf(isSuggestionEvidence),
    mode: literal("ai", "fallback"),
    rationale: isString,
    recoveryPassport: isRecoveryPassport,
    suggestedWorkflow: isCanonicalWorkflowDoc,
    suggestions: arrayOf(isWorkflowSuggestion),
  }, {
    aiError: isString,
    model: isString,
    provider: isString,
  })
}
