// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isInteger, isShape, isString, nullable } from "../../guards"

export function isWorkflowRollout(value: unknown): value is Api.WorkflowRollout {
  return isShape(value, {
    baselineFailed: isInteger,
    baselineSucceeded: isInteger,
    baselineVersionId: isString,
    canaryFailed: isInteger,
    canarySucceeded: isInteger,
    canaryVersionId: isString,
    createdAt: isString,
    endedAt: nullable(isString),
    id: isString,
    lastOutcomeAt: nullable(isString),
    minimumSampleSize: isInteger,
    minimumSuccessRatePercent: isInteger,
    rolledBackReason: nullable(isString),
    status: isString,
    trafficPercent: isInteger,
    updatedAt: isString,
    workflowId: isString,
  })
}
