// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isBoolean, isShape, isString, literal } from "../../guards"
import { isWorkflowIntentBrief } from "./WorkflowIntentBrief"

export function isWorkflowBriefCompilation(value: unknown): value is Api.WorkflowBriefCompilation {
  return isShape(value, {
    brief: isWorkflowIntentBrief,
    clarifyingQuestions: arrayOf(isString),
    complete: isBoolean,
    mode: literal("deterministic"),
  })
}
