// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { isShape, isString } from "../../guards"
import { isQualificationSummary } from "./QualificationSummary"

export function isWorkflowQualification(value: unknown): value is Api.WorkflowQualification {
  return isShape(value, {
    baselineVersionId: isString,
    candidateVersionId: isString,
    createdAt: isString,
    datasetDigest: isString,
    datasetVersion: isString,
    id: isString,
    mode: isString,
    status: isString,
    summary: isQualificationSummary,
    workflowId: isString,
  })
}
