// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isInteger, isShape, isString, nullable } from "../../guards"

export function isWorkflowListItem(value: unknown): value is Api.WorkflowListItem {
  return isShape(value, {
    bufferedTriggerCount: isInteger,
    createdAt: nullable(isString),
    createdBy: nullable(isString),
    deletedAt: nullable(isString),
    folder: nullable(isString),
    id: isString,
    lastRunStatus: nullable(isString),
    name: isString,
    orgId: isString,
    pausedReason: nullable(isString),
    runCount: isInteger,
    status: isString,
    tags: arrayOf(isString),
  })
}
