// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isShape, isString } from "../../guards"

export function isWorkflowCapabilityBinding(value: unknown): value is Api.WorkflowCapabilityBinding {
  return isShape(value, {
    alternatives: arrayOf(isString),
    field: isString,
    kind: isString,
    nodeId: isString,
  }, {
    reason: isString,
    requested: isString,
    resolvedId: isString,
  })
}
