// GENERATED by scripts/generate-api-guards.mjs from contract/openapi.json.
// Do not edit: run `make generate` after changing the Go manifest.

import type * as Api from "../../api-types.generated"
import { arrayOf, isAny, isShape, isString, recordOf } from "../../guards"
import { isWorkflowEdgeDoc } from "./WorkflowEdgeDoc"
import { isWorkflowMetadataDoc } from "./WorkflowMetadataDoc"
import { isWorkflowNodeDoc } from "./WorkflowNodeDoc"
import { isWorkflowUIDoc } from "./WorkflowUIDoc"

export function isWorkflowSaveRequest(value: unknown): value is Api.WorkflowSaveRequest {
  return isShape(value, {
    edges: arrayOf(isWorkflowEdgeDoc),
    nodes: arrayOf(isWorkflowNodeDoc),
  }, {
    dslVersion: isString,
    id: isString,
    inputs: isAny,
    metadata: isWorkflowMetadataDoc,
    name: isString,
    outputs: recordOf(isString),
    recovery: isAny,
    templatePolicy: isString,
    ui: isWorkflowUIDoc,
    upstreamHealthSources: arrayOf(isString),
  })
}
