// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRunCompletionLock = `-- name: AcquireRunCompletionLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) AcquireRunCompletionLock(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, acquireRunCompletionLock, runID)
	return err
}

const claimBufferedTriggerEvents = `-- name: ClaimBufferedTriggerEvents :many
UPDATE trigger_events SET backfill_claim_token = $1, backfill_claimed_at = now()
WHERE trigger_events.id IN (
  SELECT te.id FROM trigger_events te
  WHERE te.org_id = $2 AND te.workflow_id = $3 AND te.status = 'buffered'
    AND te.backfill_claim_token IS NULL
  ORDER BY te.created_at ASC
  LIMIT $4
  FOR UPDATE SKIP LOCKED
)
RETURNING trigger_events.id, trigger_events.node_id, trigger_events.payload_json, trigger_events.created_at,
          trigger_events.workflow_version_id, trigger_events.workflow_rollout_id, trigger_events.workflow_rollout_variant
`

type ClaimBufferedTriggerEventsParams struct {
	ClaimToken pgtype.Text
	OrgID      string
	WorkflowID pgtype.Text
	PageLimit  int32
}

type ClaimBufferedTriggerEventsRow struct {
	ID                     string
	NodeID                 string
	PayloadJson            json.RawMessage
	CreatedAt              *time.Time
	WorkflowVersionID      string
	WorkflowRolloutID      pgtype.Text
	WorkflowRolloutVariant pgtype.Text
}

func (q *Queries) ClaimBufferedTriggerEvents(ctx context.Context, arg ClaimBufferedTriggerEventsParams) ([]ClaimBufferedTriggerEventsRow, error) {
	rows, err := q.db.Query(ctx, claimBufferedTriggerEvents,
		arg.ClaimToken,
		arg.OrgID,
		arg.WorkflowID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimBufferedTriggerEventsRow
	for rows.Next() {
		var i ClaimBufferedTriggerEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.WorkflowVersionID,
			&i.WorkflowRolloutID,
			&i.WorkflowRolloutVariant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDeadLetterReplay = `-- name: ClaimDeadLetterReplay :execrows
UPDATE dead_letters
SET replay_claimed_at = now(), status = 'replayed', replayed_at = now()
WHERE id = $1 AND org_id = $2 AND replay_claimed_at IS NULL
`

type ClaimDeadLetterReplayParams struct {
	ID    string
	OrgID string
}

func (q *Queries) ClaimDeadLetterReplay(ctx context.Context, arg ClaimDeadLetterReplayParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimDeadLetterReplay, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueParentNotifications = `-- name: ClaimDueParentNotifications :many
UPDATE runs SET parent_notification_after = $1
WHERE id IN (
  SELECT due.id FROM runs AS due
  WHERE due.parent_notification_after <= $2
    AND due.status IN ('succeeded', 'failed', 'cancelled', 'timed_out')
  ORDER BY due.parent_notification_after
  LIMIT $3
  FOR UPDATE SKIP LOCKED
)
RETURNING id, status
`

type ClaimDueParentNotificationsParams struct {
	LeaseUntil *time.Time
	Now        *time.Time
	RowLimit   int32
}

type ClaimDueParentNotificationsRow struct {
	ID     string
	Status string
}

func (q *Queries) ClaimDueParentNotifications(ctx context.Context, arg ClaimDueParentNotificationsParams) ([]ClaimDueParentNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueParentNotifications, arg.LeaseUntil, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueParentNotificationsRow
	for rows.Next() {
		var i ClaimDueParentNotificationsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueReplayCampaign = `-- name: ClaimDueReplayCampaign :one
UPDATE replay_campaigns
SET next_dispatch_at = now() + make_interval(secs => pacing_ms / 1000.0),
    updated_at = now()
WHERE id = (
  SELECT id FROM replay_campaigns
  WHERE status = 'running' AND next_dispatch_at <= now()
  ORDER BY next_dispatch_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED)
RETURNING id, org_id, name, cluster_signature, filter_json, pacing_ms, status, total_count, replayed_count, failed_count, cancelled_count, created_by, cancelled_by, next_dispatch_at, started_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) ClaimDueReplayCampaign(ctx context.Context) (ReplayCampaign, error) {
	row := q.db.QueryRow(ctx, claimDueReplayCampaign)
	var i ReplayCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterSignature,
		&i.FilterJson,
		&i.PacingMs,
		&i.Status,
		&i.TotalCount,
		&i.ReplayedCount,
		&i.FailedCount,
		&i.CancelledCount,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.NextDispatchAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDueScheduleEntries = `-- name: ClaimDueScheduleEntries :many
UPDATE schedule_entries SET next_fire_at = $1
WHERE id IN (
  SELECT due.id FROM schedule_entries AS due
  WHERE due.enabled = true AND due.next_fire_at <= $2
  ORDER BY due.next_fire_at
  LIMIT $3
  FOR UPDATE SKIP LOCKED
)
RETURNING id, org_id, workflow_id, workflow_version_id, node_id, cron_expression, enabled, last_run_at, last_run_id, created_by, created_at, updated_at, next_fire_at
`

type ClaimDueScheduleEntriesParams struct {
	LeaseUntil *time.Time
	Now        *time.Time
	RowLimit   int32
}

func (q *Queries) ClaimDueScheduleEntries(ctx context.Context, arg ClaimDueScheduleEntriesParams) ([]ScheduleEntry, error) {
	rows, err := q.db.Query(ctx, claimDueScheduleEntries, arg.LeaseUntil, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleEntry
	for rows.Next() {
		var i ScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.NodeID,
			&i.CronExpression,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastRunID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextFireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNextReplayCampaignItem = `-- name: ClaimNextReplayCampaignItem :one
UPDATE replay_campaign_items
SET status = 'processing', claim_token = $1,
    claimed_at = now(), attempt_count = attempt_count + 1
WHERE replay_campaign_items.id = (
  SELECT i.id FROM replay_campaign_items i
  WHERE i.campaign_id = $2 AND i.status = 'pending'
  ORDER BY i.position
  LIMIT 1
  FOR UPDATE SKIP LOCKED)
RETURNING id, org_id, campaign_id, dead_letter_id, position, status, attempt_count, claim_token, claimed_at, error, completed_at, created_at
`

type ClaimNextReplayCampaignItemParams struct {
	ClaimToken pgtype.Text
	CampaignID string
}

func (q *Queries) ClaimNextReplayCampaignItem(ctx context.Context, arg ClaimNextReplayCampaignItemParams) (ReplayCampaignItem, error) {
	row := q.db.QueryRow(ctx, claimNextReplayCampaignItem, arg.ClaimToken, arg.CampaignID)
	var i ReplayCampaignItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CampaignID,
		&i.DeadLetterID,
		&i.Position,
		&i.Status,
		&i.AttemptCount,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.Error,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const claimStartIdempotencyKey = `-- name: ClaimStartIdempotencyKey :execrows
INSERT INTO go_pilot_start_idempotency (org_id, idempotency_key, run_id)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, idempotency_key) DO NOTHING
`

type ClaimStartIdempotencyKeyParams struct {
	OrgID          string
	IdempotencyKey string
	RunID          string
}

func (q *Queries) ClaimStartIdempotencyKey(ctx context.Context, arg ClaimStartIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimStartIdempotencyKey, arg.OrgID, arg.IdempotencyKey, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTriggerEventStart = `-- name: ClaimTriggerEventStart :execrows
UPDATE trigger_events
SET status = 'started', run_id = $3, skipped_reason = NULL,
    backfill_claim_token = NULL, backfill_claimed_at = NULL
WHERE org_id = $1 AND id = $2 AND status IN ('received', 'buffered') AND run_id IS NULL
`

type ClaimTriggerEventStartParams struct {
	OrgID string
	ID    string
	RunID pgtype.Text
}

// Accepts 'received' (the ordinary ingest path) AND 'buffered' (the
// breaker-resume backfill): both are "owed a run" states, and the CAS
// keeps a concurrent backfill/relay from spawning a second run.
func (q *Queries) ClaimTriggerEventStart(ctx context.Context, arg ClaimTriggerEventStartParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimTriggerEventStart, arg.OrgID, arg.ID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWakeup = `-- name: DeleteWakeup :exec
DELETE FROM go_pilot_wakeups WHERE run_node_id = $1
`

func (q *Queries) DeleteWakeup(ctx context.Context, runNodeID string) error {
	_, err := q.db.Exec(ctx, deleteWakeup, runNodeID)
	return err
}

const findStalledRunningNodes = `-- name: FindStalledRunningNodes :many
SELECT rn.id, rn.run_id, rn.node_id, COALESCE(rn.attempts, 1)::int AS attempt
FROM run_nodes rn
JOIN runs r ON r.id = rn.run_id
WHERE rn.status = 'running'
  AND rn.started_at < now() - make_interval(secs => $1::float8)
  AND r.status IN ('running', 'failed')
ORDER BY rn.started_at
LIMIT $2
`

type FindStalledRunningNodesParams struct {
	ThresholdSeconds float64
	BatchSize        int32
}

type FindStalledRunningNodesRow struct {
	ID      string
	RunID   string
	NodeID  string
	Attempt int32
}

func (q *Queries) FindStalledRunningNodes(ctx context.Context, arg FindStalledRunningNodesParams) ([]FindStalledRunningNodesRow, error) {
	rows, err := q.db.Query(ctx, findStalledRunningNodes, arg.ThresholdSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindStalledRunningNodesRow
	for rows.Next() {
		var i FindStalledRunningNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunNodeRecoveryClaim = `-- name: GetRunNodeRecoveryClaim :one
SELECT recovery_dead_letter_id, recovery_requested_by, recovery_claim_token,
       recovery_playbook_id, recovery_validation_run_id
FROM run_nodes WHERE run_id = $1 AND node_id = $2
`

type GetRunNodeRecoveryClaimParams struct {
	RunID  string
	NodeID string
}

type GetRunNodeRecoveryClaimRow struct {
	RecoveryDeadLetterID    pgtype.Text
	RecoveryRequestedBy     pgtype.Text
	RecoveryClaimToken      pgtype.Text
	RecoveryPlaybookID      pgtype.Text
	RecoveryValidationRunID pgtype.Text
}

func (q *Queries) GetRunNodeRecoveryClaim(ctx context.Context, arg GetRunNodeRecoveryClaimParams) (GetRunNodeRecoveryClaimRow, error) {
	row := q.db.QueryRow(ctx, getRunNodeRecoveryClaim, arg.RunID, arg.NodeID)
	var i GetRunNodeRecoveryClaimRow
	err := row.Scan(
		&i.RecoveryDeadLetterID,
		&i.RecoveryRequestedBy,
		&i.RecoveryClaimToken,
		&i.RecoveryPlaybookID,
		&i.RecoveryValidationRunID,
	)
	return i, err
}

const listDueWaitingWakeups = `-- name: ListDueWaitingWakeups :many
SELECT run_node_id, run_id, node_id, wake_at, reason
FROM (
  SELECT w.run_node_id, rn.run_id, rn.node_id, w.wake_at, w.reason,
         ROW_NUMBER() OVER (PARTITION BY rn.run_id ORDER BY w.wake_at, w.run_node_id) AS run_rank
  FROM go_pilot_wakeups w
  JOIN run_nodes rn ON rn.id = w.run_node_id
  JOIN runs r ON r.id = rn.run_id
  WHERE w.wake_at <= now() AND rn.status = 'waiting'
    AND r.status = 'running'
    AND w.reason IN ('wait_until', 'approval_timeout')
) ranked
ORDER BY run_rank, run_node_id
LIMIT $1
`

type ListDueWaitingWakeupsRow struct {
	RunNodeID string
	RunID     string
	NodeID    string
	WakeAt    time.Time
	Reason    string
}

func (q *Queries) ListDueWaitingWakeups(ctx context.Context, batchSize int32) ([]ListDueWaitingWakeupsRow, error) {
	rows, err := q.db.Query(ctx, listDueWaitingWakeups, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueWaitingWakeupsRow
	for rows.Next() {
		var i ListDueWaitingWakeupsRow
		if err := rows.Scan(
			&i.RunNodeID,
			&i.RunID,
			&i.NodeID,
			&i.WakeAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWakeups = `-- name: ListDueWakeups :many
SELECT run_node_id, wake_at, reason
FROM go_pilot_wakeups
WHERE wake_at <= now()
ORDER BY wake_at
LIMIT $1
`

func (q *Queries) ListDueWakeups(ctx context.Context, limit int32) ([]GoPilotWakeup, error) {
	rows, err := q.db.Query(ctx, listDueWakeups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoPilotWakeup
	for rows.Next() {
		var i GoPilotWakeup
		if err := rows.Scan(&i.RunNodeID, &i.WakeAt, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClaimableRunNodes = `-- name: LockClaimableRunNodes :many
SELECT rn.id
FROM run_nodes rn
JOIN runs r ON r.id = rn.run_id
WHERE rn.status = 'queued' AND r.status = 'running'
  AND NOT EXISTS (
    SELECT 1 FROM go_pilot_wakeups w
    WHERE w.run_node_id = rn.id AND w.wake_at > now()
  )
ORDER BY rn.id
LIMIT $1
FOR UPDATE OF rn SKIP LOCKED
`

func (q *Queries) LockClaimableRunNodes(ctx context.Context, batchSize int32) ([]string, error) {
	rows, err := q.db.Query(ctx, lockClaimableRunNodes, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLockedNodesRunning = `-- name: MarkLockedNodesRunning :many
UPDATE run_nodes SET status = 'running', started_at = now()
WHERE id = ANY($1::text[])
  AND status = 'queued'
  AND NOT EXISTS (
    SELECT 1 FROM go_pilot_wakeups w
    WHERE w.run_node_id = run_nodes.id AND w.wake_at > now()
  )
RETURNING id, run_id, node_id, COALESCE(attempts, 1)::int AS attempt
`

type MarkLockedNodesRunningRow struct {
	ID      string
	RunID   string
	NodeID  string
	Attempt int32
}

func (q *Queries) MarkLockedNodesRunning(ctx context.Context, ids []string) ([]MarkLockedNodesRunningRow, error) {
	rows, err := q.db.Query(ctx, markLockedNodesRunning, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkLockedNodesRunningRow
	for rows.Next() {
		var i MarkLockedNodesRunningRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyRunEvents = `-- name: NotifyRunEvents :exec
SELECT pg_notify('janusly_go_run_events', $1::text)
`

func (q *Queries) NotifyRunEvents(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, notifyRunEvents, runID)
	return err
}

const queryQueueHealth = `-- name: QueryQueueHealth :one
WITH eligible AS (
  SELECT rn.id, rn.run_id, rn.node_id
  FROM run_nodes rn
  JOIN runs r ON r.id = rn.run_id
  WHERE rn.status = 'queued' AND r.status = 'running'
    AND NOT EXISTS (
      SELECT 1 FROM go_pilot_wakeups w
      WHERE w.run_node_id = rn.id AND w.wake_at > now())
)
SELECT
  (SELECT count(*) FROM eligible)::int AS waiting,
  (SELECT count(*) FROM run_nodes WHERE status = 'running')::int AS active,
  (SELECT min(candidate) FROM (
     SELECT GREATEST(
       COALESCE((SELECT max(ev.created_at) FROM run_events ev
         WHERE ev.run_id = e.run_id AND ev.node_id = e.node_id
           AND ev.type = 'node.queued'), '-infinity'::timestamptz),
       COALESCE((SELECT w.wake_at FROM go_pilot_wakeups w
         WHERE w.run_node_id = e.id), '-infinity'::timestamptz)
     ) AS candidate FROM eligible e
   ) instants
   WHERE candidate > '-infinity'::timestamptz) AS oldest_eligible_at
`

type QueryQueueHealthRow struct {
	Waiting          int32
	Active           int32
	OldestEligibleAt interface{}
}

func (q *Queries) QueryQueueHealth(ctx context.Context) (QueryQueueHealthRow, error) {
	row := q.db.QueryRow(ctx, queryQueueHealth)
	var i QueryQueueHealthRow
	err := row.Scan(&i.Waiting, &i.Active, &i.OldestEligibleAt)
	return i, err
}

const queueRunNode = `-- name: QueueRunNode :execrows

UPDATE run_nodes SET status = 'queued', attempts = 1
WHERE run_id = $1 AND node_id = $2 AND status = 'pending'
`

type QueueRunNodeParams struct {
	RunID  string
	NodeID string
}

// Dispatch plane: claims, queue publication, wakeups, locks, reaper.
func (q *Queries) QueueRunNode(ctx context.Context, arg QueueRunNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, queueRunNode, arg.RunID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampRedriveRecoveryClaim = `-- name: StampRedriveRecoveryClaim :exec
UPDATE run_nodes
SET recovery_dead_letter_id = $3, recovery_requested_by = $4, recovery_claim_token = $5,
    recovery_playbook_id = $6, recovery_validation_run_id = $7
WHERE run_id = $1 AND node_id = $2
`

type StampRedriveRecoveryClaimParams struct {
	RunID                   string
	NodeID                  string
	RecoveryDeadLetterID    pgtype.Text
	RecoveryRequestedBy     pgtype.Text
	RecoveryClaimToken      pgtype.Text
	RecoveryPlaybookID      pgtype.Text
	RecoveryValidationRunID pgtype.Text
}

func (q *Queries) StampRedriveRecoveryClaim(ctx context.Context, arg StampRedriveRecoveryClaimParams) error {
	_, err := q.db.Exec(ctx, stampRedriveRecoveryClaim,
		arg.RunID,
		arg.NodeID,
		arg.RecoveryDeadLetterID,
		arg.RecoveryRequestedBy,
		arg.RecoveryClaimToken,
		arg.RecoveryPlaybookID,
		arg.RecoveryValidationRunID,
	)
	return err
}

const sweepDueWakeups = `-- name: SweepDueWakeups :execrows
DELETE FROM go_pilot_wakeups w
WHERE w.wake_at <= now()
  AND NOT EXISTS (
    SELECT 1 FROM run_nodes rn
    WHERE rn.id = w.run_node_id AND rn.status = 'waiting'
  )
`

func (q *Queries) SweepDueWakeups(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepDueWakeups)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWakeup = `-- name: UpsertWakeup :exec
INSERT INTO go_pilot_wakeups (run_node_id, wake_at, reason)
VALUES ($1, $2, $3)
ON CONFLICT (run_node_id) DO UPDATE SET wake_at = EXCLUDED.wake_at, reason = EXCLUDED.reason
`

type UpsertWakeupParams struct {
	RunNodeID string
	WakeAt    time.Time
	Reason    string
}

func (q *Queries) UpsertWakeup(ctx context.Context, arg UpsertWakeupParams) error {
	_, err := q.db.Exec(ctx, upsertWakeup, arg.RunNodeID, arg.WakeAt, arg.Reason)
	return err
}
