// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE invitations SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'pending'
`

// The accept CAS: only a still-pending row flips, exactly once.
func (q *Queries) AcceptInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMembersInRole = `-- name: CountMembersInRole :one
SELECT count(*)::int FROM org_members WHERE org_id = $1 AND role = $2
`

type CountMembersInRoleParams struct {
	OrgID string
	Role  string
}

func (q *Queries) CountMembersInRole(ctx context.Context, arg CountMembersInRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, countMembersInRole, arg.OrgID, arg.Role)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :execrows
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrgRole = `-- name: DeleteOrgRole :execrows
DELETE FROM org_roles WHERE org_id = $1 AND name = $2
`

type DeleteOrgRoleParams struct {
	OrgID string
	Name  string
}

func (q *Queries) DeleteOrgRole(ctx context.Context, arg DeleteOrgRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgRole, arg.OrgID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOrgMemberByEmail = `-- name: FindOrgMemberByEmail :one
SELECT id, org_id, user_id, role FROM org_members
WHERE org_id = $1 AND lower(email) = lower($2)
`

type FindOrgMemberByEmailParams struct {
	OrgID string
	Lower string
}

type FindOrgMemberByEmailRow struct {
	ID     string
	OrgID  string
	UserID string
	Role   string
}

// Legacy-orphan lazy backfill: rows seeded with userId = email before
// invite-acceptance shipped migrate to the real provider UUID on first
// authenticated sign-in.
func (q *Queries) FindOrgMemberByEmail(ctx context.Context, arg FindOrgMemberByEmailParams) (FindOrgMemberByEmailRow, error) {
	row := q.db.QueryRow(ctx, findOrgMemberByEmail, arg.OrgID, arg.Lower)
	var i FindOrgMemberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const findOrgMemberRowByEmail = `-- name: FindOrgMemberRowByEmail :one
SELECT id FROM org_members WHERE org_id = $1 AND email = $2
`

type FindOrgMemberRowByEmailParams struct {
	OrgID string
	Email pgtype.Text
}

func (q *Queries) FindOrgMemberRowByEmail(ctx context.Context, arg FindOrgMemberRowByEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, findOrgMemberRowByEmail, arg.OrgID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findPendingInvitation = `-- name: FindPendingInvitation :one
SELECT id FROM invitations
WHERE org_id = $1 AND email = $2 AND status = 'pending'
`

type FindPendingInvitationParams struct {
	OrgID string
	Email string
}

func (q *Queries) FindPendingInvitation(ctx context.Context, arg FindPendingInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, findPendingInvitation, arg.OrgID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, org_id, email, role, status FROM invitations WHERE id = $1
`

type GetInvitationByIDRow struct {
	ID     string
	OrgID  string
	Email  string
	Role   string
	Status string
}

func (q *Queries) GetInvitationByID(ctx context.Context, id string) (GetInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i GetInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const getOrgMembership = `-- name: GetOrgMembership :one

SELECT id, org_id, user_id, role FROM org_members
WHERE org_id = $1 AND user_id = $2
`

type GetOrgMembershipParams struct {
	OrgID  string
	UserID string
}

type GetOrgMembershipRow struct {
	ID     string
	OrgID  string
	UserID string
	Role   string
}

// Membership, invitations, roles, permission overrides.
func (q *Queries) GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (GetOrgMembershipRow, error) {
	row := q.db.QueryRow(ctx, getOrgMembership, arg.OrgID, arg.UserID)
	var i GetOrgMembershipRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const getOrgRole = `-- name: GetOrgRole :one
SELECT id, org_id, name, inherits_from, description, is_builtin, granted_permissions
FROM org_roles
WHERE org_id = $1 AND name = $2
`

type GetOrgRoleParams struct {
	OrgID string
	Name  string
}

type GetOrgRoleRow struct {
	ID                 string
	OrgID              string
	Name               string
	InheritsFrom       string
	Description        pgtype.Text
	IsBuiltin          bool
	GrantedPermissions json.RawMessage
}

func (q *Queries) GetOrgRole(ctx context.Context, arg GetOrgRoleParams) (GetOrgRoleRow, error) {
	row := q.db.QueryRow(ctx, getOrgRole, arg.OrgID, arg.Name)
	var i GetOrgRoleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.InheritsFrom,
		&i.Description,
		&i.IsBuiltin,
		&i.GrantedPermissions,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, name, email FROM users WHERE id = $1
`

type GetUserProfileRow struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) GetUserProfile(ctx context.Context, id string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const insertFounderMembership = `-- name: InsertFounderMembership :exec
INSERT INTO org_members (id, org_id, user_id, email, role, invited_by)
VALUES ($1, $2, $3, $4, 'admin', NULL)
`

type InsertFounderMembershipParams struct {
	ID     string
	OrgID  string
	UserID string
	Email  pgtype.Text
}

// Founder membership is a strict insert: the organization id is new inside
// the same transaction, so a conflict is a real invariant violation.
func (q *Queries) InsertFounderMembership(ctx context.Context, arg InsertFounderMembershipParams) error {
	_, err := q.db.Exec(ctx, insertFounderMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Email,
	)
	return err
}

const insertIdentityOrganization = `-- name: InsertIdentityOrganization :exec
INSERT INTO organizations (id, name, plan)
VALUES ($1, $2, 'free')
`

type InsertIdentityOrganizationParams struct {
	ID   string
	Name string
}

func (q *Queries) InsertIdentityOrganization(ctx context.Context, arg InsertIdentityOrganizationParams) error {
	_, err := q.db.Exec(ctx, insertIdentityOrganization, arg.ID, arg.Name)
	return err
}

const insertInstalledPlugin = `-- name: InsertInstalledPlugin :exec
INSERT INTO installed_plugins (id, org_id, plugin_id, config_json, installed_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInstalledPluginParams struct {
	ID          string
	OrgID       string
	PluginID    string
	ConfigJson  json.RawMessage
	InstalledBy pgtype.Text
}

func (q *Queries) InsertInstalledPlugin(ctx context.Context, arg InsertInstalledPluginParams) error {
	_, err := q.db.Exec(ctx, insertInstalledPlugin,
		arg.ID,
		arg.OrgID,
		arg.PluginID,
		arg.ConfigJson,
		arg.InstalledBy,
	)
	return err
}

const insertInvitation = `-- name: InsertInvitation :exec
INSERT INTO invitations (id, org_id, email, role, invited_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInvitationParams struct {
	ID        string
	OrgID     string
	Email     string
	Role      string
	InvitedBy pgtype.Text
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) error {
	_, err := q.db.Exec(ctx, insertInvitation,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const insertOrgMember = `-- name: InsertOrgMember :execrows
INSERT INTO org_members (id, org_id, user_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertOrgMemberParams struct {
	ID     string
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) InsertOrgMember(ctx context.Context, arg InsertOrgMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOrgMember,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOrgRole = `-- name: InsertOrgRole :exec
INSERT INTO org_roles (id, org_id, name, inherits_from, description, is_builtin, granted_permissions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrgRoleParams struct {
	ID                 string
	OrgID              string
	Name               string
	InheritsFrom       string
	Description        pgtype.Text
	IsBuiltin          bool
	GrantedPermissions json.RawMessage
}

func (q *Queries) InsertOrgRole(ctx context.Context, arg InsertOrgRoleParams) error {
	_, err := q.db.Exec(ctx, insertOrgRole,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.InheritsFrom,
		arg.Description,
		arg.IsBuiltin,
		arg.GrantedPermissions,
	)
	return err
}

const listIdentityInvitations = `-- name: ListIdentityInvitations :many
SELECT i.id, i.org_id, i.role, o.name AS organization_name
FROM invitations i
LEFT JOIN organizations o ON o.id = i.org_id
WHERE lower(i.email) = lower($1::text) AND i.status = 'pending'
ORDER BY i.created_at, i.id
LIMIT 51
`

type ListIdentityInvitationsRow struct {
	ID               string
	OrgID            string
	Role             string
	OrganizationName pgtype.Text
}

func (q *Queries) ListIdentityInvitations(ctx context.Context, email string) ([]ListIdentityInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityInvitations, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityInvitationsRow
	for rows.Next() {
		var i ListIdentityInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Role,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityMemberships = `-- name: ListIdentityMemberships :many
SELECT m.org_id, m.role, o.name AS organization_name, o.plan AS organization_plan
FROM org_members m
LEFT JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY o.name, m.org_id
LIMIT 201
`

type ListIdentityMembershipsRow struct {
	OrgID            string
	Role             string
	OrganizationName pgtype.Text
	OrganizationPlan pgtype.Text
}

// Identity bootstrap uses one extra row to report truncation without an
// unbounded count. The LEFT JOIN preserves orphan-tolerant membership truth.
func (q *Queries) ListIdentityMemberships(ctx context.Context, userID string) ([]ListIdentityMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityMembershipsRow
	for rows.Next() {
		var i ListIdentityMembershipsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Role,
			&i.OrganizationName,
			&i.OrganizationPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgInvitations = `-- name: ListOrgInvitations :many
SELECT id, org_id, email, role, invited_by, status, accepted_at, created_at
FROM invitations WHERE org_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListOrgInvitations(ctx context.Context, orgID string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listOrgInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.Status,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT id, org_id, user_id, email, role, invited_by, created_at
FROM org_members WHERE org_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID string) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgMember
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembershipsForUser = `-- name: ListOrgMembershipsForUser :many
SELECT id, org_id, user_id, role FROM org_members
WHERE user_id = $1
ORDER BY created_at, id
`

type ListOrgMembershipsForUserRow struct {
	ID     string
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) ListOrgMembershipsForUser(ctx context.Context, userID string) ([]ListOrgMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembershipsForUserRow
	for rows.Next() {
		var i ListOrgMembershipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgRoles = `-- name: ListOrgRoles :many
SELECT id, org_id, name, inherits_from, description, is_builtin, granted_permissions
FROM org_roles WHERE org_id = $1
ORDER BY name
`

type ListOrgRolesRow struct {
	ID                 string
	OrgID              string
	Name               string
	InheritsFrom       string
	Description        pgtype.Text
	IsBuiltin          bool
	GrantedPermissions json.RawMessage
}

func (q *Queries) ListOrgRoles(ctx context.Context, orgID string) ([]ListOrgRolesRow, error) {
	rows, err := q.db.Query(ctx, listOrgRoles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgRolesRow
	for rows.Next() {
		var i ListOrgRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.InheritsFrom,
			&i.Description,
			&i.IsBuiltin,
			&i.GrantedPermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many

SELECT m.org_id, m.role, coalesce(o.name, m.org_id) AS organization_name, o.plan
FROM org_members m
LEFT JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY m.org_id
LIMIT 50
`

type ListUserMembershipsRow struct {
	OrgID            string
	Role             string
	OrganizationName string
	Plan             pgtype.Text
}

// Identity surfaces: the caller's memberships with org names,
// profile upsert, the invitation-accept CAS, and the plugin stub row.
func (q *Queries) ListUserMemberships(ctx context.Context, userID string) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Role,
			&i.OrganizationName,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingIdentityInvitation = `-- name: LockPendingIdentityInvitation :one
SELECT id, org_id, email, role, invited_by
FROM invitations
WHERE id = $1
  AND lower(email) = lower($2::text)
  AND status = 'pending'
FOR UPDATE
`

type LockPendingIdentityInvitationParams struct {
	ID    string
	Email string
}

type LockPendingIdentityInvitationRow struct {
	ID        string
	OrgID     string
	Email     string
	Role      string
	InvitedBy pgtype.Text
}

func (q *Queries) LockPendingIdentityInvitation(ctx context.Context, arg LockPendingIdentityInvitationParams) (LockPendingIdentityInvitationRow, error) {
	row := q.db.QueryRow(ctx, lockPendingIdentityInvitation, arg.ID, arg.Email)
	var i LockPendingIdentityInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
	)
	return i, err
}

const markIdentityInvitationAccepted = `-- name: MarkIdentityInvitationAccepted :execrows
UPDATE invitations
SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkIdentityInvitationAccepted(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markIdentityInvitationAccepted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const migrateOrgMemberUserID = `-- name: MigrateOrgMemberUserID :execrows
UPDATE org_members SET user_id = $3
WHERE id = $1 AND org_id = $2
`

type MigrateOrgMemberUserIDParams struct {
	ID     string
	OrgID  string
	UserID string
}

func (q *Queries) MigrateOrgMemberUserID(ctx context.Context, arg MigrateOrgMemberUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, migrateOrgMemberUserID, arg.ID, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePendingInvitation = `-- name: RevokePendingInvitation :execrows
UPDATE invitations SET status = 'revoked'
WHERE id = $1 AND org_id = $2 AND status = 'pending'
`

type RevokePendingInvitationParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RevokePendingInvitation(ctx context.Context, arg RevokePendingInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePendingInvitation, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :execrows
UPDATE org_members SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrgRole = `-- name: UpdateOrgRole :one
UPDATE org_roles
SET granted_permissions = COALESCE($3, granted_permissions),
    description = COALESCE($4, description),
    inherits_from = COALESCE($5, inherits_from)
WHERE org_id = $1 AND name = $2
RETURNING id, org_id, name, inherits_from, description, is_builtin, granted_permissions
`

type UpdateOrgRoleParams struct {
	OrgID              string
	Name               string
	GrantedPermissions json.RawMessage
	Description        pgtype.Text
	InheritsFrom       pgtype.Text
}

type UpdateOrgRoleRow struct {
	ID                 string
	OrgID              string
	Name               string
	InheritsFrom       string
	Description        pgtype.Text
	IsBuiltin          bool
	GrantedPermissions json.RawMessage
}

func (q *Queries) UpdateOrgRole(ctx context.Context, arg UpdateOrgRoleParams) (UpdateOrgRoleRow, error) {
	row := q.db.QueryRow(ctx, updateOrgRole,
		arg.OrgID,
		arg.Name,
		arg.GrantedPermissions,
		arg.Description,
		arg.InheritsFrom,
	)
	var i UpdateOrgRoleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.InheritsFrom,
		&i.Description,
		&i.IsBuiltin,
		&i.GrantedPermissions,
	)
	return i, err
}

const upsertIdentityProfile = `-- name: UpsertIdentityProfile :one
INSERT INTO users (id, name, email, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (id) DO UPDATE
SET name = coalesce(EXCLUDED.name, users.name),
    email = coalesce(EXCLUDED.email, users.email),
    updated_at = now()
RETURNING id, name, email
`

type UpsertIdentityProfileParams struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

type UpsertIdentityProfileRow struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

// Bootstrap profile upserts never erase an existing name/email merely because
// the current provider omitted that optional claim.
func (q *Queries) UpsertIdentityProfile(ctx context.Context, arg UpsertIdentityProfileParams) (UpsertIdentityProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertIdentityProfile, arg.ID, arg.Name, arg.Email)
	var i UpsertIdentityProfileRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const upsertInvitedIdentityMembership = `-- name: UpsertInvitedIdentityMembership :exec
INSERT INTO org_members (id, org_id, user_id, email, role, invited_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, user_id) DO UPDATE
SET email = EXCLUDED.email,
    role = EXCLUDED.role,
    invited_by = EXCLUDED.invited_by
`

type UpsertInvitedIdentityMembershipParams struct {
	ID        string
	OrgID     string
	UserID    string
	Email     pgtype.Text
	Role      string
	InvitedBy pgtype.Text
}

// The verified provider id is the durable membership key. Re-acceptance of a
// newly issued invitation for the same org updates the existing grant exactly
// like the Node oracle.
func (q *Queries) UpsertInvitedIdentityMembership(ctx context.Context, arg UpsertInvitedIdentityMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertInvitedIdentityMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO users (id, name, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    email = coalesce(EXCLUDED.email, users.email),
    updated_at = now()
RETURNING id, name, email
`

type UpsertUserProfileParams struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

type UpsertUserProfileRow struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UpsertUserProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile, arg.ID, arg.Name, arg.Email)
	var i UpsertUserProfileRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
