// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playbooks.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDraftPlaybook = `-- name: ActivateDraftPlaybook :execrows
UPDATE recovery_playbooks
SET status = 'active', activated_at = now(), retired_at = NULL, updated_at = now(), updated_by = $3
WHERE org_id = $1 AND id = $2 AND status = 'draft'
`

type ActivateDraftPlaybookParams struct {
	OrgID string
	ID    string
	Actor pgtype.Text
}

func (q *Queries) ActivateDraftPlaybook(ctx context.Context, arg ActivateDraftPlaybookParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateDraftPlaybook, arg.OrgID, arg.ID, arg.Actor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpReplayCampaignCounter = `-- name: BumpReplayCampaignCounter :exec
UPDATE replay_campaigns
SET replayed_count = replayed_count + $2::int,
    failed_count = failed_count + $3::int,
    updated_at = now()
WHERE id = $1
`

type BumpReplayCampaignCounterParams struct {
	ID       string
	Replayed int32
	Failed   int32
}

func (q *Queries) BumpReplayCampaignCounter(ctx context.Context, arg BumpReplayCampaignCounterParams) error {
	_, err := q.db.Exec(ctx, bumpReplayCampaignCounter, arg.ID, arg.Replayed, arg.Failed)
	return err
}

const cancelPendingReplayCampaignItems = `-- name: CancelPendingReplayCampaignItems :execrows
UPDATE replay_campaign_items SET status = 'cancelled', completed_at = now()
WHERE org_id = $1 AND campaign_id = $2 AND status = 'pending'
`

type CancelPendingReplayCampaignItemsParams struct {
	OrgID      string
	CampaignID string
}

func (q *Queries) CancelPendingReplayCampaignItems(ctx context.Context, arg CancelPendingReplayCampaignItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingReplayCampaignItems, arg.OrgID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeReplayCampaignIfExhausted = `-- name: CompleteReplayCampaignIfExhausted :one
UPDATE replay_campaigns
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE replay_campaigns.id = $1 AND replay_campaigns.status = 'running'
  AND NOT EXISTS (
    SELECT 1 FROM replay_campaign_items i
    WHERE i.campaign_id = $1 AND i.status IN ('pending', 'processing'))
RETURNING id, org_id, name, cluster_signature, filter_json, pacing_ms, status, total_count, replayed_count, failed_count, cancelled_count, created_by, cancelled_by, next_dispatch_at, started_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) CompleteReplayCampaignIfExhausted(ctx context.Context, id string) (ReplayCampaign, error) {
	row := q.db.QueryRow(ctx, completeReplayCampaignIfExhausted, id)
	var i ReplayCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterSignature,
		&i.FilterJson,
		&i.PacingMs,
		&i.Status,
		&i.TotalCount,
		&i.ReplayedCount,
		&i.FailedCount,
		&i.CancelledCount,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.NextDispatchAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLatestAcceptedRecoveryFeedback = `-- name: FindLatestAcceptedRecoveryFeedback :one
SELECT id, workflow_id, approach_label, suggestion_mode, created_at
FROM recovery_feedback
WHERE org_id = $1 AND dead_letter_id = $2 AND accepted = true
ORDER BY created_at DESC
LIMIT 1
`

type FindLatestAcceptedRecoveryFeedbackParams struct {
	OrgID        string
	DeadLetterID string
}

type FindLatestAcceptedRecoveryFeedbackRow struct {
	ID             string
	WorkflowID     string
	ApproachLabel  string
	SuggestionMode string
	CreatedAt      *time.Time
}

func (q *Queries) FindLatestAcceptedRecoveryFeedback(ctx context.Context, arg FindLatestAcceptedRecoveryFeedbackParams) (FindLatestAcceptedRecoveryFeedbackRow, error) {
	row := q.db.QueryRow(ctx, findLatestAcceptedRecoveryFeedback, arg.OrgID, arg.DeadLetterID)
	var i FindLatestAcceptedRecoveryFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ApproachLabel,
		&i.SuggestionMode,
		&i.CreatedAt,
	)
	return i, err
}

const findMatchingActivePlaybook = `-- name: FindMatchingActivePlaybook :one
SELECT p.id, p.org_id, p.workflow_id, p.signature, p.version, p.status, p.title, p.instructions_markdown, p.evidence_requirements_json, p.source_workflow_version_id, p.approach_label, p.successful_uses, p.regressions, p.last_validated_at, p.last_validation_run_id, p.last_applied_validation_run_id, p.activated_at, p.retired_at, p.created_by, p.updated_by, p.created_at, p.updated_at FROM recovery_playbooks p
WHERE p.org_id = $1 AND p.workflow_id = $2 AND p.signature = $3 AND p.status = 'active'
  AND EXISTS (
    SELECT 1 FROM workflows w
    WHERE w.id = p.workflow_id AND w.org_id = p.org_id AND w.deleted_at IS NULL
  )
  AND EXISTS (
    SELECT 1 FROM workflow_versions v
    WHERE v.id = p.source_workflow_version_id
      AND v.org_id = p.org_id AND v.workflow_id = p.workflow_id
  )
ORDER BY p.version DESC
LIMIT 1
`

type FindMatchingActivePlaybookParams struct {
	OrgID      string
	WorkflowID pgtype.Text
	Signature  string
}

func (q *Queries) FindMatchingActivePlaybook(ctx context.Context, arg FindMatchingActivePlaybookParams) (RecoveryPlaybook, error) {
	row := q.db.QueryRow(ctx, findMatchingActivePlaybook, arg.OrgID, arg.WorkflowID, arg.Signature)
	var i RecoveryPlaybook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Signature,
		&i.Version,
		&i.Status,
		&i.Title,
		&i.InstructionsMarkdown,
		&i.EvidenceRequirementsJson,
		&i.SourceWorkflowVersionID,
		&i.ApproachLabel,
		&i.SuccessfulUses,
		&i.Regressions,
		&i.LastValidatedAt,
		&i.LastValidationRunID,
		&i.LastAppliedValidationRunID,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPlaybookBySourceVersion = `-- name: FindPlaybookBySourceVersion :one
SELECT id, org_id, workflow_id, signature, version, status, title, instructions_markdown, evidence_requirements_json, source_workflow_version_id, approach_label, successful_uses, regressions, last_validated_at, last_validation_run_id, last_applied_validation_run_id, activated_at, retired_at, created_by, updated_by, created_at, updated_at FROM recovery_playbooks
WHERE org_id = $1 AND source_workflow_version_id = $2
`

type FindPlaybookBySourceVersionParams struct {
	OrgID                   string
	SourceWorkflowVersionID string
}

func (q *Queries) FindPlaybookBySourceVersion(ctx context.Context, arg FindPlaybookBySourceVersionParams) (RecoveryPlaybook, error) {
	row := q.db.QueryRow(ctx, findPlaybookBySourceVersion, arg.OrgID, arg.SourceWorkflowVersionID)
	var i RecoveryPlaybook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Signature,
		&i.Version,
		&i.Status,
		&i.Title,
		&i.InstructionsMarkdown,
		&i.EvidenceRequirementsJson,
		&i.SourceWorkflowVersionID,
		&i.ApproachLabel,
		&i.SuccessfulUses,
		&i.Regressions,
		&i.LastValidatedAt,
		&i.LastValidationRunID,
		&i.LastAppliedValidationRunID,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryPlaybook = `-- name: GetRecoveryPlaybook :one
SELECT id, org_id, workflow_id, signature, version, status, title, instructions_markdown, evidence_requirements_json, source_workflow_version_id, approach_label, successful_uses, regressions, last_validated_at, last_validation_run_id, last_applied_validation_run_id, activated_at, retired_at, created_by, updated_by, created_at, updated_at FROM recovery_playbooks WHERE org_id = $1 AND id = $2
`

type GetRecoveryPlaybookParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetRecoveryPlaybook(ctx context.Context, arg GetRecoveryPlaybookParams) (RecoveryPlaybook, error) {
	row := q.db.QueryRow(ctx, getRecoveryPlaybook, arg.OrgID, arg.ID)
	var i RecoveryPlaybook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Signature,
		&i.Version,
		&i.Status,
		&i.Title,
		&i.InstructionsMarkdown,
		&i.EvidenceRequirementsJson,
		&i.SourceWorkflowVersionID,
		&i.ApproachLabel,
		&i.SuccessfulUses,
		&i.Regressions,
		&i.LastValidatedAt,
		&i.LastValidationRunID,
		&i.LastAppliedValidationRunID,
		&i.ActivatedAt,
		&i.RetiredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReplayCampaign = `-- name: GetReplayCampaign :one
SELECT id, org_id, name, cluster_signature, filter_json, pacing_ms, status, total_count, replayed_count, failed_count, cancelled_count, created_by, cancelled_by, next_dispatch_at, started_at, completed_at, cancelled_at, created_at, updated_at FROM replay_campaigns WHERE org_id = $1 AND id = $2
`

type GetReplayCampaignParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetReplayCampaign(ctx context.Context, arg GetReplayCampaignParams) (ReplayCampaign, error) {
	row := q.db.QueryRow(ctx, getReplayCampaign, arg.OrgID, arg.ID)
	var i ReplayCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ClusterSignature,
		&i.FilterJson,
		&i.PacingMs,
		&i.Status,
		&i.TotalCount,
		&i.ReplayedCount,
		&i.FailedCount,
		&i.CancelledCount,
		&i.CreatedBy,
		&i.CancelledBy,
		&i.NextDispatchAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecoveryPlaybookDraft = `-- name: InsertRecoveryPlaybookDraft :exec
INSERT INTO recovery_playbooks (id, org_id, workflow_id, signature, version, status, title,
  instructions_markdown, evidence_requirements_json, source_workflow_version_id, approach_label,
  last_validated_at, last_validation_run_id, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, 'draft', $6, $7, $8, $9, $10, now(), $11, $12, $12)
`

type InsertRecoveryPlaybookDraftParams struct {
	ID                       string
	OrgID                    string
	WorkflowID               pgtype.Text
	Signature                string
	Version                  int32
	Title                    string
	InstructionsMarkdown     string
	EvidenceRequirementsJson json.RawMessage
	SourceWorkflowVersionID  string
	ApproachLabel            string
	LastValidationRunID      pgtype.Text
	CreatedBy                pgtype.Text
}

func (q *Queries) InsertRecoveryPlaybookDraft(ctx context.Context, arg InsertRecoveryPlaybookDraftParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryPlaybookDraft,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Signature,
		arg.Version,
		arg.Title,
		arg.InstructionsMarkdown,
		arg.EvidenceRequirementsJson,
		arg.SourceWorkflowVersionID,
		arg.ApproachLabel,
		arg.LastValidationRunID,
		arg.CreatedBy,
	)
	return err
}

const insertReplayCampaign = `-- name: InsertReplayCampaign :exec
INSERT INTO replay_campaigns (id, org_id, name, cluster_signature, filter_json,
                              pacing_ms, total_count, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertReplayCampaignParams struct {
	ID               string
	OrgID            string
	Name             string
	ClusterSignature string
	FilterJson       json.RawMessage
	PacingMs         int32
	TotalCount       int32
	CreatedBy        string
}

func (q *Queries) InsertReplayCampaign(ctx context.Context, arg InsertReplayCampaignParams) error {
	_, err := q.db.Exec(ctx, insertReplayCampaign,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ClusterSignature,
		arg.FilterJson,
		arg.PacingMs,
		arg.TotalCount,
		arg.CreatedBy,
	)
	return err
}

const insertReplayCampaignItem = `-- name: InsertReplayCampaignItem :exec
INSERT INTO replay_campaign_items (id, org_id, campaign_id, dead_letter_id, position)
VALUES ($1, $2, $3, $4, $5)
`

type InsertReplayCampaignItemParams struct {
	ID           string
	OrgID        string
	CampaignID   string
	DeadLetterID string
	Position     int32
}

func (q *Queries) InsertReplayCampaignItem(ctx context.Context, arg InsertReplayCampaignItemParams) error {
	_, err := q.db.Exec(ctx, insertReplayCampaignItem,
		arg.ID,
		arg.OrgID,
		arg.CampaignID,
		arg.DeadLetterID,
		arg.Position,
	)
	return err
}

const listDrillRootDeadLetters = `-- name: ListDrillRootDeadLetters :many
SELECT id FROM dead_letters
WHERE org_id = $1 AND replay_claimed_at IS NOT NULL
ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListDrillRootDeadLetters(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDrillRootDeadLetters, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayCampaignDeadLetters = `-- name: ListReplayCampaignDeadLetters :many

SELECT id, run_id, node_id, status, error_json, node_json
FROM dead_letters
WHERE org_id = $1 AND id = ANY($2::text[])
`

type ListReplayCampaignDeadLettersParams struct {
	OrgID string
	Ids   []string
}

type ListReplayCampaignDeadLettersRow struct {
	ID        string
	RunID     string
	NodeID    string
	Status    string
	ErrorJson json.RawMessage
	NodeJson  json.RawMessage
}

// Playbooks, replay campaigns, drills: evidencia y remediación guiada.
func (q *Queries) ListReplayCampaignDeadLetters(ctx context.Context, arg ListReplayCampaignDeadLettersParams) ([]ListReplayCampaignDeadLettersRow, error) {
	rows, err := q.db.Query(ctx, listReplayCampaignDeadLetters, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayCampaignDeadLettersRow
	for rows.Next() {
		var i ListReplayCampaignDeadLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Status,
			&i.ErrorJson,
			&i.NodeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayCampaignItems = `-- name: ListReplayCampaignItems :many
SELECT id, org_id, campaign_id, dead_letter_id, position, status, attempt_count, claim_token, claimed_at, error, completed_at, created_at FROM replay_campaign_items
WHERE org_id = $1 AND campaign_id = $2
ORDER BY position
`

type ListReplayCampaignItemsParams struct {
	OrgID      string
	CampaignID string
}

func (q *Queries) ListReplayCampaignItems(ctx context.Context, arg ListReplayCampaignItemsParams) ([]ReplayCampaignItem, error) {
	rows, err := q.db.Query(ctx, listReplayCampaignItems, arg.OrgID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayCampaignItem
	for rows.Next() {
		var i ReplayCampaignItem
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CampaignID,
			&i.DeadLetterID,
			&i.Position,
			&i.Status,
			&i.AttemptCount,
			&i.ClaimToken,
			&i.ClaimedAt,
			&i.Error,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayCampaigns = `-- name: ListReplayCampaigns :many
SELECT id, org_id, name, cluster_signature, filter_json, pacing_ms, status, total_count, replayed_count, failed_count, cancelled_count, created_by, cancelled_by, next_dispatch_at, started_at, completed_at, cancelled_at, created_at, updated_at FROM replay_campaigns
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReplayCampaignsParams struct {
	OrgID string
	Limit int32
}

func (q *Queries) ListReplayCampaigns(ctx context.Context, arg ListReplayCampaignsParams) ([]ReplayCampaign, error) {
	rows, err := q.db.Query(ctx, listReplayCampaigns, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayCampaign
	for rows.Next() {
		var i ReplayCampaign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ClusterSignature,
			&i.FilterJson,
			&i.PacingMs,
			&i.Status,
			&i.TotalCount,
			&i.ReplayedCount,
			&i.FailedCount,
			&i.CancelledCount,
			&i.CreatedBy,
			&i.CancelledBy,
			&i.NextDispatchAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPlaybookVersion = `-- name: MaxPlaybookVersion :one
SELECT COALESCE(max(version), 0)::int FROM recovery_playbooks
WHERE org_id = $1 AND signature = $2
`

type MaxPlaybookVersionParams struct {
	OrgID     string
	Signature string
}

func (q *Queries) MaxPlaybookVersion(ctx context.Context, arg MaxPlaybookVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxPlaybookVersion, arg.OrgID, arg.Signature)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordPlaybookApplied = `-- name: RecordPlaybookApplied :execrows
WITH claimed AS (
  UPDATE runs SET recovery_playbook_applied_recorded_at = now()
  WHERE org_id = $3 AND id = $1
    AND replay_mode = 'validation' AND recovery_playbook_applied_recorded_at IS NULL
    AND EXISTS (
      SELECT 1 FROM recovery_playbooks p
      WHERE p.org_id = $3 AND p.id = $4 AND p.status = 'active'
    )
  RETURNING 1
)
UPDATE recovery_playbooks
SET successful_uses = successful_uses + 1,
    last_applied_validation_run_id = $1,
    updated_at = now(), updated_by = $2
WHERE recovery_playbooks.org_id = $3 AND recovery_playbooks.id = $4
  AND recovery_playbooks.status = 'active'
  AND EXISTS (SELECT 1 FROM claimed)
`

type RecordPlaybookAppliedParams struct {
	ValidationRunID pgtype.Text
	Actor           pgtype.Text
	OrgID           string
	ID              string
}

func (q *Queries) RecordPlaybookApplied(ctx context.Context, arg RecordPlaybookAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPlaybookApplied,
		arg.ValidationRunID,
		arg.Actor,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPlaybookValidationRegression = `-- name: RecordPlaybookValidationRegression :execrows
WITH claimed AS (
  UPDATE runs SET recovery_playbook_validation_recorded_at = now()
  WHERE org_id = $3 AND id = $1
    AND replay_mode = 'validation' AND recovery_playbook_validation_recorded_at IS NULL
    AND EXISTS (
      SELECT 1 FROM recovery_playbooks p
      WHERE p.org_id = $3 AND p.id = $4
    )
  RETURNING 1
)
UPDATE recovery_playbooks
SET status = 'retired', retired_at = now(), regressions = regressions + 1,
    last_validation_run_id = $1, updated_at = now(),
    updated_by = $2
WHERE recovery_playbooks.org_id = $3 AND recovery_playbooks.id = $4
  AND EXISTS (SELECT 1 FROM claimed)
`

type RecordPlaybookValidationRegressionParams struct {
	ValidationRunID pgtype.Text
	Actor           pgtype.Text
	OrgID           string
	ID              string
}

func (q *Queries) RecordPlaybookValidationRegression(ctx context.Context, arg RecordPlaybookValidationRegressionParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPlaybookValidationRegression,
		arg.ValidationRunID,
		arg.Actor,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPlaybookValidationSuccess = `-- name: RecordPlaybookValidationSuccess :execrows
WITH claimed AS (
  UPDATE runs SET recovery_playbook_validation_recorded_at = now()
  WHERE org_id = $3 AND id = $1
    AND replay_mode = 'validation' AND recovery_playbook_validation_recorded_at IS NULL
    AND EXISTS (
      SELECT 1 FROM recovery_playbooks p
      WHERE p.org_id = $3 AND p.id = $4
    )
  RETURNING 1
)
UPDATE recovery_playbooks
SET last_validated_at = now(), last_validation_run_id = $1,
    updated_at = now(), updated_by = $2
WHERE recovery_playbooks.org_id = $3 AND recovery_playbooks.id = $4
  AND EXISTS (SELECT 1 FROM claimed)
`

type RecordPlaybookValidationSuccessParams struct {
	ValidationRunID pgtype.Text
	Actor           pgtype.Text
	OrgID           string
	ID              string
}

func (q *Queries) RecordPlaybookValidationSuccess(ctx context.Context, arg RecordPlaybookValidationSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPlaybookValidationSuccess,
		arg.ValidationRunID,
		arg.Actor,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoveryImpactExists = `-- name: RecoveryImpactExists :one
SELECT EXISTS (
  SELECT 1 FROM recovery_impact_events
  WHERE org_id = $1 AND dead_letter_id = $2
)::boolean
`

type RecoveryImpactExistsParams struct {
	OrgID        string
	DeadLetterID string
}

func (q *Queries) RecoveryImpactExists(ctx context.Context, arg RecoveryImpactExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recoveryImpactExists, arg.OrgID, arg.DeadLetterID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const retirePreviousActivePlaybookMatch = `-- name: RetirePreviousActivePlaybookMatch :execrows
UPDATE recovery_playbooks
SET status = 'retired', retired_at = now(), updated_at = now(), updated_by = $4
WHERE org_id = $1 AND workflow_id = $2 AND signature = $3 AND status = 'active' AND id <> $5
`

type RetirePreviousActivePlaybookMatchParams struct {
	OrgID      string
	WorkflowID pgtype.Text
	Signature  string
	Actor      pgtype.Text
	ExcludeID  string
}

func (q *Queries) RetirePreviousActivePlaybookMatch(ctx context.Context, arg RetirePreviousActivePlaybookMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, retirePreviousActivePlaybookMatch,
		arg.OrgID,
		arg.WorkflowID,
		arg.Signature,
		arg.Actor,
		arg.ExcludeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireRecoveryPlaybook = `-- name: RetireRecoveryPlaybook :execrows
UPDATE recovery_playbooks
SET status = 'retired', retired_at = now(), updated_at = now(), updated_by = $3
WHERE org_id = $1 AND id = $2 AND status <> 'retired'
`

type RetireRecoveryPlaybookParams struct {
	OrgID string
	ID    string
	Actor pgtype.Text
}

func (q *Queries) RetireRecoveryPlaybook(ctx context.Context, arg RetireRecoveryPlaybookParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireRecoveryPlaybook, arg.OrgID, arg.ID, arg.Actor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleReplayCampaignItem = `-- name: SettleReplayCampaignItem :execrows
UPDATE replay_campaign_items
SET status = $1, error = $2, completed_at = now()
WHERE id = $3 AND claim_token = $4 AND status = 'processing'
`

type SettleReplayCampaignItemParams struct {
	Status     string
	Error      pgtype.Text
	ID         string
	ClaimToken pgtype.Text
}

func (q *Queries) SettleReplayCampaignItem(ctx context.Context, arg SettleReplayCampaignItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleReplayCampaignItem,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
