// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRunCompletionLock = `-- name: AcquireRunCompletionLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Serializes node-completion transactions per run: the xact lock releases
// on commit, so a concurrent sibling's readiness scan always observes this
// completion — the fan-in gate for joins.
func (q *Queries) AcquireRunCompletionLock(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, acquireRunCompletionLock, runID)
	return err
}

const claimDeadLetterReplay = `-- name: ClaimDeadLetterReplay :execrows
UPDATE dead_letters SET replay_claimed_at = now()
WHERE id = $1 AND org_id = $2 AND replay_claimed_at IS NULL
`

type ClaimDeadLetterReplayParams struct {
	ID    string
	OrgID string
}

func (q *Queries) ClaimDeadLetterReplay(ctx context.Context, arg ClaimDeadLetterReplayParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimDeadLetterReplay, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimQueuedRunNodes = `-- name: ClaimQueuedRunNodes :many
UPDATE run_nodes SET status = 'running', started_at = now()
WHERE id IN (
  SELECT rn.id
  FROM run_nodes rn
  JOIN runs r ON r.id = rn.run_id
  WHERE rn.status = 'queued' AND r.status = 'running'
  ORDER BY rn.id
  LIMIT $1
  FOR UPDATE OF rn SKIP LOCKED
)
RETURNING id, run_id, node_id, COALESCE(attempts, 1)::int AS attempt
`

type ClaimQueuedRunNodesRow struct {
	ID      string
	RunID   string
	NodeID  string
	Attempt int32
}

// The claim is the queue's consume operation: SKIP LOCKED lets N workers
// pull disjoint rows without blocking each other, and the runs join keeps
// nodes of cancelled/failed runs from ever being picked up.
func (q *Queries) ClaimQueuedRunNodes(ctx context.Context, batchSize int32) ([]ClaimQueuedRunNodesRow, error) {
	rows, err := q.db.Query(ctx, claimQueuedRunNodes, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimQueuedRunNodesRow
	for rows.Next() {
		var i ClaimQueuedRunNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeRunNode = `-- name: CompleteRunNode :execrows
UPDATE run_nodes
SET status = 'succeeded', state_json = $1,
    finished_at = $2
WHERE run_id = $3 AND node_id = $4
  AND status = 'running'
`

type CompleteRunNodeParams struct {
	StateJson  json.RawMessage
	FinishedAt *time.Time
	RunID      string
	NodeID     string
}

func (q *Queries) CompleteRunNode(ctx context.Context, arg CompleteRunNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRunNode,
		arg.StateJson,
		arg.FinishedAt,
		arg.RunID,
		arg.NodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWakeup = `-- name: DeleteWakeup :exec
DELETE FROM go_pilot_wakeups WHERE run_node_id = $1
`

func (q *Queries) DeleteWakeup(ctx context.Context, runNodeID string) error {
	_, err := q.db.Exec(ctx, deleteWakeup, runNodeID)
	return err
}

const failRunNode = `-- name: FailRunNode :execrows
UPDATE run_nodes
SET status = 'failed', error_json = $1,
    finished_at = $2
WHERE run_id = $3 AND node_id = $4
  AND status = 'running'
`

type FailRunNodeParams struct {
	ErrorJson  json.RawMessage
	FinishedAt *time.Time
	RunID      string
	NodeID     string
}

func (q *Queries) FailRunNode(ctx context.Context, arg FailRunNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRunNode,
		arg.ErrorJson,
		arg.FinishedAt,
		arg.RunID,
		arg.NodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeadLetter = `-- name: GetDeadLetter :one
SELECT id, org_id, run_id, node_id, attempt, workflow_json, node_json,
       error_json, status, replayed_at, created_at, replay_claimed_at
FROM dead_letters
WHERE id = $1 AND org_id = $2
`

type GetDeadLetterParams struct {
	ID    string
	OrgID string
}

type GetDeadLetterRow struct {
	ID              string
	OrgID           string
	RunID           string
	NodeID          string
	Attempt         int32
	WorkflowJson    json.RawMessage
	NodeJson        json.RawMessage
	ErrorJson       json.RawMessage
	Status          string
	ReplayedAt      *time.Time
	CreatedAt       *time.Time
	ReplayClaimedAt *time.Time
}

func (q *Queries) GetDeadLetter(ctx context.Context, arg GetDeadLetterParams) (GetDeadLetterRow, error) {
	row := q.db.QueryRow(ctx, getDeadLetter, arg.ID, arg.OrgID)
	var i GetDeadLetterRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.NodeID,
		&i.Attempt,
		&i.WorkflowJson,
		&i.NodeJson,
		&i.ErrorJson,
		&i.Status,
		&i.ReplayedAt,
		&i.CreatedAt,
		&i.ReplayClaimedAt,
	)
	return i, err
}

const getLatestWorkflowVersion = `-- name: GetLatestWorkflowVersion :one
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowVersionParams struct {
	WorkflowID string
	OrgID      string
}

type GetLatestWorkflowVersionRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) GetLatestWorkflowVersion(ctx context.Context, arg GetLatestWorkflowVersionParams) (GetLatestWorkflowVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersion, arg.WorkflowID, arg.OrgID)
	var i GetLatestWorkflowVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, org_id, workflow_version_id, status, input_json, output_json,
       parent_run_id, parent_node_id, replay_mode, created_by, created_at
FROM runs
WHERE id = $1 AND org_id = $2
`

type GetRunParams struct {
	ID    string
	OrgID string
}

type GetRunRow struct {
	ID                string
	OrgID             string
	WorkflowVersionID string
	Status            string
	InputJson         json.RawMessage
	OutputJson        json.RawMessage
	ParentRunID       pgtype.Text
	ParentNodeID      pgtype.Text
	ReplayMode        pgtype.Text
	CreatedBy         pgtype.Text
	CreatedAt         *time.Time
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.OrgID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.InputJson,
		&i.OutputJson,
		&i.ParentRunID,
		&i.ParentNodeID,
		&i.ReplayMode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRunExecution = `-- name: GetRunExecution :one
SELECT status, input_json FROM runs WHERE id = $1
`

type GetRunExecutionRow struct {
	Status    string
	InputJson json.RawMessage
}

func (q *Queries) GetRunExecution(ctx context.Context, id string) (GetRunExecutionRow, error) {
	row := q.db.QueryRow(ctx, getRunExecution, id)
	var i GetRunExecutionRow
	err := row.Scan(&i.Status, &i.InputJson)
	return i, err
}

const getRunNode = `-- name: GetRunNode :one
SELECT id, run_id, node_id, status, state_json, attempts, started_at,
       finished_at, error_json
FROM run_nodes
WHERE run_id = $1 AND node_id = $2
`

type GetRunNodeParams struct {
	RunID  string
	NodeID string
}

type GetRunNodeRow struct {
	ID         string
	RunID      string
	NodeID     string
	Status     string
	StateJson  json.RawMessage
	Attempts   pgtype.Int4
	StartedAt  *time.Time
	FinishedAt *time.Time
	ErrorJson  json.RawMessage
}

func (q *Queries) GetRunNode(ctx context.Context, arg GetRunNodeParams) (GetRunNodeRow, error) {
	row := q.db.QueryRow(ctx, getRunNode, arg.RunID, arg.NodeID)
	var i GetRunNodeRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeID,
		&i.Status,
		&i.StateJson,
		&i.Attempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorJson,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, org_id, name, status, paused_reason, created_by, created_at, deleted_at
FROM workflows
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.OrgID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.PausedReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertDeadLetter = `-- name: InsertDeadLetter :exec
INSERT INTO dead_letters (id, org_id, run_id, node_id, attempt, workflow_json, node_json, error_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDeadLetterParams struct {
	ID           string
	OrgID        string
	RunID        string
	NodeID       string
	Attempt      int32
	WorkflowJson json.RawMessage
	NodeJson     json.RawMessage
	ErrorJson    json.RawMessage
}

func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error {
	_, err := q.db.Exec(ctx, insertDeadLetter,
		arg.ID,
		arg.OrgID,
		arg.RunID,
		arg.NodeID,
		arg.Attempt,
		arg.WorkflowJson,
		arg.NodeJson,
		arg.ErrorJson,
	)
	return err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (id, org_id, workflow_version_id, status, input_json, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRunParams struct {
	ID                string
	OrgID             string
	WorkflowVersionID string
	Status            string
	InputJson         json.RawMessage
	CreatedBy         pgtype.Text
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.Exec(ctx, insertRun,
		arg.ID,
		arg.OrgID,
		arg.WorkflowVersionID,
		arg.Status,
		arg.InputJson,
		arg.CreatedBy,
	)
	return err
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (id, run_id, node_id, type, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRunEventParams struct {
	ID      string
	RunID   string
	NodeID  pgtype.Text
	Type    string
	Payload json.RawMessage
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.Exec(ctx, insertRunEvent,
		arg.ID,
		arg.RunID,
		arg.NodeID,
		arg.Type,
		arg.Payload,
	)
	return err
}

const insertRunEventAt = `-- name: InsertRunEventAt :exec
INSERT INTO run_events (id, run_id, node_id, type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRunEventAtParams struct {
	ID        string
	RunID     string
	NodeID    pgtype.Text
	Type      string
	Payload   json.RawMessage
	CreatedAt *time.Time
}

func (q *Queries) InsertRunEventAt(ctx context.Context, arg InsertRunEventAtParams) error {
	_, err := q.db.Exec(ctx, insertRunEventAt,
		arg.ID,
		arg.RunID,
		arg.NodeID,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const insertRunNode = `-- name: InsertRunNode :exec
INSERT INTO run_nodes (id, run_id, node_id, status, attempts, state_json)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRunNodeParams struct {
	ID        string
	RunID     string
	NodeID    string
	Status    string
	Attempts  pgtype.Int4
	StateJson json.RawMessage
}

func (q *Queries) InsertRunNode(ctx context.Context, arg InsertRunNodeParams) error {
	_, err := q.db.Exec(ctx, insertRunNode,
		arg.ID,
		arg.RunID,
		arg.NodeID,
		arg.Status,
		arg.Attempts,
		arg.StateJson,
	)
	return err
}

const insertWorkflow = `-- name: InsertWorkflow :exec

INSERT INTO workflows (id, org_id, name, created_by)
VALUES ($1, $2, $3, $4)
`

type InsertWorkflowParams struct {
	ID        string
	OrgID     string
	Name      string
	CreatedBy pgtype.Text
}

// Typed access to the shared schema. Conventions:
//   - every tenant-scoped read filters by org_id;
//   - keyset pagination orders by (created_at, id) with the id as tiebreak,
//     matching the wire cursors the Node API emits;
//   - status transitions are conditional updates (compare-and-set) so a
//     concurrent worker can never double-apply one;
//   - jsonb parameters and columns are raw bytes end to end.
func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) error {
	_, err := q.db.Exec(ctx, insertWorkflow,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CreatedBy,
	)
	return err
}

const insertWorkflowVersion = `-- name: InsertWorkflowVersion :exec
INSERT INTO workflow_versions (id, org_id, workflow_id, version, dag_json, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertWorkflowVersionParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
}

func (q *Queries) InsertWorkflowVersion(ctx context.Context, arg InsertWorkflowVersionParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowVersion,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Version,
		arg.DagJson,
		arg.CreatedBy,
	)
	return err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id, org_id, run_id, node_id, attempt, error_json, status, created_at
FROM dead_letters
WHERE org_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListDeadLettersParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListDeadLettersRow struct {
	ID        string
	OrgID     string
	RunID     string
	NodeID    string
	Attempt   int32
	ErrorJson json.RawMessage
	Status    string
	CreatedAt *time.Time
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]ListDeadLettersRow, error) {
	rows, err := q.db.Query(ctx, listDeadLetters,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeadLettersRow
	for rows.Next() {
		var i ListDeadLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.NodeID,
			&i.Attempt,
			&i.ErrorJson,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWakeups = `-- name: ListDueWakeups :many
SELECT run_node_id, wake_at, reason
FROM go_pilot_wakeups
WHERE wake_at <= now()
ORDER BY wake_at
LIMIT $1
`

func (q *Queries) ListDueWakeups(ctx context.Context, limit int32) ([]GoPilotWakeup, error) {
	rows, err := q.db.Query(ctx, listDueWakeups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoPilotWakeup
	for rows.Next() {
		var i GoPilotWakeup
		if err := rows.Scan(&i.RunNodeID, &i.WakeAt, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, run_id, node_id, type, payload, created_at
FROM run_events
WHERE run_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRunEventsParams struct {
	RunID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListRunEventsRow struct {
	ID        string
	RunID     string
	NodeID    pgtype.Text
	Type      string
	Payload   json.RawMessage
	CreatedAt *time.Time
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]ListRunEventsRow, error) {
	rows, err := q.db.Query(ctx, listRunEvents,
		arg.RunID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunEventsRow
	for rows.Next() {
		var i ListRunEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunNodeStatuses = `-- name: ListRunNodeStatuses :many
SELECT node_id, status FROM run_nodes WHERE run_id = $1
`

type ListRunNodeStatusesRow struct {
	NodeID string
	Status string
}

func (q *Queries) ListRunNodeStatuses(ctx context.Context, runID string) ([]ListRunNodeStatusesRow, error) {
	rows, err := q.db.Query(ctx, listRunNodeStatuses, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunNodeStatusesRow
	for rows.Next() {
		var i ListRunNodeStatusesRow
		if err := rows.Scan(&i.NodeID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunNodesByRun = `-- name: ListRunNodesByRun :many
SELECT id, run_id, node_id, status, state_json, attempts, started_at,
       finished_at, error_json
FROM run_nodes
WHERE run_id = $1
ORDER BY id
`

type ListRunNodesByRunRow struct {
	ID         string
	RunID      string
	NodeID     string
	Status     string
	StateJson  json.RawMessage
	Attempts   pgtype.Int4
	StartedAt  *time.Time
	FinishedAt *time.Time
	ErrorJson  json.RawMessage
}

func (q *Queries) ListRunNodesByRun(ctx context.Context, runID string) ([]ListRunNodesByRunRow, error) {
	rows, err := q.db.Query(ctx, listRunNodesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunNodesByRunRow
	for rows.Next() {
		var i ListRunNodesByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeID,
			&i.Status,
			&i.StateJson,
			&i.Attempts,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, org_id, workflow_version_id, status, created_by, created_at
FROM runs
WHERE org_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRunsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListRunsRow struct {
	ID                string
	OrgID             string
	WorkflowVersionID string
	Status            string
	CreatedBy         pgtype.Text
	CreatedAt         *time.Time
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowVersionID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, org_id, name, status, created_by, created_at
FROM workflows
WHERE org_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListWorkflowsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListWorkflowsRow struct {
	ID        string
	OrgID     string
	Name      string
	Status    string
	CreatedBy pgtype.Text
	CreatedAt *time.Time
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsRow
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunTerminalFromRunning = `-- name: MarkRunTerminalFromRunning :execrows
UPDATE runs SET status = $1, output_json = $2
WHERE id = $3 AND status = 'running'
`

type MarkRunTerminalFromRunningParams struct {
	Status     string
	OutputJson json.RawMessage
	ID         string
}

func (q *Queries) MarkRunTerminalFromRunning(ctx context.Context, arg MarkRunTerminalFromRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunTerminalFromRunning, arg.Status, arg.OutputJson, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyWake = `-- name: NotifyWake :exec
SELECT pg_notify('janusly_go_wake', $1::text)
`

func (q *Queries) NotifyWake(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, notifyWake, runID)
	return err
}

const queueRunNode = `-- name: QueueRunNode :execrows
UPDATE run_nodes SET status = 'queued', attempts = 1
WHERE run_id = $1 AND node_id = $2 AND status = 'pending'
`

type QueueRunNodeParams struct {
	RunID  string
	NodeID string
}

func (q *Queries) QueueRunNode(ctx context.Context, arg QueueRunNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, queueRunNode, arg.RunID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipRunNode = `-- name: SkipRunNode :execrows
UPDATE run_nodes
SET status = 'skipped', state_json = $1,
    finished_at = $2
WHERE run_id = $3 AND node_id = $4
  AND status = 'pending'
`

type SkipRunNodeParams struct {
	StateJson  json.RawMessage
	FinishedAt *time.Time
	RunID      string
	NodeID     string
}

func (q *Queries) SkipRunNode(ctx context.Context, arg SkipRunNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, skipRunNode,
		arg.StateJson,
		arg.FinishedAt,
		arg.RunID,
		arg.NodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunStatusCAS = `-- name: UpdateRunStatusCAS :execrows
UPDATE runs SET status = $4, output_json = COALESCE($5, output_json)
WHERE id = $1 AND org_id = $2 AND status = $3
`

type UpdateRunStatusCASParams struct {
	ID         string
	OrgID      string
	Status     string
	Status_2   string
	OutputJson json.RawMessage
}

func (q *Queries) UpdateRunStatusCAS(ctx context.Context, arg UpdateRunStatusCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunStatusCAS,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.Status_2,
		arg.OutputJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWakeup = `-- name: UpsertWakeup :exec
INSERT INTO go_pilot_wakeups (run_node_id, wake_at, reason)
VALUES ($1, $2, $3)
ON CONFLICT (run_node_id) DO UPDATE SET wake_at = EXCLUDED.wake_at, reason = EXCLUDED.reason
`

type UpsertWakeupParams struct {
	RunNodeID string
	WakeAt    time.Time
	Reason    string
}

func (q *Queries) UpsertWakeup(ctx context.Context, arg UpsertWakeupParams) error {
	_, err := q.db.Exec(ctx, upsertWakeup, arg.RunNodeID, arg.WakeAt, arg.Reason)
	return err
}
