// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addScimUserGroup = `-- name: AddScimUserGroup :exec
INSERT INTO scim_user_groups (id, org_id, scim_directory_id, provider_user_id, provider_group_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scim_directory_id, provider_user_id, provider_group_id) DO NOTHING
`

type AddScimUserGroupParams struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderUserID  string
	ProviderGroupID string
}

func (q *Queries) AddScimUserGroup(ctx context.Context, arg AddScimUserGroupParams) error {
	_, err := q.db.Exec(ctx, addScimUserGroup,
		arg.ID,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.ProviderUserID,
		arg.ProviderGroupID,
	)
	return err
}

const deleteScimGroupRoleMapping = `-- name: DeleteScimGroupRoleMapping :execrows
DELETE FROM scim_group_role_mappings WHERE id = $1 AND org_id = $2
`

type DeleteScimGroupRoleMappingParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteScimGroupRoleMapping(ctx context.Context, arg DeleteScimGroupRoleMappingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScimGroupRoleMapping, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScimGroupState = `-- name: DeleteScimGroupState :exec
DELETE FROM scim_group_state WHERE id = $1
`

func (q *Queries) DeleteScimGroupState(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteScimGroupState, id)
	return err
}

const deleteScimMembershipByEmail = `-- name: DeleteScimMembershipByEmail :execrows
DELETE FROM org_members
WHERE org_id = $1 AND email = $2 AND invited_by = $3
`

type DeleteScimMembershipByEmailParams struct {
	OrgID     string
	Email     pgtype.Text
	InvitedBy pgtype.Text
}

// Deprovisioning only ever deletes rows SCIM itself created — a
// human-invited row sharing the email must survive a directory delete
// (T-534 property find: the unguarded delete could remove the human).
func (q *Queries) DeleteScimMembershipByEmail(ctx context.Context, arg DeleteScimMembershipByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScimMembershipByEmail, arg.OrgID, arg.Email, arg.InvitedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScimProcessedEvent = `-- name: DeleteScimProcessedEvent :exec
DELETE FROM scim_processed_events WHERE event_id = $1 AND org_id = $2
`

type DeleteScimProcessedEventParams struct {
	EventID string
	OrgID   string
}

func (q *Queries) DeleteScimProcessedEvent(ctx context.Context, arg DeleteScimProcessedEventParams) error {
	_, err := q.db.Exec(ctx, deleteScimProcessedEvent, arg.EventID, arg.OrgID)
	return err
}

const deleteScimUserGroupsForGroup = `-- name: DeleteScimUserGroupsForGroup :exec
DELETE FROM scim_user_groups
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_group_id = $3
`

type DeleteScimUserGroupsForGroupParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
}

func (q *Queries) DeleteScimUserGroupsForGroup(ctx context.Context, arg DeleteScimUserGroupsForGroupParams) error {
	_, err := q.db.Exec(ctx, deleteScimUserGroupsForGroup, arg.OrgID, arg.ScimDirectoryID, arg.ProviderGroupID)
	return err
}

const deleteScimUserGroupsForUser = `-- name: DeleteScimUserGroupsForUser :exec
DELETE FROM scim_user_groups
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_user_id = $3
`

type DeleteScimUserGroupsForUserParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderUserID  string
}

func (q *Queries) DeleteScimUserGroupsForUser(ctx context.Context, arg DeleteScimUserGroupsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteScimUserGroupsForUser, arg.OrgID, arg.ScimDirectoryID, arg.ProviderUserID)
	return err
}

const findScimGroupRoleMappingByGroup = `-- name: FindScimGroupRoleMappingByGroup :one
SELECT id, org_id, scim_directory_id, provider_group_id, role, created_by, updated_by, created_at, updated_at FROM scim_group_role_mappings
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_group_id = $3
`

type FindScimGroupRoleMappingByGroupParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
}

func (q *Queries) FindScimGroupRoleMappingByGroup(ctx context.Context, arg FindScimGroupRoleMappingByGroupParams) (ScimGroupRoleMapping, error) {
	row := q.db.QueryRow(ctx, findScimGroupRoleMappingByGroup, arg.OrgID, arg.ScimDirectoryID, arg.ProviderGroupID)
	var i ScimGroupRoleMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderGroupID,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findScimMemberByEmail = `-- name: FindScimMemberByEmail :one
SELECT id, user_id, role, invited_by FROM org_members
WHERE org_id = $1 AND (email = $2 OR lower(user_id) = $2)
`

type FindScimMemberByEmailParams struct {
	OrgID string
	Email pgtype.Text
}

type FindScimMemberByEmailRow struct {
	ID        string
	UserID    string
	Role      string
	InvitedBy pgtype.Text
}

// SCIM membership writes are keyed on (org_id, lower(email)) — the
// user-stable join key — not (org_id, user_id); see the reference's
// upsertMembershipByEmail. The update preserves invited_by (and user_id,
// which the SSO backfill may have rewritten) unless a new inviter is given.
// The lookup matches the email COLUMN or an email-shaped user_id: the
// legacy pre-invite rows seed userId with the email and leave the email
// column NULL (the auth resolver's backfill acknowledges them) — without
// this arm the collision guard is blind to them and provisioning 500s
// on the (org_id, user_id) unique index forever (T-534 property find).
func (q *Queries) FindScimMemberByEmail(ctx context.Context, arg FindScimMemberByEmailParams) (FindScimMemberByEmailRow, error) {
	row := q.db.QueryRow(ctx, findScimMemberByEmail, arg.OrgID, arg.Email)
	var i FindScimMemberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
	)
	return i, err
}

const getScimDirectoryByID = `-- name: GetScimDirectoryByID :one
SELECT id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at FROM scim_directories WHERE id = $1 AND org_id = $2
`

type GetScimDirectoryByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetScimDirectoryByID(ctx context.Context, arg GetScimDirectoryByIDParams) (ScimDirectory, error) {
	row := q.db.QueryRow(ctx, getScimDirectoryByID, arg.ID, arg.OrgID)
	var i ScimDirectory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderDirectoryID,
		&i.DirectoryType,
		&i.DefaultRole,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimDirectoryByOrgID = `-- name: GetScimDirectoryByOrgID :one

SELECT id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at FROM scim_directories WHERE org_id = $1
`

// SCIM directory sync (WorkOS): directorios, estado, mapeos, dedupe.
func (q *Queries) GetScimDirectoryByOrgID(ctx context.Context, orgID string) (ScimDirectory, error) {
	row := q.db.QueryRow(ctx, getScimDirectoryByOrgID, orgID)
	var i ScimDirectory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderDirectoryID,
		&i.DirectoryType,
		&i.DefaultRole,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimDirectoryByProviderDirectoryID = `-- name: GetScimDirectoryByProviderDirectoryID :one
SELECT id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at FROM scim_directories WHERE provider_directory_id = $1
`

// The webhook's org-binding seam: deliberately un-scoped — the inbound
// event carries no tenant, so the matched row IS the tenant grant.
func (q *Queries) GetScimDirectoryByProviderDirectoryID(ctx context.Context, providerDirectoryID string) (ScimDirectory, error) {
	row := q.db.QueryRow(ctx, getScimDirectoryByProviderDirectoryID, providerDirectoryID)
	var i ScimDirectory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderDirectoryID,
		&i.DirectoryType,
		&i.DefaultRole,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimGroupRoleMappingByID = `-- name: GetScimGroupRoleMappingByID :one
SELECT id, org_id, scim_directory_id, provider_group_id, role, created_by, updated_by, created_at, updated_at FROM scim_group_role_mappings WHERE id = $1 AND org_id = $2
`

type GetScimGroupRoleMappingByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetScimGroupRoleMappingByID(ctx context.Context, arg GetScimGroupRoleMappingByIDParams) (ScimGroupRoleMapping, error) {
	row := q.db.QueryRow(ctx, getScimGroupRoleMappingByID, arg.ID, arg.OrgID)
	var i ScimGroupRoleMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderGroupID,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimGroupState = `-- name: GetScimGroupState :one
SELECT id, org_id, scim_directory_id, provider_group_id, name, last_synced_at FROM scim_group_state WHERE scim_directory_id = $1 AND provider_group_id = $2
`

type GetScimGroupStateParams struct {
	ScimDirectoryID string
	ProviderGroupID string
}

func (q *Queries) GetScimGroupState(ctx context.Context, arg GetScimGroupStateParams) (ScimGroupState, error) {
	row := q.db.QueryRow(ctx, getScimGroupState, arg.ScimDirectoryID, arg.ProviderGroupID)
	var i ScimGroupState
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderGroupID,
		&i.Name,
		&i.LastSyncedAt,
	)
	return i, err
}

const getScimUserState = `-- name: GetScimUserState :one
SELECT id, org_id, scim_directory_id, provider_user_id, email, first_name, last_name, active, last_event_id, last_event_timestamp, created_at, updated_at FROM scim_user_state WHERE scim_directory_id = $1 AND provider_user_id = $2
`

type GetScimUserStateParams struct {
	ScimDirectoryID string
	ProviderUserID  string
}

func (q *Queries) GetScimUserState(ctx context.Context, arg GetScimUserStateParams) (ScimUserState, error) {
	row := q.db.QueryRow(ctx, getScimUserState, arg.ScimDirectoryID, arg.ProviderUserID)
	var i ScimUserState
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Active,
		&i.LastEventID,
		&i.LastEventTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScimDirectory = `-- name: InsertScimDirectory :one
INSERT INTO scim_directories (id, org_id, provider_directory_id, directory_type, default_role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at
`

type InsertScimDirectoryParams struct {
	ID                  string
	OrgID               string
	ProviderDirectoryID string
	DirectoryType       pgtype.Text
	DefaultRole         string
}

func (q *Queries) InsertScimDirectory(ctx context.Context, arg InsertScimDirectoryParams) (ScimDirectory, error) {
	row := q.db.QueryRow(ctx, insertScimDirectory,
		arg.ID,
		arg.OrgID,
		arg.ProviderDirectoryID,
		arg.DirectoryType,
		arg.DefaultRole,
	)
	var i ScimDirectory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderDirectoryID,
		&i.DirectoryType,
		&i.DefaultRole,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScimGroupRoleMapping = `-- name: InsertScimGroupRoleMapping :one
INSERT INTO scim_group_role_mappings (id, org_id, scim_directory_id, provider_group_id, role, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, scim_directory_id, provider_group_id, role, created_by, updated_by, created_at, updated_at
`

type InsertScimGroupRoleMappingParams struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
	Role            string
	CreatedBy       pgtype.Text
}

func (q *Queries) InsertScimGroupRoleMapping(ctx context.Context, arg InsertScimGroupRoleMappingParams) (ScimGroupRoleMapping, error) {
	row := q.db.QueryRow(ctx, insertScimGroupRoleMapping,
		arg.ID,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.ProviderGroupID,
		arg.Role,
		arg.CreatedBy,
	)
	var i ScimGroupRoleMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderGroupID,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScimMembership = `-- name: InsertScimMembership :exec
INSERT INTO org_members (id, org_id, user_id, email, role, invited_by)
VALUES ($1, $2, $3, $3, $4, $5)
`

type InsertScimMembershipParams struct {
	ID        string
	OrgID     string
	Email     string
	Role      string
	InvitedBy pgtype.Text
}

func (q *Queries) InsertScimMembership(ctx context.Context, arg InsertScimMembershipParams) error {
	_, err := q.db.Exec(ctx, insertScimMembership,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const listActiveScimUserState = `-- name: ListActiveScimUserState :many
SELECT provider_user_id, email FROM scim_user_state
WHERE org_id = $1 AND scim_directory_id = $2 AND active = true
ORDER BY email ASC
LIMIT $3
`

type ListActiveScimUserStateParams struct {
	OrgID           string
	ScimDirectoryID string
	Limit           int32
}

type ListActiveScimUserStateRow struct {
	ProviderUserID string
	Email          string
}

func (q *Queries) ListActiveScimUserState(ctx context.Context, arg ListActiveScimUserStateParams) ([]ListActiveScimUserStateRow, error) {
	rows, err := q.db.Query(ctx, listActiveScimUserState, arg.OrgID, arg.ScimDirectoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveScimUserStateRow
	for rows.Next() {
		var i ListActiveScimUserStateRow
		if err := rows.Scan(&i.ProviderUserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScimDirectories = `-- name: ListScimDirectories :many
SELECT id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at FROM scim_directories WHERE org_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListScimDirectories(ctx context.Context, orgID string) ([]ScimDirectory, error) {
	rows, err := q.db.Query(ctx, listScimDirectories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimDirectory
	for rows.Next() {
		var i ScimDirectory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderDirectoryID,
			&i.DirectoryType,
			&i.DefaultRole,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScimGroupRoleMappings = `-- name: ListScimGroupRoleMappings :many
SELECT id, org_id, scim_directory_id, provider_group_id, role, created_by, updated_by, created_at, updated_at FROM scim_group_role_mappings WHERE org_id = $1 AND scim_directory_id = $2
ORDER BY created_at ASC
`

type ListScimGroupRoleMappingsParams struct {
	OrgID           string
	ScimDirectoryID string
}

func (q *Queries) ListScimGroupRoleMappings(ctx context.Context, arg ListScimGroupRoleMappingsParams) ([]ScimGroupRoleMapping, error) {
	rows, err := q.db.Query(ctx, listScimGroupRoleMappings, arg.OrgID, arg.ScimDirectoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroupRoleMapping
	for rows.Next() {
		var i ScimGroupRoleMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScimDirectoryID,
			&i.ProviderGroupID,
			&i.Role,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScimGroupState = `-- name: ListScimGroupState :many
SELECT id, org_id, scim_directory_id, provider_group_id, name, last_synced_at FROM scim_group_state WHERE org_id = $1 AND scim_directory_id = $2
ORDER BY name ASC
LIMIT $3
`

type ListScimGroupStateParams struct {
	OrgID           string
	ScimDirectoryID string
	Limit           int32
}

func (q *Queries) ListScimGroupState(ctx context.Context, arg ListScimGroupStateParams) ([]ScimGroupState, error) {
	rows, err := q.db.Query(ctx, listScimGroupState, arg.OrgID, arg.ScimDirectoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroupState
	for rows.Next() {
		var i ScimGroupState
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScimDirectoryID,
			&i.ProviderGroupID,
			&i.Name,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScimUserGroupIDs = `-- name: ListScimUserGroupIDs :many
SELECT provider_group_id FROM scim_user_groups
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_user_id = $3
`

type ListScimUserGroupIDsParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderUserID  string
}

func (q *Queries) ListScimUserGroupIDs(ctx context.Context, arg ListScimUserGroupIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listScimUserGroupIDs, arg.OrgID, arg.ScimDirectoryID, arg.ProviderUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider_group_id string
		if err := rows.Scan(&provider_group_id); err != nil {
			return nil, err
		}
		items = append(items, provider_group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScimUserIDsForGroup = `-- name: ListScimUserIDsForGroup :many
SELECT provider_user_id FROM scim_user_groups
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_group_id = $3
`

type ListScimUserIDsForGroupParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
}

func (q *Queries) ListScimUserIDsForGroup(ctx context.Context, arg ListScimUserIDsForGroupParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listScimUserIDsForGroup, arg.OrgID, arg.ScimDirectoryID, arg.ProviderGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider_user_id string
		if err := rows.Scan(&provider_user_id); err != nil {
			return nil, err
		}
		items = append(items, provider_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScimUserInactive = `-- name: MarkScimUserInactive :exec
UPDATE scim_user_state SET active = false, last_event_id = $2, last_event_timestamp = $3, updated_at = now()
WHERE id = $1
`

type MarkScimUserInactiveParams struct {
	ID                 string
	LastEventID        pgtype.Text
	LastEventTimestamp *time.Time
}

func (q *Queries) MarkScimUserInactive(ctx context.Context, arg MarkScimUserInactiveParams) error {
	_, err := q.db.Exec(ctx, markScimUserInactive, arg.ID, arg.LastEventID, arg.LastEventTimestamp)
	return err
}

const recordScimDirectorySync = `-- name: RecordScimDirectorySync :exec
UPDATE scim_directories SET last_synced_at = now(), updated_at = now()
WHERE id = $1 AND org_id = $2
`

type RecordScimDirectorySyncParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RecordScimDirectorySync(ctx context.Context, arg RecordScimDirectorySyncParams) error {
	_, err := q.db.Exec(ctx, recordScimDirectorySync, arg.ID, arg.OrgID)
	return err
}

const recordScimProcessedEvent = `-- name: RecordScimProcessedEvent :execrows
INSERT INTO scim_processed_events (event_id, org_id, scim_directory_id, event_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id) DO NOTHING
`

type RecordScimProcessedEventParams struct {
	EventID         string
	OrgID           string
	ScimDirectoryID string
	EventType       string
}

// Replay guard: 1 row inserted = fresh claim; 0 = already processed.
func (q *Queries) RecordScimProcessedEvent(ctx context.Context, arg RecordScimProcessedEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordScimProcessedEvent,
		arg.EventID,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.EventType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeScimUserGroup = `-- name: RemoveScimUserGroup :exec
DELETE FROM scim_user_groups
WHERE org_id = $1 AND scim_directory_id = $2 AND provider_user_id = $3 AND provider_group_id = $4
`

type RemoveScimUserGroupParams struct {
	OrgID           string
	ScimDirectoryID string
	ProviderUserID  string
	ProviderGroupID string
}

func (q *Queries) RemoveScimUserGroup(ctx context.Context, arg RemoveScimUserGroupParams) error {
	_, err := q.db.Exec(ctx, removeScimUserGroup,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.ProviderUserID,
		arg.ProviderGroupID,
	)
	return err
}

const revokeScimDirectory = `-- name: RevokeScimDirectory :execrows
DELETE FROM scim_directories WHERE id = $1 AND org_id = $2
`

type RevokeScimDirectoryParams struct {
	ID    string
	OrgID string
}

// Revoke is a HARD delete (reference revokeScimDirectory): the unique
// (org_id) and (provider_directory_id) indexes must free up so a re-attach
// can succeed; orphaned state/mapping rows are tolerated (no FK) and the
// create-path collision guard absorbs SCIM-owned memberships on re-provision.
func (q *Queries) RevokeScimDirectory(ctx context.Context, arg RevokeScimDirectoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeScimDirectory, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScimDirectoryDefaultRole = `-- name: UpdateScimDirectoryDefaultRole :one
UPDATE scim_directories SET default_role = $3, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, provider_directory_id, directory_type, default_role, status, last_synced_at, created_at, updated_at
`

type UpdateScimDirectoryDefaultRoleParams struct {
	ID          string
	OrgID       string
	DefaultRole string
}

func (q *Queries) UpdateScimDirectoryDefaultRole(ctx context.Context, arg UpdateScimDirectoryDefaultRoleParams) (ScimDirectory, error) {
	row := q.db.QueryRow(ctx, updateScimDirectoryDefaultRole, arg.ID, arg.OrgID, arg.DefaultRole)
	var i ScimDirectory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderDirectoryID,
		&i.DirectoryType,
		&i.DefaultRole,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScimGroupRoleMappingRole = `-- name: UpdateScimGroupRoleMappingRole :one
UPDATE scim_group_role_mappings SET role = $3, updated_by = $4, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, scim_directory_id, provider_group_id, role, created_by, updated_by, created_at, updated_at
`

type UpdateScimGroupRoleMappingRoleParams struct {
	ID        string
	OrgID     string
	Role      string
	UpdatedBy pgtype.Text
}

func (q *Queries) UpdateScimGroupRoleMappingRole(ctx context.Context, arg UpdateScimGroupRoleMappingRoleParams) (ScimGroupRoleMapping, error) {
	row := q.db.QueryRow(ctx, updateScimGroupRoleMappingRole,
		arg.ID,
		arg.OrgID,
		arg.Role,
		arg.UpdatedBy,
	)
	var i ScimGroupRoleMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ScimDirectoryID,
		&i.ProviderGroupID,
		&i.Role,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScimMembershipByEmail = `-- name: UpdateScimMembershipByEmail :execrows
UPDATE org_members SET email = $1, role = $2,
  invited_by = coalesce($3, invited_by)
WHERE id = $4 AND org_id = $5
`

type UpdateScimMembershipByEmailParams struct {
	Email     pgtype.Text
	Role      string
	InvitedBy pgtype.Text
	ID        string
	OrgID     string
}

func (q *Queries) UpdateScimMembershipByEmail(ctx context.Context, arg UpdateScimMembershipByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScimMembershipByEmail,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertScimGroupState = `-- name: UpsertScimGroupState :exec
INSERT INTO scim_group_state (id, org_id, scim_directory_id, provider_group_id, name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scim_directory_id, provider_group_id) DO UPDATE SET
  name = excluded.name, last_synced_at = now()
`

type UpsertScimGroupStateParams struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
	Name            string
}

func (q *Queries) UpsertScimGroupState(ctx context.Context, arg UpsertScimGroupStateParams) error {
	_, err := q.db.Exec(ctx, upsertScimGroupState,
		arg.ID,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.ProviderGroupID,
		arg.Name,
	)
	return err
}

const upsertScimUserState = `-- name: UpsertScimUserState :exec
INSERT INTO scim_user_state (id, org_id, scim_directory_id, provider_user_id, email,
  first_name, last_name, active, last_event_id, last_event_timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, true, $8, $9)
ON CONFLICT (scim_directory_id, provider_user_id) DO UPDATE SET
  email = excluded.email, first_name = excluded.first_name, last_name = excluded.last_name,
  active = true, last_event_id = excluded.last_event_id,
  last_event_timestamp = excluded.last_event_timestamp, updated_at = now()
`

type UpsertScimUserStateParams struct {
	ID                 string
	OrgID              string
	ScimDirectoryID    string
	ProviderUserID     string
	Email              string
	FirstName          pgtype.Text
	LastName           pgtype.Text
	LastEventID        pgtype.Text
	LastEventTimestamp *time.Time
}

func (q *Queries) UpsertScimUserState(ctx context.Context, arg UpsertScimUserStateParams) error {
	_, err := q.db.Exec(ctx, upsertScimUserState,
		arg.ID,
		arg.OrgID,
		arg.ScimDirectoryID,
		arg.ProviderUserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.LastEventID,
		arg.LastEventTimestamp,
	)
	return err
}
