// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoRollbackRollout = `-- name: AutoRollbackRollout :one
UPDATE workflow_rollouts
SET status = 'rolled_back', rolled_back_reason = $2, ended_at = now(), updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type AutoRollbackRolloutParams struct {
	ID     string
	Reason pgtype.Text
}

func (q *Queries) AutoRollbackRollout(ctx context.Context, arg AutoRollbackRolloutParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, autoRollbackRollout, arg.ID, arg.Reason)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const cancelActiveWorkflowRollout = `-- name: CancelActiveWorkflowRollout :execrows
UPDATE workflow_rollouts
SET status = 'cancelled', rolled_back_reason = $3,
    ended_at = now(), updated_at = now()
WHERE org_id = $1 AND workflow_id = $2 AND status = 'active'
`

type CancelActiveWorkflowRolloutParams struct {
	OrgID      string
	WorkflowID string
	Reason     pgtype.Text
}

func (q *Queries) CancelActiveWorkflowRollout(ctx context.Context, arg CancelActiveWorkflowRolloutParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveWorkflowRollout, arg.OrgID, arg.WorkflowID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentWorkflowRunStatuses = `-- name: CountRecentWorkflowRunStatuses :many
SELECT r.status FROM runs r
LEFT JOIN workflow_versions v ON v.id = r.workflow_version_id AND v.org_id = r.org_id
WHERE r.org_id = $1
  AND COALESCE(v.workflow_id, r.workflow_version_id) = $2
  AND r.replay_mode IS NULL
  AND r.status IN ('succeeded', 'failed')
ORDER BY r.created_at DESC
LIMIT $3
`

type CountRecentWorkflowRunStatusesParams struct {
	OrgID      string
	WorkflowID string
	PageLimit  int32
}

func (q *Queries) CountRecentWorkflowRunStatuses(ctx context.Context, arg CountRecentWorkflowRunStatusesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, countRecentWorkflowRunStatuses, arg.OrgID, arg.WorkflowID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkflowVersions = `-- name: CountWorkflowVersions :one
SELECT COALESCE(MAX(version), 0)::int FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
`

type CountWorkflowVersionsParams struct {
	WorkflowID string
	OrgID      string
}

func (q *Queries) CountWorkflowVersions(ctx context.Context, arg CountWorkflowVersionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkflowVersions, arg.WorkflowID, arg.OrgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkflowFolderBulk = `-- name: DeleteWorkflowFolderBulk :execrows
UPDATE workflow_metadata SET folder = NULL, updated_at = now()
WHERE org_id = $1 AND folder = $2
`

type DeleteWorkflowFolderBulkParams struct {
	OrgID  string
	Folder pgtype.Text
}

func (q *Queries) DeleteWorkflowFolderBulk(ctx context.Context, arg DeleteWorkflowFolderBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowFolderBulk, arg.OrgID, arg.Folder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowTagBulk = `-- name: DeleteWorkflowTagBulk :execrows
UPDATE workflow_metadata
SET tags = tags - $2::text, updated_at = now()
WHERE org_id = $1 AND tags ? $2::text
`

type DeleteWorkflowTagBulkParams struct {
	OrgID string
	Tag   string
}

func (q *Queries) DeleteWorkflowTagBulk(ctx context.Context, arg DeleteWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowTagBulk, arg.OrgID, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveWorkflowRollout = `-- name: FindActiveWorkflowRollout :one
SELECT id FROM workflow_rollouts WHERE org_id = $1 AND workflow_id = $2 AND status = 'active' LIMIT 1
`

type FindActiveWorkflowRolloutParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) FindActiveWorkflowRollout(ctx context.Context, arg FindActiveWorkflowRolloutParams) (string, error) {
	row := q.db.QueryRow(ctx, findActiveWorkflowRollout, arg.OrgID, arg.WorkflowID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findWorkflowRecoveryQualification = `-- name: FindWorkflowRecoveryQualification :one
SELECT id, org_id, workflow_id, baseline_version_id, candidate_version_id, dataset_version, dataset_digest, mode, status, summary_json, created_by, created_at FROM workflow_recovery_qualifications
WHERE org_id = $1 AND workflow_id = $2 AND baseline_version_id = $3
  AND candidate_version_id = $4 AND dataset_version = $5
ORDER BY created_at DESC, id DESC LIMIT 1
`

type FindWorkflowRecoveryQualificationParams struct {
	OrgID              string
	WorkflowID         string
	BaselineVersionID  string
	CandidateVersionID string
	DatasetVersion     string
}

func (q *Queries) FindWorkflowRecoveryQualification(ctx context.Context, arg FindWorkflowRecoveryQualificationParams) (WorkflowRecoveryQualification, error) {
	row := q.db.QueryRow(ctx, findWorkflowRecoveryQualification,
		arg.OrgID,
		arg.WorkflowID,
		arg.BaselineVersionID,
		arg.CandidateVersionID,
		arg.DatasetVersion,
	)
	var i WorkflowRecoveryQualification
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CandidateVersionID,
		&i.DatasetVersion,
		&i.DatasetDigest,
		&i.Mode,
		&i.Status,
		&i.SummaryJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const finishWorkflowRolloutCAS = `-- name: FinishWorkflowRolloutCAS :one
UPDATE workflow_rollouts
SET status = $4,
    rolled_back_reason = CASE WHEN $4 = 'rolled_back' THEN $5 ELSE NULL END,
    ended_at = now(), updated_at = now()
WHERE id = $1 AND org_id = $2 AND workflow_id = $3 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type FinishWorkflowRolloutCASParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	NewStatus  string
	Reason     pgtype.Text
}

func (q *Queries) FinishWorkflowRolloutCAS(ctx context.Context, arg FinishWorkflowRolloutCASParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, finishWorkflowRolloutCAS,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.NewStatus,
		arg.Reason,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getActiveRolloutForOutcome = `-- name: GetActiveRolloutForOutcome :one
SELECT id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at FROM workflow_rollouts WHERE id = $1 AND org_id = $2 AND status = 'active'
`

type GetActiveRolloutForOutcomeParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetActiveRolloutForOutcome(ctx context.Context, arg GetActiveRolloutForOutcomeParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getActiveRolloutForOutcome, arg.ID, arg.OrgID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getLatestWorkflowRolloutRow = `-- name: GetLatestWorkflowRolloutRow :one
SELECT wr.id, wr.org_id, wr.workflow_id, wr.baseline_version_id, wr.canary_version_id, wr.traffic_percent, wr.minimum_sample_size, wr.minimum_success_rate_percent, wr.status, wr.baseline_succeeded, wr.baseline_failed, wr.canary_succeeded, wr.canary_failed, wr.rolled_back_reason, wr.created_by, wr.created_at, wr.updated_at, wr.ended_at, wr.last_outcome_at FROM workflow_rollouts wr
JOIN workflows w ON w.id = wr.workflow_id AND w.org_id = wr.org_id
WHERE wr.org_id = $1 AND wr.workflow_id = $2 AND w.deleted_at IS NULL
ORDER BY CASE WHEN wr.status = 'active' THEN 0 ELSE 1 END, wr.created_at DESC, wr.id DESC
LIMIT 1
`

type GetLatestWorkflowRolloutRowParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetLatestWorkflowRolloutRow(ctx context.Context, arg GetLatestWorkflowRolloutRowParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowRolloutRow, arg.OrgID, arg.WorkflowID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getLatestWorkflowSlo = `-- name: GetLatestWorkflowSlo :one
SELECT slo_json FROM workflow_versions
WHERE org_id = $1 AND workflow_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowSloParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetLatestWorkflowSlo(ctx context.Context, arg GetLatestWorkflowSloParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowSlo, arg.OrgID, arg.WorkflowID)
	var slo_json json.RawMessage
	err := row.Scan(&slo_json)
	return slo_json, err
}

const getLatestWorkflowVersion = `-- name: GetLatestWorkflowVersion :one
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowVersionParams struct {
	WorkflowID string
	OrgID      string
}

type GetLatestWorkflowVersionRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) GetLatestWorkflowVersion(ctx context.Context, arg GetLatestWorkflowVersionParams) (GetLatestWorkflowVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersion, arg.WorkflowID, arg.OrgID)
	var i GetLatestWorkflowVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRunForRolloutOutcome = `-- name: GetRunForRolloutOutcome :one
SELECT org_id, status, replay_mode, workflow_rollout_id, workflow_rollout_variant, workflow_version_id
FROM runs WHERE id = $1
`

type GetRunForRolloutOutcomeRow struct {
	OrgID                  string
	Status                 string
	ReplayMode             pgtype.Text
	WorkflowRolloutID      pgtype.Text
	WorkflowRolloutVariant pgtype.Text
	WorkflowVersionID      string
}

func (q *Queries) GetRunForRolloutOutcome(ctx context.Context, id string) (GetRunForRolloutOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getRunForRolloutOutcome, id)
	var i GetRunForRolloutOutcomeRow
	err := row.Scan(
		&i.OrgID,
		&i.Status,
		&i.ReplayMode,
		&i.WorkflowRolloutID,
		&i.WorkflowRolloutVariant,
		&i.WorkflowVersionID,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, org_id, name, status, paused_reason, created_by, created_at, deleted_at
FROM workflows
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.OrgID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.PausedReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowAiGuidance = `-- name: GetWorkflowAiGuidance :one
SELECT ai_guidance_markdown FROM workflow_metadata
WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowAiGuidanceParams struct {
	OrgID      string
	WorkflowID string
}

// Workflow-scope operator guidance for AI prompt composition.
func (q *Queries) GetWorkflowAiGuidance(ctx context.Context, arg GetWorkflowAiGuidanceParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWorkflowAiGuidance, arg.OrgID, arg.WorkflowID)
	var ai_guidance_markdown pgtype.Text
	err := row.Scan(&ai_guidance_markdown)
	return ai_guidance_markdown, err
}

const getWorkflowBreakerStatus = `-- name: GetWorkflowBreakerStatus :one
SELECT status FROM workflows
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetWorkflowBreakerStatusParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetWorkflowBreakerStatus(ctx context.Context, arg GetWorkflowBreakerStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkflowBreakerStatus, arg.OrgID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getWorkflowIngestState = `-- name: GetWorkflowIngestState :one
SELECT org_id, status, deleted_at FROM workflows WHERE id = $1
`

type GetWorkflowIngestStateRow struct {
	OrgID     string
	Status    string
	DeletedAt *time.Time
}

func (q *Queries) GetWorkflowIngestState(ctx context.Context, id string) (GetWorkflowIngestStateRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowIngestState, id)
	var i GetWorkflowIngestStateRow
	err := row.Scan(&i.OrgID, &i.Status, &i.DeletedAt)
	return i, err
}

const getWorkflowMetadata = `-- name: GetWorkflowMetadata :one
SELECT id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown FROM workflow_metadata WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowMetadataParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowMetadata(ctx context.Context, arg GetWorkflowMetadataParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, getWorkflowMetadata, arg.OrgID, arg.WorkflowID)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const getWorkflowOwnerState = `-- name: GetWorkflowOwnerState :one
SELECT org_id, deleted_at FROM workflows WHERE id = $1
`

type GetWorkflowOwnerStateRow struct {
	OrgID     string
	DeletedAt *time.Time
}

func (q *Queries) GetWorkflowOwnerState(ctx context.Context, id string) (GetWorkflowOwnerStateRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowOwnerState, id)
	var i GetWorkflowOwnerStateRow
	err := row.Scan(&i.OrgID, &i.DeletedAt)
	return i, err
}

const getWorkflowRolloutRow = `-- name: GetWorkflowRolloutRow :one
SELECT id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at FROM workflow_rollouts WHERE id = $1 AND org_id = $2 AND workflow_id = $3
`

type GetWorkflowRolloutRowParams struct {
	ID         string
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowRolloutRow(ctx context.Context, arg GetWorkflowRolloutRowParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getWorkflowRolloutRow, arg.ID, arg.OrgID, arg.WorkflowID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getWorkflowSeverityDefault = `-- name: GetWorkflowSeverityDefault :one
SELECT severity_default FROM workflow_metadata WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowSeverityDefaultParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowSeverityDefault(ctx context.Context, arg GetWorkflowSeverityDefaultParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWorkflowSeverityDefault, arg.OrgID, arg.WorkflowID)
	var severity_default pgtype.Text
	err := row.Scan(&severity_default)
	return severity_default, err
}

const getWorkflowVersionAnyWorkflow = `-- name: GetWorkflowVersionAnyWorkflow :one
SELECT id, org_id, workflow_id, version, dag_json FROM workflow_versions
WHERE id = $1 AND org_id = $2
`

type GetWorkflowVersionAnyWorkflowParams struct {
	ID    string
	OrgID string
}

type GetWorkflowVersionAnyWorkflowRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
}

func (q *Queries) GetWorkflowVersionAnyWorkflow(ctx context.Context, arg GetWorkflowVersionAnyWorkflowParams) (GetWorkflowVersionAnyWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionAnyWorkflow, arg.ID, arg.OrgID)
	var i GetWorkflowVersionAnyWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
	)
	return i, err
}

const getWorkflowVersionByID = `-- name: GetWorkflowVersionByID :one
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE id = $1 AND org_id = $2 AND workflow_id = $3
`

type GetWorkflowVersionByIDParams struct {
	ID         string
	OrgID      string
	WorkflowID string
}

type GetWorkflowVersionByIDRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) GetWorkflowVersionByID(ctx context.Context, arg GetWorkflowVersionByIDParams) (GetWorkflowVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByID, arg.ID, arg.OrgID, arg.WorkflowID)
	var i GetWorkflowVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowVersionByNumber = `-- name: GetWorkflowVersionByNumber :one
SELECT wv.id, wv.dag_json, wv.version
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.workflow_id = $1 AND wv.org_id = $2 AND wv.version = $3
  AND w.deleted_at IS NULL
`

type GetWorkflowVersionByNumberParams struct {
	WorkflowID string
	OrgID      string
	Version    int32
}

type GetWorkflowVersionByNumberRow struct {
	ID      string
	DagJson json.RawMessage
	Version int32
}

func (q *Queries) GetWorkflowVersionByNumber(ctx context.Context, arg GetWorkflowVersionByNumberParams) (GetWorkflowVersionByNumberRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByNumber, arg.WorkflowID, arg.OrgID, arg.Version)
	var i GetWorkflowVersionByNumberRow
	err := row.Scan(&i.ID, &i.DagJson, &i.Version)
	return i, err
}

const incrementRolloutCounters = `-- name: IncrementRolloutCounters :one
UPDATE workflow_rollouts SET
  baseline_succeeded = baseline_succeeded + $2,
  baseline_failed = baseline_failed + $3,
  canary_succeeded = canary_succeeded + $4,
  canary_failed = canary_failed + $5,
  last_outcome_at = now(), updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type IncrementRolloutCountersParams struct {
	ID                   string
	BaselineSucceededInc int32
	BaselineFailedInc    int32
	CanarySucceededInc   int32
	CanaryFailedInc      int32
}

func (q *Queries) IncrementRolloutCounters(ctx context.Context, arg IncrementRolloutCountersParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, incrementRolloutCounters,
		arg.ID,
		arg.BaselineSucceededInc,
		arg.BaselineFailedInc,
		arg.CanarySucceededInc,
		arg.CanaryFailedInc,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const insertWorkflow = `-- name: InsertWorkflow :exec

INSERT INTO workflows (id, org_id, name, created_by)
VALUES ($1, $2, $3, $4)
`

type InsertWorkflowParams struct {
	ID        string
	OrgID     string
	Name      string
	CreatedBy pgtype.Text
}

// Workflows, versions, trash, rollouts, tags/folders/metadata, health.
func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) error {
	_, err := q.db.Exec(ctx, insertWorkflow,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CreatedBy,
	)
	return err
}

const insertWorkflowRollout = `-- name: InsertWorkflowRollout :one
INSERT INTO workflow_rollouts (id, org_id, workflow_id, baseline_version_id, canary_version_id,
  traffic_percent, minimum_sample_size, minimum_success_rate_percent, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type InsertWorkflowRolloutParams struct {
	ID                        string
	OrgID                     string
	WorkflowID                string
	BaselineVersionID         string
	CanaryVersionID           string
	TrafficPercent            int32
	MinimumSampleSize         int32
	MinimumSuccessRatePercent int32
	CreatedBy                 string
}

func (q *Queries) InsertWorkflowRollout(ctx context.Context, arg InsertWorkflowRolloutParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, insertWorkflowRollout,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.BaselineVersionID,
		arg.CanaryVersionID,
		arg.TrafficPercent,
		arg.MinimumSampleSize,
		arg.MinimumSuccessRatePercent,
		arg.CreatedBy,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const insertWorkflowRolloutOutcome = `-- name: InsertWorkflowRolloutOutcome :execrows
INSERT INTO workflow_rollout_outcomes (run_id, org_id, rollout_id, workflow_id, variant, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id) DO NOTHING
`

type InsertWorkflowRolloutOutcomeParams struct {
	RunID      string
	OrgID      string
	RolloutID  string
	WorkflowID string
	Variant    string
	Status     string
}

func (q *Queries) InsertWorkflowRolloutOutcome(ctx context.Context, arg InsertWorkflowRolloutOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWorkflowRolloutOutcome,
		arg.RunID,
		arg.OrgID,
		arg.RolloutID,
		arg.WorkflowID,
		arg.Variant,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWorkflowVersion = `-- name: InsertWorkflowVersion :exec
INSERT INTO workflow_versions (id, org_id, workflow_id, version, dag_json, created_by,
                               upstream_health_sources, slo_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWorkflowVersionParams struct {
	ID                    string
	OrgID                 string
	WorkflowID            string
	Version               int32
	DagJson               json.RawMessage
	CreatedBy             pgtype.Text
	UpstreamHealthSources json.RawMessage
	SloJson               json.RawMessage
}

func (q *Queries) InsertWorkflowVersion(ctx context.Context, arg InsertWorkflowVersionParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowVersion,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Version,
		arg.DagJson,
		arg.CreatedBy,
		arg.UpstreamHealthSources,
		arg.SloJson,
	)
	return err
}

const listDeletedWorkflowRows = `-- name: ListDeletedWorkflowRows :many
SELECT w.id, w.org_id, w.name, w.created_by, w.created_at, w.status,
       w.paused_reason, w.deleted_at,
       (SELECT count(*) FROM runs r
        JOIN workflow_versions wv ON wv.id = r.workflow_version_id
        WHERE r.org_id = w.org_id AND wv.workflow_id = w.id)::int AS run_count,
       COALESCE(last_run.status, '') AS last_run_status
FROM workflows w
LEFT JOIN LATERAL (
  SELECT r.status FROM runs r
  JOIN workflow_versions wv ON wv.id = r.workflow_version_id
  WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
  ORDER BY r.created_at DESC, r.id DESC LIMIT 1
) last_run ON true
WHERE w.org_id = $1 AND w.deleted_at IS NOT NULL
  AND (w.deleted_at, w.id) < ($2::timestamptz, $3::text)
ORDER BY w.deleted_at DESC, w.id DESC
LIMIT $4
`

type ListDeletedWorkflowRowsParams struct {
	OrgID           string
	BeforeDeletedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListDeletedWorkflowRowsRow struct {
	ID            string
	OrgID         string
	Name          string
	CreatedBy     pgtype.Text
	CreatedAt     *time.Time
	Status        string
	PausedReason  pgtype.Text
	DeletedAt     *time.Time
	RunCount      int32
	LastRunStatus string
}

// The trash list: the same list-row shape with deletedAt populated,
// ordered by (deleted_at, id) DESC with its own keyset.
func (q *Queries) ListDeletedWorkflowRows(ctx context.Context, arg ListDeletedWorkflowRowsParams) ([]ListDeletedWorkflowRowsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedWorkflowRows,
		arg.OrgID,
		arg.BeforeDeletedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedWorkflowRowsRow
	for rows.Next() {
		var i ListDeletedWorkflowRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
			&i.PausedReason,
			&i.DeletedAt,
			&i.RunCount,
			&i.LastRunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkflowFolders = `-- name: ListDistinctWorkflowFolders :many
SELECT DISTINCT m.folder::text AS folder
FROM workflow_metadata m
JOIN workflows w ON w.id = m.workflow_id AND w.org_id = m.org_id
WHERE m.org_id = $1 AND m.folder IS NOT NULL AND w.deleted_at IS NULL
ORDER BY folder ASC
LIMIT 200
`

func (q *Queries) ListDistinctWorkflowFolders(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkflowFolders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var folder string
		if err := rows.Scan(&folder); err != nil {
			return nil, err
		}
		items = append(items, folder)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkflowTags = `-- name: ListDistinctWorkflowTags :many
SELECT DISTINCT jsonb_array_elements_text(m.tags)::text AS tag
FROM workflow_metadata m
JOIN workflows w ON w.id = m.workflow_id AND w.org_id = m.org_id
WHERE m.org_id = $1 AND w.deleted_at IS NULL
ORDER BY tag ASC
LIMIT 200
`

func (q *Queries) ListDistinctWorkflowTags(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkflowTags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalWorkflows = `-- name: ListExternalWorkflows :many
SELECT id, org_id, connection_id, external_workflow_id, name, version, snapshot_json, evidence_json, last_sequence, last_event_id, last_observed_at, created_at, updated_at FROM external_workflows
WHERE org_id = $1
ORDER BY last_observed_at DESC NULLS LAST, external_workflow_id ASC
LIMIT 100
`

func (q *Queries) ListExternalWorkflows(ctx context.Context, orgID string) ([]ExternalWorkflow, error) {
	rows, err := q.db.Query(ctx, listExternalWorkflows, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalWorkflow
	for rows.Next() {
		var i ExternalWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.ExternalWorkflowID,
			&i.Name,
			&i.Version,
			&i.SnapshotJson,
			&i.EvidenceJson,
			&i.LastSequence,
			&i.LastEventID,
			&i.LastObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWorkflowVersionDags = `-- name: ListLatestWorkflowVersionDags :many
SELECT DISTINCT ON (wv.workflow_id) wv.workflow_id, wv.dag_json
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.org_id = $1 AND w.deleted_at IS NULL
ORDER BY wv.workflow_id, wv.version DESC
LIMIT 1000
`

type ListLatestWorkflowVersionDagsRow struct {
	WorkflowID string
	DagJson    json.RawMessage
}

func (q *Queries) ListLatestWorkflowVersionDags(ctx context.Context, orgID string) ([]ListLatestWorkflowVersionDagsRow, error) {
	rows, err := q.db.Query(ctx, listLatestWorkflowVersionDags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestWorkflowVersionDagsRow
	for rows.Next() {
		var i ListLatestWorkflowVersionDagsRow
		if err := rows.Scan(&i.WorkflowID, &i.DagJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWorkflowVersionUpstreamTags = `-- name: ListLatestWorkflowVersionUpstreamTags :many
SELECT DISTINCT ON (wv.workflow_id) wv.workflow_id, wv.upstream_health_sources
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.org_id = $1 AND w.deleted_at IS NULL
ORDER BY wv.workflow_id, wv.version DESC
LIMIT 1000
`

type ListLatestWorkflowVersionUpstreamTagsRow struct {
	WorkflowID            string
	UpstreamHealthSources json.RawMessage
}

func (q *Queries) ListLatestWorkflowVersionUpstreamTags(ctx context.Context, orgID string) ([]ListLatestWorkflowVersionUpstreamTagsRow, error) {
	rows, err := q.db.Query(ctx, listLatestWorkflowVersionUpstreamTags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestWorkflowVersionUpstreamTagsRow
	for rows.Next() {
		var i ListLatestWorkflowVersionUpstreamTagsRow
		if err := rows.Scan(&i.WorkflowID, &i.UpstreamHealthSources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsWithSoftDeletedWorkflows = `-- name: ListOrgsWithSoftDeletedWorkflows :many
SELECT DISTINCT org_id FROM workflows WHERE deleted_at IS NOT NULL
`

// Per-org retention: the sweep resolves each org's catalog window and
// purges with an org-scoped cutoff.
func (q *Queries) ListOrgsWithSoftDeletedWorkflows(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listOrgsWithSoftDeletedWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var org_id string
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedActiveWorkflowIDs = `-- name: ListOwnedActiveWorkflowIDs :many
SELECT id FROM workflows
WHERE org_id = $1 AND id = ANY($2::text[]) AND deleted_at IS NULL
`

type ListOwnedActiveWorkflowIDsParams struct {
	OrgID string
	Ids   []string
}

func (q *Queries) ListOwnedActiveWorkflowIDs(ctx context.Context, arg ListOwnedActiveWorkflowIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listOwnedActiveWorkflowIDs, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeadLetterErrorsForWorkflow = `-- name: ListRecentDeadLetterErrorsForWorkflow :many
SELECT d.error_json
FROM dead_letters d
JOIN runs r ON r.id = d.run_id
WHERE r.org_id = $1
  AND d.created_at >= $2
  AND (r.workflow_version_id = $3
       OR r.workflow_version_id IN (SELECT v3.id FROM workflow_versions v3
            WHERE v3.workflow_id = $3 AND v3.org_id = $1))
  AND ($4::int IS NULL OR coalesce(
        (SELECT wv.version FROM workflow_versions wv
         WHERE wv.id = r.workflow_version_id AND wv.org_id = $1),
        (SELECT count(*) FROM workflow_versions v2
         WHERE v2.workflow_id = $3 AND v2.org_id = $1
           AND v2.created_at <= r.created_at))::int >= $4::int)
ORDER BY d.created_at DESC
LIMIT 100
`

type ListRecentDeadLetterErrorsForWorkflowParams struct {
	OrgID       string
	CreatedAt   *time.Time
	WorkflowID  string
	FromVersion pgtype.Int4
}

func (q *Queries) ListRecentDeadLetterErrorsForWorkflow(ctx context.Context, arg ListRecentDeadLetterErrorsForWorkflowParams) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, listRecentDeadLetterErrorsForWorkflow,
		arg.OrgID,
		arg.CreatedAt,
		arg.WorkflowID,
		arg.FromVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var error_json json.RawMessage
		if err := rows.Scan(&error_json); err != nil {
			return nil, err
		}
		items = append(items, error_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleEntriesForWorkflow = `-- name: ListScheduleEntriesForWorkflow :many
SELECT id, org_id, workflow_id, workflow_version_id, node_id, cron_expression, enabled, last_run_at, last_run_id, created_by, created_at, updated_at, next_fire_at FROM schedule_entries WHERE org_id = $1 AND workflow_id = $2 ORDER BY node_id
`

type ListScheduleEntriesForWorkflowParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) ListScheduleEntriesForWorkflow(ctx context.Context, arg ListScheduleEntriesForWorkflowParams) ([]ScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listScheduleEntriesForWorkflow, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleEntry
	for rows.Next() {
		var i ScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.NodeID,
			&i.CronExpression,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastRunID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextFireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnrecordedRolloutOutcomes = `-- name: ListUnrecordedRolloutOutcomes :many
SELECT r.id AS run_id, r.status FROM runs r
JOIN workflow_rollouts wr ON wr.id = r.workflow_rollout_id AND wr.org_id = r.org_id AND wr.status = 'active'
LEFT JOIN workflow_rollout_outcomes o ON o.run_id = r.id
WHERE r.workflow_rollout_id IS NOT NULL AND r.replay_mode IS NULL
  AND r.status IN ('succeeded','failed','cancelled') AND o.run_id IS NULL
ORDER BY r.created_at ASC, r.id ASC
LIMIT $1
`

type ListUnrecordedRolloutOutcomesRow struct {
	RunID  string
	Status string
}

func (q *Queries) ListUnrecordedRolloutOutcomes(ctx context.Context, pageLimit int32) ([]ListUnrecordedRolloutOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listUnrecordedRolloutOutcomes, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnrecordedRolloutOutcomesRow
	for rows.Next() {
		var i ListUnrecordedRolloutOutcomesRow
		if err := rows.Scan(&i.RunID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRows = `-- name: ListWorkflowRows :many
SELECT w.id, w.org_id, w.name, w.created_by, w.created_at, w.status,
       w.paused_reason, w.deleted_at,
       (SELECT count(*) FROM runs r
        JOIN workflow_versions wv ON wv.id = r.workflow_version_id
        WHERE r.org_id = w.org_id AND wv.workflow_id = w.id)::int AS run_count,
       COALESCE(last_run.status, '') AS last_run_status
FROM workflows w
LEFT JOIN LATERAL (
  SELECT r.status FROM runs r
  JOIN workflow_versions wv ON wv.id = r.workflow_version_id
  WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
  ORDER BY r.created_at DESC, r.id DESC LIMIT 1
) last_run ON true
WHERE w.org_id = $1 AND w.deleted_at IS NULL
  AND (w.created_at, w.id) < ($2::timestamptz, $3::text)
  AND ($4::text IS NULL
       OR w.name ILIKE '%' || $4 || '%'
       OR w.id ILIKE '%' || $4 || '%')
ORDER BY w.created_at DESC, w.id DESC
LIMIT $5
`

type ListWorkflowRowsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	Search          pgtype.Text
	PageLimit       int32
}

type ListWorkflowRowsRow struct {
	ID            string
	OrgID         string
	Name          string
	CreatedBy     pgtype.Text
	CreatedAt     *time.Time
	Status        string
	PausedReason  pgtype.Text
	DeletedAt     *time.Time
	RunCount      int32
	LastRunStatus string
}

// Workflow list rows with the read-surface aggregates: run count and last
// run status match runs either through saved versions or the ad-hoc
// version-id fallback, mirroring the runs-list filter.
func (q *Queries) ListWorkflowRows(ctx context.Context, arg ListWorkflowRowsParams) ([]ListWorkflowRowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRows,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.Search,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRowsRow
	for rows.Next() {
		var i ListWorkflowRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
			&i.PausedReason,
			&i.DeletedAt,
			&i.RunCount,
			&i.LastRunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersions = `-- name: ListWorkflowVersions :many
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
ORDER BY version DESC
`

type ListWorkflowVersionsParams struct {
	WorkflowID string
	OrgID      string
}

type ListWorkflowVersionsRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) ListWorkflowVersions(ctx context.Context, arg ListWorkflowVersionsParams) ([]ListWorkflowVersionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersions, arg.WorkflowID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVersionsRow
	for rows.Next() {
		var i ListWorkflowVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.Version,
			&i.DagJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersionsForRollout = `-- name: ListWorkflowVersionsForRollout :many
SELECT id, version, dag_json FROM workflow_versions
WHERE org_id = $1 AND workflow_id = $2 ORDER BY version DESC LIMIT 200
`

type ListWorkflowVersionsForRolloutParams struct {
	OrgID      string
	WorkflowID string
}

type ListWorkflowVersionsForRolloutRow struct {
	ID      string
	Version int32
	DagJson json.RawMessage
}

func (q *Queries) ListWorkflowVersionsForRollout(ctx context.Context, arg ListWorkflowVersionsForRolloutParams) ([]ListWorkflowVersionsForRolloutRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionsForRollout, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVersionsForRolloutRow
	for rows.Next() {
		var i ListWorkflowVersionsForRolloutRow
		if err := rows.Scan(&i.ID, &i.Version, &i.DagJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, org_id, name, status, created_by, created_at
FROM workflows
WHERE org_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListWorkflowsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListWorkflowsRow struct {
	ID        string
	OrgID     string
	Name      string
	Status    string
	CreatedBy pgtype.Text
	CreatedAt *time.Time
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsRow
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkflowForRollout = `-- name: LockWorkflowForRollout :one
SELECT id FROM workflows WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL FOR UPDATE
`

type LockWorkflowForRolloutParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockWorkflowForRollout(ctx context.Context, arg LockWorkflowForRolloutParams) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkflowForRollout, arg.OrgID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const queryWorkflowHealthSignals = `-- name: QueryWorkflowHealthSignals :one
WITH candidate_runs AS (
  -- A saved workflow's plain runs carry workflow_version_id = the WORKFLOW
  -- id (the pilot's no-rollout convention); pinned/rollout runs carry a
  -- real version-row id. The effective version for un-pinned runs is the
  -- number of versions saved at run time.
  SELECT r.id, r.status, r.created_at,
         coalesce(
           (SELECT wv.version FROM workflow_versions wv
            WHERE wv.id = r.workflow_version_id AND wv.org_id = $2),
           (SELECT count(*) FROM workflow_versions v2
            WHERE v2.workflow_id = $1 AND v2.org_id = $2
              AND v2.created_at <= r.created_at)
         )::int AS effective_version
  FROM runs r
  WHERE r.org_id = $2
    AND r.created_at >= $3
    AND r.replay_mode IS NULL
    AND (r.workflow_version_id = $1
         OR r.workflow_version_id IN (SELECT v3.id FROM workflow_versions v3
              WHERE v3.workflow_id = $1 AND v3.org_id = $2))
), window_runs AS (
  SELECT id, status, created_at FROM candidate_runs
  WHERE ($4::int IS NULL OR effective_version < $4::int)
    AND ($5::int IS NULL OR effective_version >= $5::int)
), terminal AS (
  SELECT wr.id, wr.status, wr.created_at,
         (SELECT min(e.created_at) FROM run_events e
          WHERE e.run_id = wr.id AND e.type IN ('run.succeeded','run.failed','run.cancelled','run.timed_out')) AS terminal_at
  FROM window_runs wr
  WHERE wr.status IN ('succeeded','failed','cancelled','timed_out')
)
SELECT
  (SELECT count(*) FROM terminal)::int AS total_runs,
  (SELECT count(*) FROM terminal WHERE status = 'succeeded')::int AS success_count,
  (SELECT count(*) FROM terminal WHERE status = 'failed')::int AS failure_count,
  (SELECT count(*) FROM run_events e JOIN window_runs wr ON wr.id = e.run_id
   WHERE e.type = 'node.retry')::int AS retry_count,
  (SELECT count(*) FROM dead_letters d JOIN window_runs wr ON wr.id = d.run_id
   WHERE d.status = 'open')::int AS dlq_open_count,
  coalesce((SELECT percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (t.terminal_at - t.created_at)) * 1000)
   FROM terminal t WHERE t.terminal_at IS NOT NULL), -1)::float8 AS p95_latency_ms,
  coalesce((SELECT sum((u.metadata ->> 'costUsd')::float8) FROM usage_events u
   JOIN window_runs wr ON wr.id = u.run_id
   WHERE u.metadata ? 'costUsd' AND u.metadata ->> 'costUsd' != '<nil>'), 0)::float8 AS total_cost_usd,
  coalesce((SELECT sum(u.quantity) FROM usage_events u
   JOIN window_runs wr ON wr.id = u.run_id), 0)::float8 AS total_tokens,
  (SELECT count(*) FROM workflow_versions v2
   WHERE v2.workflow_id = $1 AND v2.org_id = $2)::int AS version_count,
  (SELECT count(*) FROM window_runs WHERE status = 'running')::int AS running_count
`

type QueryWorkflowHealthSignalsParams struct {
	WorkflowID    string
	OrgID         string
	Since         *time.Time
	BeforeVersion pgtype.Int4
	FromVersion   pgtype.Int4
}

type QueryWorkflowHealthSignalsRow struct {
	TotalRuns    int32
	SuccessCount int32
	FailureCount int32
	RetryCount   int32
	DlqOpenCount int32
	P95LatencyMs float64
	TotalCostUsd float64
	TotalTokens  float64
	VersionCount int32
	RunningCount int32
}

func (q *Queries) QueryWorkflowHealthSignals(ctx context.Context, arg QueryWorkflowHealthSignalsParams) (QueryWorkflowHealthSignalsRow, error) {
	row := q.db.QueryRow(ctx, queryWorkflowHealthSignals,
		arg.WorkflowID,
		arg.OrgID,
		arg.Since,
		arg.BeforeVersion,
		arg.FromVersion,
	)
	var i QueryWorkflowHealthSignalsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.SuccessCount,
		&i.FailureCount,
		&i.RetryCount,
		&i.DlqOpenCount,
		&i.P95LatencyMs,
		&i.TotalCostUsd,
		&i.TotalTokens,
		&i.VersionCount,
		&i.RunningCount,
	)
	return i, err
}

const renameWorkflowFolderBulk = `-- name: RenameWorkflowFolderBulk :execrows
UPDATE workflow_metadata SET folder = $2, updated_at = now()
WHERE org_id = $1 AND folder = $3
`

type RenameWorkflowFolderBulkParams struct {
	OrgID      string
	ToFolder   pgtype.Text
	FromFolder pgtype.Text
}

func (q *Queries) RenameWorkflowFolderBulk(ctx context.Context, arg RenameWorkflowFolderBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWorkflowFolderBulk, arg.OrgID, arg.ToFolder, arg.FromFolder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameWorkflowTagBulk = `-- name: RenameWorkflowTagBulk :execrows
UPDATE workflow_metadata
SET tags = (tags - $2::text) || to_jsonb($3::text),
    updated_at = now()
WHERE org_id = $1 AND tags ? $2::text
`

type RenameWorkflowTagBulkParams struct {
	OrgID   string
	FromTag string
	ToTag   string
}

func (q *Queries) RenameWorkflowTagBulk(ctx context.Context, arg RenameWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWorkflowTagBulk, arg.OrgID, arg.FromTag, arg.ToTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreWorkflow = `-- name: RestoreWorkflow :execrows
UPDATE workflows SET deleted_at = NULL
WHERE id = $1 AND org_id = $2 AND deleted_at IS NOT NULL
`

type RestoreWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RestoreWorkflow(ctx context.Context, arg RestoreWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreWorkflow, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkflowFolderOnly = `-- name: SetWorkflowFolderOnly :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, folder, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  folder = excluded.folder, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type SetWorkflowFolderOnlyParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Folder     pgtype.Text
	CreatedBy  pgtype.Text
}

func (q *Queries) SetWorkflowFolderOnly(ctx context.Context, arg SetWorkflowFolderOnlyParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, setWorkflowFolderOnly,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Folder,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const setWorkflowTagsOnly = `-- name: SetWorkflowTagsOnly :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, tags, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  tags = excluded.tags, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type SetWorkflowTagsOnlyParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Tags       json.RawMessage
	CreatedBy  pgtype.Text
}

func (q *Queries) SetWorkflowTagsOnly(ctx context.Context, arg SetWorkflowTagsOnlyParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, setWorkflowTagsOnly,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Tags,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const softDeleteWorkflow = `-- name: SoftDeleteWorkflow :execrows
UPDATE workflows SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) SoftDeleteWorkflow(ctx context.Context, arg SoftDeleteWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkflow, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorkflowMetadata = `-- name: UpsertWorkflowMetadata :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, owners, tags, description,
                               slack_channel, linear_project, severity_default,
                               folder, runbook_markdown, ai_guidance_markdown, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  owners = excluded.owners, tags = excluded.tags, description = excluded.description,
  slack_channel = excluded.slack_channel, linear_project = excluded.linear_project,
  severity_default = excluded.severity_default, folder = excluded.folder,
  runbook_markdown = excluded.runbook_markdown,
  ai_guidance_markdown = excluded.ai_guidance_markdown, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type UpsertWorkflowMetadataParams struct {
	ID                 string
	OrgID              string
	WorkflowID         string
	Owners             json.RawMessage
	Tags               json.RawMessage
	Description        pgtype.Text
	SlackChannel       pgtype.Text
	LinearProject      pgtype.Text
	SeverityDefault    pgtype.Text
	Folder             pgtype.Text
	RunbookMarkdown    pgtype.Text
	AiGuidanceMarkdown pgtype.Text
	CreatedBy          pgtype.Text
}

func (q *Queries) UpsertWorkflowMetadata(ctx context.Context, arg UpsertWorkflowMetadataParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowMetadata,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Owners,
		arg.Tags,
		arg.Description,
		arg.SlackChannel,
		arg.LinearProject,
		arg.SeverityDefault,
		arg.Folder,
		arg.RunbookMarkdown,
		arg.AiGuidanceMarkdown,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}
