// The closed audit-action catalog, extracted mechanically from the
// reference (apps/api/src/audit-helper.ts AuditAction union — 147 actions).
// Action is a distinct type and every write validates membership, so a
// typo'd action is a test failure here and can never land as a silent
// unfilterable row. Pilot-own actions (documented in the plan registry)
// register through RegisterPilotAction.
package audit

// Action names one auditable event from the closed catalog.
type Action string

var knownActions = map[Action]bool{
	"ai.generation.candidates_backoff":    true,
	"ai.run.explained":                    true,
	"ai.workflow.explained":               true,
	"ai.workflow.generated":               true,
	"ai.workflow.improvement_suggested":   true,
	"ai.workflow.patch_suggested":         true,
	"ai.workflow.reviewed":                true,
	"alert.policy.created":                true,
	"alert.policy.deleted":                true,
	"alert.policy.updated":                true,
	"auto_healing.decline.manual":         true,
	"auto_healing.scan.triggered":         true,
	"billing.budget.configured":           true,
	"billing.usage.exported":              true,
	"credential.bulk_updated":             true,
	"credential.created":                  true,
	"credential.expiry_set":               true,
	"credential.revoked":                  true,
	"dlq.replayed":                        true,
	"dlq.resolved":                        true,
	"eval.dataset.created":                true,
	"eval.dataset.deleted":                true,
	"eval.dataset.exported":               true,
	"experiment.run.completed":            true,
	"experiment.run.promotion_suggested":  true,
	"experiment.run.started":              true,
	"external_runtime.connection.created": true,
	"external_runtime.connection.deleted": true,
	"external_runtime.connection.updated": true,
	"invitation.created":                  true,
	"invitation.revoked":                  true,
	"mcp.connection.created":              true,
	"mcp.connection.deleted":              true,
	"mcp.connection.expose_to_ai_set":     true,
	"mcp.connection.rediscovered":         true,
	"mcp.connection.updated":              true,
	"mcp.tool.disabled":                   true,
	"mcp.tool.enabled":                    true,
	"mcp.tool.expose_to_ai_set":           true,
	"mcp.tool.rate_limit_set":             true,
	// member.joined is a real reference action used by invitation and domain
	// provisioning. The original port omitted it; the pin test holds the
	// resulting 148-action catalog closed.
	"member.joined":                            true,
	"member.removed":                           true,
	"member.role.updated":                      true,
	"member.self_modification_blocked":         true,
	"memory.consent.granted":                   true,
	"memory.consent.revoked":                   true,
	"onboarding.completed":                     true,
	"onboarding.restarted":                     true,
	"onboarding.resumed":                       true,
	"onboarding.skipped":                       true,
	"org.config.updated":                       true,
	"org.permissions.override_cleared":         true,
	"org.permissions.override_set":             true,
	"org.role.created":                         true,
	"org.role.deleted":                         true,
	"org.role.updated":                         true,
	"org.scim.directory_attached":              true,
	"org.scim.directory_revoked":               true,
	"org.scim.directory_updated":               true,
	"org.scim.group_role_mapping_created":      true,
	"org.scim.group_role_mapping_deleted":      true,
	"org.scim.group_role_mapping_updated":      true,
	"org.scim.resynced":                        true,
	"org.sso.connection_added":                 true,
	"org.sso.connection_revoked":               true,
	"org.sso.connection_updated":               true,
	"plugin.installed":                         true,
	"prompt.created":                           true,
	"prompt.version_created":                   true,
	"prompt.version_pinned":                    true,
	"recovery.campaign.cancelled":              true,
	"recovery.campaign.created":                true,
	"recovery.cluster_apply":                   true,
	"recovery.feedback":                        true,
	"recovery.handoff.github":                  true,
	"recovery.handoff.linear":                  true,
	"recovery.handoff.slack":                   true,
	"recovery.handoff.webhook":                 true,
	"recovery.item.acknowledged":               true,
	"recovery.item.assigned":                   true,
	"recovery.item.commented":                  true,
	"recovery.item.escalated":                  true,
	"recovery.item.in_progress":                true,
	"recovery.item.reopened":                   true,
	"recovery.item.resolved":                   true,
	"recovery.item.waiting_external":           true,
	"recovery.playbook.activated":              true,
	"recovery.playbook.applied":                true,
	"recovery.playbook.created":                true,
	"recovery.playbook.regressed":              true,
	"recovery.playbook.retired":                true,
	"recovery.playbook.used":                   true,
	"recovery.playbook.validated":              true,
	"recovery.semantic_resolved":               true,
	"recovery.validation_started":              true,
	"replay_lab.fork_started":                  true,
	"replay_lab.started":                       true,
	"report.evidence.delivered":                true,
	"report.evidence.exported":                 true,
	"report.recovery_validation.exported":      true,
	"report.run_explain.delivered":             true,
	"report.run_explain.exported":              true,
	"report.value_dashboard.exported":          true,
	"retention.purged":                         true,
	"run.cancelled":                            true,
	"run.redrive":                              true,
	"run.resumed":                              true,
	"run.started":                              true,
	"run.started.adhoc":                        true,
	"slack.interaction.created":                true,
	"slack.interaction.deleted":                true,
	"slack.interaction.updated":                true,
	"snippet.created":                          true,
	"snippet.deleted":                          true,
	"snippet.inserted":                         true,
	"snippet.updated":                          true,
	"solution_pack.failure_injected":           true,
	"solution_pack.sample_run_started":         true,
	"trigger.event.buffered":                   true,
	"trigger.event.received":                   true,
	"trigger.event.replayed":                   true,
	"trigger.event.skipped":                    true,
	"trigger.event.started":                    true,
	"upstream_health.source.created":           true,
	"upstream_health.source.deleted":           true,
	"upstream_health.source.updated":           true,
	"workflow.circuit_breaker.resumed":         true,
	"workflow.circuit_breaker.tripped":         true,
	"workflow.deleted":                         true,
	"workflow.folder.bulk_assigned":            true,
	"workflow.folder.deleted":                  true,
	"workflow.folder.renamed":                  true,
	"workflow.force_run_during_pause":          true,
	"workflow.metadata.set":                    true,
	"workflow.pack_imported":                   true,
	"workflow.recovery_qualification.recorded": true,
	"workflow.restored":                        true,
	"workflow.rolled_back":                     true,
	"workflow.rollout.promoted":                true,
	"workflow.rollout.rolled_back":             true,
	"workflow.rollout.started":                 true,
	"workflow.saved":                           true,
	"workflow.slo.set":                         true,
	"workflow.tag.deleted":                     true,
	"workflow.tag.renamed":                     true,
	"workflow.tag.set":                         true,
	"workflow.tags.bulk_assigned":              true,
	"workflow.trigger_backfill":                true,
}

// rawAuditActions holds reference actions written through the RAW audit()
// chokepoint (system-actor / skipAuth writers), which the typed
// AuditAction union — and therefore the parity pin above — deliberately
// excludes: the SCIM webhook lifecycle (scim-event-handler.ts), the public
// WorkOS SSO lifecycle, the Slack interaction callback, the upstream-health
// auto-pause watcher, the schedule sweep, auto-healing, and the memory consent
// purge.
var rawAuditActions = map[Action]bool{
	"auth.policy.rejected":              true,
	"auth.sso.callback_failed":          true,
	"auth.sso.login":                    true,
	"auth.sso.start":                    true,
	"auth.sso.state_invalid":            true,
	"auto_healing.apply.manual":         true,
	"auto_healing.failed":               true,
	"memory.bulk.purged":                true,
	"org.created":                       true,
	"recovery.item.created":             true,
	"recovery.item.occurrence_attached": true,
	"schedule.entry.disabled":           true,
	"schedule.tick.dropped":             true,
	"scim.group.membership_changed":     true,
	"scim.group.synced":                 true,
	"scim.user.deprovisioned":           true,
	"scim.user.provision_collision":     true,
	"scim.user.provision_rejected":      true,
	"scim.user.provisioned":             true,
	"scim.user.rekey_collision":         true,
	"scim.user.resurrection_blocked":    true,
	"scim.user.updated":                 true,
	"scim.webhook.directory_revoked":    true,
	"scim.webhook.event_replayed":       true,
	"scim.webhook.malformed_payload":    true,
	"scim.webhook.malformed_timestamp":  true,
	"scim.webhook.missing_directory_id": true,
	"scim.webhook.out_of_order":         true,
	"scim.webhook.signature_invalid":    true,
	"scim.webhook.unknown_directory":    true,
	"scim.webhook.unknown_event":        true,
	"scim.webhook.unknown_user":         true,
	"slack.interaction.opened":          true,
	"slack.interaction.rejected":        true,
	"workflow.paused.upstream":          true,
	"workflow.resumed.upstream":         true,
}

// pilotActions holds pilot-own additions, kept separate so the parity pin
// on the reference count stays exact.
var pilotActions = map[Action]bool{}

// RegisterPilotAction admits a pilot-own action name (call at init).
func RegisterPilotAction(action Action) { pilotActions[action] = true }

// IsKnown reports catalog membership (reference typed-union, reference
// raw-audit, or pilot-own).
func IsKnown(action Action) bool {
	return knownActions[action] || rawAuditActions[action] || pilotActions[action]
}

// ReferenceActionCount anchors the parity pin test.
func ReferenceActionCount() int { return len(knownActions) }
