/**
 * Deterministic OpenAPI 3.1 generation from the route registry.
 *
 * Used by `/v1/openapi.json`, the checked-in contract generator, and contract
 * tests. Zod 4 is the only schema source; no parallel hand-written model tree.
 */

import { z } from "zod";

import type { ApiContractRouteDescriptor, ApiRouteContract } from "./api-contract-types";
import type { ApiErrorCode } from "./error-codes";

const GENERIC_ERROR_CODES = [
  "server_internal_error",
  "server_not_found",
  "server_request_failed",
] as const satisfies readonly ApiErrorCode[];

type JsonSchema = Record<string, unknown>;

/** Build the complete public contract. Throws on duplicate paths or operation IDs. */
export function buildOpenApiDocument(routes: readonly ApiContractRouteDescriptor[]): Record<string, unknown> {
  const contracted = [...routes]
    .sort((a, b) => {
      const pathOrder = a.contract.path.localeCompare(b.contract.path);
      return pathOrder || a.method.localeCompare(b.method);
    });
  assertUniqueContracts(contracted);

  const paths: Record<string, Record<string, unknown>> = {};
  for (const route of contracted) {
    const contract = route.contract;
    const pathItem = paths[contract.path] ?? {};
    pathItem[route.method.toLowerCase()] = buildOperation(route, contract);
    paths[contract.path] = pathItem;
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "Janusly API",
      version: "1.0.0",
      description: "Stable, tenant-scoped Janusly operator API. Legacy unversioned routes remain available during migration.",
    },
    servers: [{ url: "/v1", description: "Version 1" }],
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
        januslySession: { type: "apiKey", in: "cookie", name: "janusly_session" },
        devOrg: { type: "apiKey", in: "header", name: "x-org-id" },
        devUser: { type: "apiKey", in: "header", name: "x-user-id" },
      },
    },
  };
}

/** Stable JSON used by both the writer and the CI drift checker. */
export function serializeOpenApi(routes: readonly ApiContractRouteDescriptor[]): string {
  return `${JSON.stringify(buildOpenApiDocument(routes), null, 2)}\n`;
}

function buildOperation(route: ApiContractRouteDescriptor, contract: ApiRouteContract): Record<string, unknown> {
  const errorCodes = [...new Set([...GENERIC_ERROR_CODES, ...contract.errorCodes])].sort();
  return {
    operationId: contract.operationId,
    summary: contract.summary,
    tags: contract.tags,
    security: route.skipAuth
      ? []
      : [
          { bearerAuth: [] },
          { januslySession: [] },
          { devOrg: [], devUser: [] },
        ],
    ...(route.role ? { "x-janusly-minimum-role": route.role } : {}),
    ...(route.permission ? { "x-janusly-permission": route.permission } : {}),
    ...buildRequest(contract),
    responses: {
      "200": {
        description: "Successful response",
        headers: requestIdResponseHeader(),
        content: {
          "application/json": {
            schema: {
              type: "object",
              properties: {
                apiVersion: { const: "v1" },
                requestId: { type: "string" },
                data: toJsonSchema(contract.response),
              },
              required: ["apiVersion", "requestId", "data"],
              additionalProperties: false,
            },
          },
        },
      },
      default: {
        description: "Catalogued error response",
        headers: requestIdResponseHeader(),
        content: {
          "application/json": {
            schema: {
              type: "object",
              properties: {
                apiVersion: { const: "v1" },
                requestId: { type: "string" },
                error: {
                  type: "object",
                  properties: {
                    code: { type: "string", enum: errorCodes },
                    message: { type: "string" },
                    params: {
                      type: "object",
                      additionalProperties: { type: ["string", "number", "boolean"] },
                    },
                  },
                  required: ["code", "message"],
                  additionalProperties: false,
                },
              },
              required: ["apiVersion", "requestId", "error"],
              additionalProperties: false,
            },
          },
        },
      },
    },
  };
}

function requestIdResponseHeader(): Record<string, unknown> {
  return {
    "X-Request-Id": {
      description: "Correlation ID echoed from the request or generated by Janusly.",
      schema: { type: "string" },
    },
  };
}

function buildRequest(contract: ApiRouteContract): Record<string, unknown> {
  const request: Record<string, unknown> = {};
  const parameters: Array<Record<string, unknown>> = [];
  const path = contract.request?.path;
  const pathProperties = path
    ? asObject(toJsonSchema(path).properties)
    : {};
  const pathParameterNames = assertPathParameterParity(contract.path, pathProperties);
  for (const name of pathParameterNames) {
    const propertySchema = pathProperties[name];
    if (propertySchema) {
      parameters.push({
        name,
        in: "path",
        required: true,
        schema: propertySchema,
      });
    }
  }
  const query = contract.request?.query;
  if (query) {
    const schema = toJsonSchema(query);
    const properties = asObject(schema.properties);
    const required = new Set(Array.isArray(schema.required) ? schema.required.filter((item): item is string => typeof item === "string") : []);
    parameters.push(...Object.entries(properties).map(([name, propertySchema]) => ({
      name,
      in: "query",
      required: required.has(name),
      schema: propertySchema,
    })));
  }
  if (parameters.length > 0) request.parameters = parameters;
  const body = contract.request?.body;
  if (body) {
    request.requestBody = {
      required: true,
      content: { "application/json": { schema: toJsonSchema(body) } },
    };
  }
  return request;
}

function assertPathParameterParity(
  contractPath: string,
  properties: Record<string, unknown>,
): string[] {
  const templateNames = contractPath
    .split("/")
    .map((segment) => segment.match(/^\{([^{}]+)\}$/)?.[1])
    .filter((name): name is string => Boolean(name));
  const schemaNames = Object.keys(properties);
  if (
    templateNames.length !== schemaNames.length
    || templateNames.some((name) => !schemaNames.includes(name))
  ) {
    throw new Error(
      `API contract path parameters do not match ${contractPath}: template=[${templateNames.join(",")}] schema=[${schemaNames.join(",")}]`,
    );
  }
  return templateNames;
}

function toJsonSchema(schema: z.ZodType): JsonSchema {
  // Runtime validation calls `safeParse` on the wire payload. Zod object
  // schemas accept additive keys unless explicitly strict, so input-mode JSON
  // Schema is the matching public contract. Output mode would incorrectly add
  // `additionalProperties: false` to every ordinary `z.object` response.
  const jsonSchema = z.toJSONSchema(schema, {
    target: "draft-2020-12",
    io: "input",
  }) as JsonSchema;
  // OpenAPI 3.1 already declares the dialect globally; repeating `$schema` in
  // every inline fragment creates noisy, semantically empty contract diffs.
  const { $schema: _dialect, ...rest } = jsonSchema;
  return rest;
}

function asObject(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function assertUniqueContracts(routes: readonly ApiContractRouteDescriptor[]): void {
  const operationIds = new Set<string>();
  const methodPaths = new Set<string>();
  for (const route of routes) {
    const operationId = route.contract.operationId;
    if (operationIds.has(operationId)) throw new Error(`Duplicate API operationId: ${operationId}`);
    operationIds.add(operationId);

    const methodPath = `${route.method} ${route.contract.path}`;
    if (methodPaths.has(methodPath)) throw new Error(`Duplicate API contract path: ${methodPath}`);
    methodPaths.add(methodPath);
  }
}
