// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authoringexperiences.sql

package store

import (
	"context"
	"encoding/json"
	"time"
)

const authoringExperienceExists = `-- name: AuthoringExperienceExists :one
SELECT EXISTS (SELECT 1 FROM authoring_experiences WHERE org_id=$1 AND id=$2)
`

type AuthoringExperienceExistsParams struct {
	OrgID string
	ID    string
}

func (q *Queries) AuthoringExperienceExists(ctx context.Context, arg AuthoringExperienceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, authoringExperienceExists, arg.OrgID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteExpiredAuthoringExperienceSource = `-- name: DeleteExpiredAuthoringExperienceSource :exec
DELETE FROM authoring_experiences
WHERE org_id=$1 AND workflow_id=$2 AND workflow_version_id=$3 AND brief_key=$4
  AND retain_until <= $5::timestamptz
`

type DeleteExpiredAuthoringExperienceSourceParams struct {
	OrgID             string
	WorkflowID        string
	WorkflowVersionID string
	BriefKey          string
	AsOf              time.Time
}

// Expired active rows no longer prevent a fresh explicit registration. Never
// extend a still-active entry's deadline by merely submitting it again.
func (q *Queries) DeleteExpiredAuthoringExperienceSource(ctx context.Context, arg DeleteExpiredAuthoringExperienceSourceParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthoringExperienceSource,
		arg.OrgID,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.BriefKey,
		arg.AsOf,
	)
	return err
}

const findAuthoringExperienceCandidates = `-- name: FindAuthoringExperienceCandidates :many
SELECT e.id,e.org_id,e.workflow_id,e.workflow_version_id,v.version,e.brief_key,e.policy_version,
       e.registered_at,v.created_at AS version_created_at,e.retain_until,e.revoked_at,w.deleted_at,v.dag_json
FROM authoring_experiences e
JOIN workflow_versions v ON v.org_id=e.org_id AND v.workflow_id=e.workflow_id AND v.id=e.workflow_version_id
JOIN workflows w ON w.org_id=e.org_id AND w.id=e.workflow_id
WHERE e.org_id=$1 AND e.brief_key=$2
  AND e.schema_version='1' AND e.policy_version='authoring-experience-v1'
  AND e.registered_at <= $3::timestamptz AND v.created_at <= $3::timestamptz
  AND e.retain_until > $3::timestamptz
  AND (e.revoked_at IS NULL OR ($4::boolean AND e.revoked_at > $3::timestamptz))
  AND (w.deleted_at IS NULL OR ($4::boolean AND w.deleted_at > $3::timestamptz))
  AND octet_length(v.dag_json::text) <= 2097152
ORDER BY e.registered_at DESC,e.id COLLATE "C" DESC
LIMIT 7
FOR SHARE OF e,w,v
`

type FindAuthoringExperienceCandidatesParams struct {
	OrgID      string
	BriefKey   string
	AsOf       time.Time
	Historical bool
}

type FindAuthoringExperienceCandidatesRow struct {
	ID                string
	OrgID             string
	WorkflowID        string
	WorkflowVersionID string
	Version           int32
	BriefKey          string
	PolicyVersion     string
	RegisteredAt      time.Time
	VersionCreatedAt  *time.Time
	RetainUntil       time.Time
	RevokedAt         *time.Time
	DeletedAt         *time.Time
	DagJson           json.RawMessage
}

// Temporal eligibility precedes the bounded source-work horizon. Historical
// reads consume an explicit frozen consent snapshot at the caller; current
// config is not proof of past consent. Live reads reject any tombstone.
func (q *Queries) FindAuthoringExperienceCandidates(ctx context.Context, arg FindAuthoringExperienceCandidatesParams) ([]FindAuthoringExperienceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findAuthoringExperienceCandidates,
		arg.OrgID,
		arg.BriefKey,
		arg.AsOf,
		arg.Historical,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAuthoringExperienceCandidatesRow
	for rows.Next() {
		var i FindAuthoringExperienceCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.Version,
			&i.BriefKey,
			&i.PolicyVersion,
			&i.RegisteredAt,
			&i.VersionCreatedAt,
			&i.RetainUntil,
			&i.RevokedAt,
			&i.DeletedAt,
			&i.DagJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthoringExperienceVersion = `-- name: GetAuthoringExperienceVersion :one
SELECT v.id, v.version, v.dag_json, v.created_at
FROM workflow_versions v JOIN workflows w ON w.org_id=v.org_id AND w.id=v.workflow_id
WHERE v.org_id=$1 AND v.workflow_id=$2 AND v.id=$3 AND w.deleted_at IS NULL
  AND v.created_at <= $4::timestamptz
  AND octet_length(v.dag_json::text) <= 2097152
FOR SHARE OF w, v
`

type GetAuthoringExperienceVersionParams struct {
	OrgID      string
	WorkflowID string
	ID         string
	AsOf       time.Time
}

type GetAuthoringExperienceVersionRow struct {
	ID        string
	Version   int32
	DagJson   json.RawMessage
	CreatedAt *time.Time
}

func (q *Queries) GetAuthoringExperienceVersion(ctx context.Context, arg GetAuthoringExperienceVersionParams) (GetAuthoringExperienceVersionRow, error) {
	row := q.db.QueryRow(ctx, getAuthoringExperienceVersion,
		arg.OrgID,
		arg.WorkflowID,
		arg.ID,
		arg.AsOf,
	)
	var i GetAuthoringExperienceVersionRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.DagJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthoringExperience = `-- name: InsertAuthoringExperience :one
INSERT INTO authoring_experiences
(id,org_id,workflow_id,workflow_version_id,brief_key,brief_json,policy_version,registered_at,retain_until,created_by)
SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
WHERE octet_length($6::jsonb::text) <= 8192
ON CONFLICT (org_id,workflow_id,workflow_version_id,brief_key,policy_version) WHERE revoked_at IS NULL
DO UPDATE SET id = authoring_experiences.id
RETURNING id, org_id, workflow_id, workflow_version_id, brief_key, brief_json, schema_version, policy_version, registered_at, retain_until, revoked_at, created_by
`

type InsertAuthoringExperienceParams struct {
	ID                string
	OrgID             string
	WorkflowID        string
	WorkflowVersionID string
	BriefKey          string
	BriefJson         json.RawMessage
	PolicyVersion     string
	RegisteredAt      time.Time
	RetainUntil       time.Time
	CreatedBy         string
}

func (q *Queries) InsertAuthoringExperience(ctx context.Context, arg InsertAuthoringExperienceParams) (AuthoringExperience, error) {
	row := q.db.QueryRow(ctx, insertAuthoringExperience,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.BriefKey,
		arg.BriefJson,
		arg.PolicyVersion,
		arg.RegisteredAt,
		arg.RetainUntil,
		arg.CreatedBy,
	)
	var i AuthoringExperience
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.BriefKey,
		&i.BriefJson,
		&i.SchemaVersion,
		&i.PolicyVersion,
		&i.RegisteredAt,
		&i.RetainUntil,
		&i.RevokedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAuthoringExperiences = `-- name: ListAuthoringExperiences :many
SELECT e.id,e.workflow_id,e.workflow_version_id,v.version,e.policy_version,e.registered_at,e.retain_until
FROM authoring_experiences e
JOIN workflow_versions v ON v.org_id=e.org_id AND v.workflow_id=e.workflow_id AND v.id=e.workflow_version_id
JOIN workflows w ON w.org_id=e.org_id AND w.id=e.workflow_id
WHERE e.org_id=$1 AND e.workflow_id=$2 AND e.revoked_at IS NULL AND w.deleted_at IS NULL
  AND e.schema_version='1' AND e.policy_version='authoring-experience-v1'
  AND e.registered_at <= $3::timestamptz AND v.created_at <= $3::timestamptz
  AND e.retain_until > $3::timestamptz
ORDER BY e.registered_at DESC,e.id DESC
LIMIT $4
`

type ListAuthoringExperiencesParams struct {
	OrgID      string
	WorkflowID string
	AsOf       time.Time
	RowLimit   int32
}

type ListAuthoringExperiencesRow struct {
	ID                string
	WorkflowID        string
	WorkflowVersionID string
	Version           int32
	PolicyVersion     string
	RegisteredAt      time.Time
	RetainUntil       time.Time
}

func (q *Queries) ListAuthoringExperiences(ctx context.Context, arg ListAuthoringExperiencesParams) ([]ListAuthoringExperiencesRow, error) {
	rows, err := q.db.Query(ctx, listAuthoringExperiences,
		arg.OrgID,
		arg.WorkflowID,
		arg.AsOf,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthoringExperiencesRow
	for rows.Next() {
		var i ListAuthoringExperiencesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.Version,
			&i.PolicyVersion,
			&i.RegisteredAt,
			&i.RetainUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthoringExperienceConsent = `-- name: LockAuthoringExperienceConsent :many
SELECT key, value_json FROM org_configs
WHERE org_id = $1 AND key IN ('ai.authoringExperienceEnabled','memory.enabled','memory.allowedKinds','memory.retentionDaysByKind')
ORDER BY key FOR SHARE
`

type LockAuthoringExperienceConsentRow struct {
	Key       string
	ValueJson json.RawMessage
}

// Consent readers lock a stable, small key set before registration. Config
// writers and the revocation trigger cannot overtake an admitted insertion.
func (q *Queries) LockAuthoringExperienceConsent(ctx context.Context, orgID string) ([]LockAuthoringExperienceConsentRow, error) {
	rows, err := q.db.Query(ctx, lockAuthoringExperienceConsent, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAuthoringExperienceConsentRow
	for rows.Next() {
		var i LockAuthoringExperienceConsentRow
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthoringExperienceResolveConsent = `-- name: LockAuthoringExperienceResolveConsent :many
SELECT key, value_json FROM org_configs
WHERE org_id = $1 AND key IN ('ai.authoringExperienceEnabled','memory.enabled','memory.allowedKinds','memory.retentionDaysByKind')
ORDER BY key FOR UPDATE
`

type LockAuthoringExperienceResolveConsentRow struct {
	Key       string
	ValueJson json.RawMessage
}

// Resolution serializes against registration as well as consent writers.
// Taking this mode initially avoids lock-upgrade deadlocks between resolvers.
func (q *Queries) LockAuthoringExperienceResolveConsent(ctx context.Context, orgID string) ([]LockAuthoringExperienceResolveConsentRow, error) {
	rows, err := q.db.Query(ctx, lockAuthoringExperienceResolveConsent, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAuthoringExperienceResolveConsentRow
	for rows.Next() {
		var i LockAuthoringExperienceResolveConsentRow
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuthoringExperiencesBatch = `-- name: PurgeAuthoringExperiencesBatch :execrows
DELETE FROM authoring_experiences WHERE id IN (
 SELECT id FROM authoring_experiences
 WHERE retain_until <= $1::timestamptz
    OR revoked_at <= $2::timestamptz
 ORDER BY retain_until,id FOR UPDATE SKIP LOCKED LIMIT $3
)
`

type PurgeAuthoringExperiencesBatchParams struct {
	AsOf          time.Time
	RevokedBefore time.Time
	BatchSize     int32
}

// One bounded batch rides the existing retention loop. Physical removal is
// independent of the immediate eligibility/consent fence.
func (q *Queries) PurgeAuthoringExperiencesBatch(ctx context.Context, arg PurgeAuthoringExperiencesBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuthoringExperiencesBatch, arg.AsOf, arg.RevokedBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeAuthoringExperiencesForOrg = `-- name: PurgeAuthoringExperiencesForOrg :execrows
DELETE FROM authoring_experiences WHERE org_id=$1
`

func (q *Queries) PurgeAuthoringExperiencesForOrg(ctx context.Context, orgID string) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuthoringExperiencesForOrg, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthoringExperience = `-- name: RevokeAuthoringExperience :execrows
UPDATE authoring_experiences SET revoked_at=$3::timestamptz
WHERE org_id=$1 AND id=$2 AND revoked_at IS NULL
`

type RevokeAuthoringExperienceParams struct {
	OrgID string
	ID    string
	AsOf  time.Time
}

// Only an active row transitions; repeat withdrawals keep the first timestamp
// and report no transition so callers audit a revocation exactly once.
func (q *Queries) RevokeAuthoringExperience(ctx context.Context, arg RevokeAuthoringExperienceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthoringExperience, arg.OrgID, arg.ID, arg.AsOf)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
