// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertReplayCampaignItems implements pgx.CopyFromSource.
type iteratorForInsertReplayCampaignItems struct {
	rows                 []InsertReplayCampaignItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertReplayCampaignItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertReplayCampaignItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OrgID,
		r.rows[0].CampaignID,
		r.rows[0].DeadLetterID,
		r.rows[0].Position,
	}, nil
}

func (r iteratorForInsertReplayCampaignItems) Err() error {
	return nil
}

func (q *Queries) InsertReplayCampaignItems(ctx context.Context, arg []InsertReplayCampaignItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"replay_campaign_items"}, []string{"id", "org_id", "campaign_id", "dead_letter_id", "position"}, &iteratorForInsertReplayCampaignItems{rows: arg})
}

// iteratorForInsertRunEvents implements pgx.CopyFromSource.
type iteratorForInsertRunEvents struct {
	rows                 []InsertRunEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRunEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRunEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].OrgID,
		r.rows[0].NodeID,
		r.rows[0].Type,
		r.rows[0].Payload,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertRunEvents) Err() error {
	return nil
}

// One COPY for every event a completion-family transaction appends:
// same columns and payload bytes as InsertRunEventAt, one
// round trip instead of one per event.
func (q *Queries) InsertRunEvents(ctx context.Context, arg []InsertRunEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_events"}, []string{"id", "run_id", "org_id", "node_id", "type", "payload", "created_at"}, &iteratorForInsertRunEvents{rows: arg})
}

// iteratorForInsertRunNodes implements pgx.CopyFromSource.
type iteratorForInsertRunNodes struct {
	rows                 []InsertRunNodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRunNodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRunNodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].OrgID,
		r.rows[0].NodeID,
		r.rows[0].Status,
		r.rows[0].Attempts,
		r.rows[0].StateJson,
		r.rows[0].QueuePublicationRepairAfter,
		r.rows[0].QueuePublicationGeneration,
	}, nil
}

func (r iteratorForInsertRunNodes) Err() error {
	return nil
}

// Initial executable roots expose one Node-compatible rollback generation;
// pending descendants do not become publishable until readiness queues them.
// Run start writes every node row in one COPY; the queued roots carry the
// publication stamp InsertRunNode computes in SQL.
func (q *Queries) InsertRunNodes(ctx context.Context, arg []InsertRunNodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_nodes"}, []string{"id", "run_id", "org_id", "node_id", "status", "attempts", "state_json", "queue_publication_repair_after", "queue_publication_generation"}, &iteratorForInsertRunNodes{rows: arg})
}
