// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueUpstreamHealthSources = `-- name: ClaimDueUpstreamHealthSources :many
UPDATE upstream_health_sources SET last_checked_at = now()
FROM (
  SELECT due.id FROM upstream_health_sources AS due
  WHERE due.enabled = true
    AND (due.last_checked_at IS NULL
         OR due.last_checked_at <= now() - make_interval(secs => due.check_interval_seconds))
  ORDER BY due.last_checked_at NULLS FIRST
  LIMIT $1
  FOR UPDATE SKIP LOCKED
) AS claimed
WHERE upstream_health_sources.id = claimed.id
RETURNING upstream_health_sources.id, upstream_health_sources.org_id, upstream_health_sources.name, upstream_health_sources.kind, upstream_health_sources.url, upstream_health_sources.expected_components, upstream_health_sources.check_interval_seconds, upstream_health_sources.enabled, upstream_health_sources.last_status, upstream_health_sources.last_degraded, upstream_health_sources.last_checked_at, upstream_health_sources.last_error_reason, upstream_health_sources.created_by, upstream_health_sources.created_at, upstream_health_sources.updated_at
`

// Claim-to-poll: the due check reads last_checked_at and the poller only
// writes it AFTER fetching, so every replica polled every due source.
// Stamping the clock inside the claim makes the sweep exclusive without a
// lock — the loser simply sees a source that is no longer due.
func (q *Queries) ClaimDueUpstreamHealthSources(ctx context.Context, rowLimit int32) ([]UpstreamHealthSource, error) {
	rows, err := q.db.Query(ctx, claimDueUpstreamHealthSources, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamHealthSource
	for rows.Next() {
		var i UpstreamHealthSource
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.ExpectedComponents,
			&i.CheckIntervalSeconds,
			&i.Enabled,
			&i.LastStatus,
			&i.LastDegraded,
			&i.LastCheckedAt,
			&i.LastErrorReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBufferedTriggerEvents = `-- name: CountBufferedTriggerEvents :one
SELECT count(*) FROM trigger_events te
WHERE te.org_id = $1 AND te.workflow_id = $2 AND te.status = 'buffered'
  AND te.backfill_claim_token IS NULL
`

type CountBufferedTriggerEventsParams struct {
	OrgID      string
	WorkflowID pgtype.Text
}

func (q *Queries) CountBufferedTriggerEvents(ctx context.Context, arg CountBufferedTriggerEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBufferedTriggerEvents, arg.OrgID, arg.WorkflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMcpToolDescriptorsByConnection = `-- name: CountMcpToolDescriptorsByConnection :many
SELECT d.connection_id,
       count(*)::int AS total,
       count(*) FILTER (WHERE d.enabled)::int AS enabled
FROM mcp_tool_descriptors d
WHERE d.connection_id = ANY($1::text[])
GROUP BY d.connection_id
`

type CountMcpToolDescriptorsByConnectionRow struct {
	ConnectionID string
	Total        int32
	Enabled      int32
}

// The connections panel only needs counts, and fetching every descriptor
// row per connection made the listing N+1 in both queries and payload.
func (q *Queries) CountMcpToolDescriptorsByConnection(ctx context.Context, connectionIds []string) ([]CountMcpToolDescriptorsByConnectionRow, error) {
	rows, err := q.db.Query(ctx, countMcpToolDescriptorsByConnection, connectionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMcpToolDescriptorsByConnectionRow
	for rows.Next() {
		var i CountMcpToolDescriptorsByConnectionRow
		if err := rows.Scan(&i.ConnectionID, &i.Total, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCredential = `-- name: DeleteCredential :execrows
DELETE FROM credentials WHERE org_id = $1 AND id = $2
`

type DeleteCredentialParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredential, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSlackInteractionConnection = `-- name: DeleteSlackInteractionConnection :execrows
DELETE FROM slack_interaction_connections WHERE org_id = $1 AND id = $2
`

type DeleteSlackInteractionConnectionParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteSlackInteractionConnection(ctx context.Context, arg DeleteSlackInteractionConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSlackInteractionConnection, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUpstreamHealthSource = `-- name: DeleteUpstreamHealthSource :one
DELETE FROM upstream_health_sources
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, kind, url, expected_components, check_interval_seconds, enabled, last_status, last_degraded, last_checked_at, last_error_reason, created_by, created_at, updated_at
`

type DeleteUpstreamHealthSourceParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteUpstreamHealthSource(ctx context.Context, arg DeleteUpstreamHealthSourceParams) (UpstreamHealthSource, error) {
	row := q.db.QueryRow(ctx, deleteUpstreamHealthSource, arg.OrgID, arg.ID)
	var i UpstreamHealthSource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.ExpectedComponents,
		&i.CheckIntervalSeconds,
		&i.Enabled,
		&i.LastStatus,
		&i.LastDegraded,
		&i.LastCheckedAt,
		&i.LastErrorReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTriggerEventByDedupe = `-- name: FindTriggerEventByDedupe :one
SELECT id, org_id, trigger_type, workflow_id, workflow_version_id, node_id,
       status, run_id, dedupe_key, payload_json, skipped_reason, created_at
FROM trigger_events
WHERE org_id = $1 AND dedupe_key = $2
`

type FindTriggerEventByDedupeParams struct {
	OrgID     string
	DedupeKey pgtype.Text
}

type FindTriggerEventByDedupeRow struct {
	ID                string
	OrgID             string
	TriggerType       string
	WorkflowID        pgtype.Text
	WorkflowVersionID string
	NodeID            string
	Status            string
	RunID             pgtype.Text
	DedupeKey         pgtype.Text
	PayloadJson       json.RawMessage
	SkippedReason     pgtype.Text
	CreatedAt         *time.Time
}

func (q *Queries) FindTriggerEventByDedupe(ctx context.Context, arg FindTriggerEventByDedupeParams) (FindTriggerEventByDedupeRow, error) {
	row := q.db.QueryRow(ctx, findTriggerEventByDedupe, arg.OrgID, arg.DedupeKey)
	var i FindTriggerEventByDedupeRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TriggerType,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.NodeID,
		&i.Status,
		&i.RunID,
		&i.DedupeKey,
		&i.PayloadJson,
		&i.SkippedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, org_id, name, kind, secret_ref, metadata, created_by, created_at, updated_at, expires_at FROM credentials WHERE org_id = $1 AND kind = $2 AND name = $3
`

type GetCredentialByNameParams struct {
	OrgID string
	Kind  string
	Name  string
}

func (q *Queries) GetCredentialByName(ctx context.Context, arg GetCredentialByNameParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByName, arg.OrgID, arg.Kind, arg.Name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.SecretRef,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCredentialByOrgName = `-- name: GetCredentialByOrgName :one
SELECT id, org_id, name, kind, secret_ref, updated_at, expires_at
FROM credentials WHERE org_id = $1 AND name = $2
`

type GetCredentialByOrgNameParams struct {
	OrgID string
	Name  string
}

type GetCredentialByOrgNameRow struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	SecretRef string
	UpdatedAt time.Time
	ExpiresAt *time.Time
}

func (q *Queries) GetCredentialByOrgName(ctx context.Context, arg GetCredentialByOrgNameParams) (GetCredentialByOrgNameRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByOrgName, arg.OrgID, arg.Name)
	var i GetCredentialByOrgNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.SecretRef,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCredentialSecretVersion = `-- name: GetCredentialSecretVersion :one
SELECT id, org_id, credential_id, version, ciphertext, data_nonce, data_tag,
       wrapped_key, wrap_nonce, wrap_tag, key_version
FROM credential_secret_versions
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type GetCredentialSecretVersionParams struct {
	ID    string
	OrgID string
}

type GetCredentialSecretVersionRow struct {
	ID           string
	OrgID        string
	CredentialID string
	Version      int32
	Ciphertext   string
	DataNonce    string
	DataTag      string
	WrappedKey   string
	WrapNonce    string
	WrapTag      string
	KeyVersion   int32
}

func (q *Queries) GetCredentialSecretVersion(ctx context.Context, arg GetCredentialSecretVersionParams) (GetCredentialSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, getCredentialSecretVersion, arg.ID, arg.OrgID)
	var i GetCredentialSecretVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CredentialID,
		&i.Version,
		&i.Ciphertext,
		&i.DataNonce,
		&i.DataTag,
		&i.WrappedKey,
		&i.WrapNonce,
		&i.WrapTag,
		&i.KeyVersion,
	)
	return i, err
}

const getMcpConnectionByAlias = `-- name: GetMcpConnectionByAlias :one
SELECT id, org_id, alias, transport, command, args, url, env_refs, enabled, status, status_reason, expose_to_ai, last_discovery_at, created_by, created_at, updated_at FROM mcp_connections WHERE org_id = $1 AND alias = $2
`

type GetMcpConnectionByAliasParams struct {
	OrgID string
	Alias string
}

func (q *Queries) GetMcpConnectionByAlias(ctx context.Context, arg GetMcpConnectionByAliasParams) (McpConnection, error) {
	row := q.db.QueryRow(ctx, getMcpConnectionByAlias, arg.OrgID, arg.Alias)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Alias,
		&i.Transport,
		&i.Command,
		&i.Args,
		&i.Url,
		&i.EnvRefs,
		&i.Enabled,
		&i.Status,
		&i.StatusReason,
		&i.ExposeToAi,
		&i.LastDiscoveryAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMcpToolDescriptor = `-- name: GetMcpToolDescriptor :one
SELECT id, connection_id, name, description, input_schema, write_side, enabled, rate_limit_per_min, expose_to_ai, created_at, updated_at FROM mcp_tool_descriptors WHERE connection_id = $1 AND name = $2
`

type GetMcpToolDescriptorParams struct {
	ConnectionID string
	Name         string
}

func (q *Queries) GetMcpToolDescriptor(ctx context.Context, arg GetMcpToolDescriptorParams) (McpToolDescriptor, error) {
	row := q.db.QueryRow(ctx, getMcpToolDescriptor, arg.ConnectionID, arg.Name)
	var i McpToolDescriptor
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.WriteSide,
		&i.Enabled,
		&i.RateLimitPerMin,
		&i.ExposeToAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackInteractionConnection = `-- name: GetSlackInteractionConnection :one
SELECT id, org_id, name, team_id, signing_credential_name, user_mappings, enabled, created_by, created_at, updated_at FROM slack_interaction_connections WHERE org_id = $1 AND id = $2
`

type GetSlackInteractionConnectionParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetSlackInteractionConnection(ctx context.Context, arg GetSlackInteractionConnectionParams) (SlackInteractionConnection, error) {
	row := q.db.QueryRow(ctx, getSlackInteractionConnection, arg.OrgID, arg.ID)
	var i SlackInteractionConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TeamID,
		&i.SigningCredentialName,
		&i.UserMappings,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackInteractionConnectionForCallback = `-- name: GetSlackInteractionConnectionForCallback :one
SELECT id, org_id, name, team_id, signing_credential_name, user_mappings, enabled, created_by, created_at, updated_at FROM slack_interaction_connections WHERE id = $1
`

func (q *Queries) GetSlackInteractionConnectionForCallback(ctx context.Context, id string) (SlackInteractionConnection, error) {
	row := q.db.QueryRow(ctx, getSlackInteractionConnectionForCallback, id)
	var i SlackInteractionConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TeamID,
		&i.SigningCredentialName,
		&i.UserMappings,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTriggerEvent = `-- name: GetTriggerEvent :one
SELECT id, org_id, trigger_type, workflow_id, workflow_version_id, node_id,
       status, run_id, dedupe_key, payload_json, skipped_reason, created_at
FROM trigger_events
WHERE org_id = $1 AND id = $2
`

type GetTriggerEventParams struct {
	OrgID string
	ID    string
}

type GetTriggerEventRow struct {
	ID                string
	OrgID             string
	TriggerType       string
	WorkflowID        pgtype.Text
	WorkflowVersionID string
	NodeID            string
	Status            string
	RunID             pgtype.Text
	DedupeKey         pgtype.Text
	PayloadJson       json.RawMessage
	SkippedReason     pgtype.Text
	CreatedAt         *time.Time
}

func (q *Queries) GetTriggerEvent(ctx context.Context, arg GetTriggerEventParams) (GetTriggerEventRow, error) {
	row := q.db.QueryRow(ctx, getTriggerEvent, arg.OrgID, arg.ID)
	var i GetTriggerEventRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TriggerType,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.NodeID,
		&i.Status,
		&i.RunID,
		&i.DedupeKey,
		&i.PayloadJson,
		&i.SkippedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUpstreamHealthSource = `-- name: GetUpstreamHealthSource :one
SELECT id, org_id, name, kind, url, expected_components, check_interval_seconds, enabled, last_status, last_degraded, last_checked_at, last_error_reason, created_by, created_at, updated_at FROM upstream_health_sources
WHERE org_id = $1 AND id = $2
`

type GetUpstreamHealthSourceParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetUpstreamHealthSource(ctx context.Context, arg GetUpstreamHealthSourceParams) (UpstreamHealthSource, error) {
	row := q.db.QueryRow(ctx, getUpstreamHealthSource, arg.OrgID, arg.ID)
	var i UpstreamHealthSource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.ExpectedComponents,
		&i.CheckIntervalSeconds,
		&i.Enabled,
		&i.LastStatus,
		&i.LastDegraded,
		&i.LastCheckedAt,
		&i.LastErrorReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (id, org_id, name, kind, secret_ref, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCredentialParams struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	SecretRef string
	CreatedBy pgtype.Text
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.SecretRef,
		arg.CreatedBy,
	)
	return err
}

const insertCredentialFull = `-- name: InsertCredentialFull :exec
INSERT INTO credentials (id, org_id, name, kind, secret_ref, metadata, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCredentialFullParams struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	SecretRef string
	Metadata  json.RawMessage
	ExpiresAt *time.Time
	CreatedBy pgtype.Text
}

func (q *Queries) InsertCredentialFull(ctx context.Context, arg InsertCredentialFullParams) error {
	_, err := q.db.Exec(ctx, insertCredentialFull,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.SecretRef,
		arg.Metadata,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const insertCredentialSecretVersion = `-- name: InsertCredentialSecretVersion :exec
INSERT INTO credential_secret_versions (id, org_id, credential_id, version, ciphertext,
  data_nonce, data_tag, wrapped_key, wrap_nonce, wrap_tag, key_version, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertCredentialSecretVersionParams struct {
	ID           string
	OrgID        string
	CredentialID string
	Version      int32
	Ciphertext   string
	DataNonce    string
	DataTag      string
	WrappedKey   string
	WrapNonce    string
	WrapTag      string
	KeyVersion   int32
	CreatedBy    pgtype.Text
}

func (q *Queries) InsertCredentialSecretVersion(ctx context.Context, arg InsertCredentialSecretVersionParams) error {
	_, err := q.db.Exec(ctx, insertCredentialSecretVersion,
		arg.ID,
		arg.OrgID,
		arg.CredentialID,
		arg.Version,
		arg.Ciphertext,
		arg.DataNonce,
		arg.DataTag,
		arg.WrappedKey,
		arg.WrapNonce,
		arg.WrapTag,
		arg.KeyVersion,
		arg.CreatedBy,
	)
	return err
}

const insertMcpConnection = `-- name: InsertMcpConnection :exec
INSERT INTO mcp_connections (id, org_id, alias, transport, command, args, url, env_refs, enabled, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertMcpConnectionParams struct {
	ID        string
	OrgID     string
	Alias     string
	Transport string
	Command   pgtype.Text
	Args      json.RawMessage
	Url       pgtype.Text
	EnvRefs   json.RawMessage
	Enabled   bool
	Status    string
	CreatedBy pgtype.Text
}

func (q *Queries) InsertMcpConnection(ctx context.Context, arg InsertMcpConnectionParams) error {
	_, err := q.db.Exec(ctx, insertMcpConnection,
		arg.ID,
		arg.OrgID,
		arg.Alias,
		arg.Transport,
		arg.Command,
		arg.Args,
		arg.Url,
		arg.EnvRefs,
		arg.Enabled,
		arg.Status,
		arg.CreatedBy,
	)
	return err
}

const insertSlackInteractionConnection = `-- name: InsertSlackInteractionConnection :exec
INSERT INTO slack_interaction_connections (id, org_id, name, team_id, signing_credential_name,
  user_mappings, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSlackInteractionConnectionParams struct {
	ID                    string
	OrgID                 string
	Name                  string
	TeamID                string
	SigningCredentialName string
	UserMappings          json.RawMessage
	Enabled               bool
	CreatedBy             string
}

func (q *Queries) InsertSlackInteractionConnection(ctx context.Context, arg InsertSlackInteractionConnectionParams) error {
	_, err := q.db.Exec(ctx, insertSlackInteractionConnection,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.TeamID,
		arg.SigningCredentialName,
		arg.UserMappings,
		arg.Enabled,
		arg.CreatedBy,
	)
	return err
}

const insertSlackInteractionReceipt = `-- name: InsertSlackInteractionReceipt :execrows
INSERT INTO slack_interaction_receipts (id, org_id, connection_id)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertSlackInteractionReceiptParams struct {
	ID           string
	OrgID        string
	ConnectionID string
}

func (q *Queries) InsertSlackInteractionReceipt(ctx context.Context, arg InsertSlackInteractionReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSlackInteractionReceipt, arg.ID, arg.OrgID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTriggerEvent = `-- name: InsertTriggerEvent :execrows

INSERT INTO trigger_events (id, org_id, trigger_type, workflow_id,
                            workflow_version_id, node_id, status, dedupe_key, payload_json,
                            workflow_rollout_id, workflow_rollout_variant)
VALUES ($1, $2, $3, $4, $5, $6, 'received', $7, $8, $9, $10)
ON CONFLICT (org_id, dedupe_key) DO NOTHING
`

type InsertTriggerEventParams struct {
	ID                     string
	OrgID                  string
	TriggerType            string
	WorkflowID             pgtype.Text
	WorkflowVersionID      string
	NodeID                 string
	DedupeKey              pgtype.Text
	PayloadJson            json.RawMessage
	WorkflowRolloutID      pgtype.Text
	WorkflowRolloutVariant pgtype.Text
}

// Credentials/secret store, MCP, Slack, external runtimes, upstream, triggers.
func (q *Queries) InsertTriggerEvent(ctx context.Context, arg InsertTriggerEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTriggerEvent,
		arg.ID,
		arg.OrgID,
		arg.TriggerType,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.NodeID,
		arg.DedupeKey,
		arg.PayloadJson,
		arg.WorkflowRolloutID,
		arg.WorkflowRolloutVariant,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUpstreamHealthSource = `-- name: InsertUpstreamHealthSource :one
INSERT INTO upstream_health_sources (id, org_id, name, kind, url,
                                     expected_components, check_interval_seconds,
                                     enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, kind, url, expected_components, check_interval_seconds, enabled, last_status, last_degraded, last_checked_at, last_error_reason, created_by, created_at, updated_at
`

type InsertUpstreamHealthSourceParams struct {
	ID                   string
	OrgID                string
	Name                 string
	Kind                 string
	Url                  string
	ExpectedComponents   json.RawMessage
	CheckIntervalSeconds int32
	Enabled              bool
	CreatedBy            pgtype.Text
}

func (q *Queries) InsertUpstreamHealthSource(ctx context.Context, arg InsertUpstreamHealthSourceParams) (UpstreamHealthSource, error) {
	row := q.db.QueryRow(ctx, insertUpstreamHealthSource,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Url,
		arg.ExpectedComponents,
		arg.CheckIntervalSeconds,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i UpstreamHealthSource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.ExpectedComponents,
		&i.CheckIntervalSeconds,
		&i.Enabled,
		&i.LastStatus,
		&i.LastDegraded,
		&i.LastCheckedAt,
		&i.LastErrorReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialUsageRows = `-- name: ListCredentialUsageRows :many
SELECT metadata ->> 'credentialName' AS credential_name, created_at,
       coalesce((metadata ->> 'ok')::bool, true) AS ok, metadata ->> 'error' AS error_message
FROM usage_events
WHERE org_id = $1 AND created_at >= $2
  AND metric LIKE 'tool.%' AND metadata ? 'credentialName'
ORDER BY created_at DESC
LIMIT 10000
`

type ListCredentialUsageRowsParams struct {
	OrgID     string
	CreatedAt *time.Time
}

type ListCredentialUsageRowsRow struct {
	CredentialName interface{}
	CreatedAt      *time.Time
	Ok             interface{}
	ErrorMessage   interface{}
}

func (q *Queries) ListCredentialUsageRows(ctx context.Context, arg ListCredentialUsageRowsParams) ([]ListCredentialUsageRowsRow, error) {
	rows, err := q.db.Query(ctx, listCredentialUsageRows, arg.OrgID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialUsageRowsRow
	for rows.Next() {
		var i ListCredentialUsageRowsRow
		if err := rows.Scan(
			&i.CredentialName,
			&i.CreatedAt,
			&i.Ok,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, org_id, name, kind, secret_ref, metadata, created_by, created_at, updated_at, expires_at
FROM credentials WHERE org_id = $1 ORDER BY name LIMIT 500
`

func (q *Queries) ListCredentials(ctx context.Context, orgID string) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.SecretRef,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposedMcpToolsForAi = `-- name: ListExposedMcpToolsForAi :many
SELECT c.alias, d.name, d.description, d.input_schema, d.write_side
FROM mcp_connections c
JOIN mcp_tool_descriptors d ON d.connection_id = c.id
WHERE c.org_id = $1 AND c.enabled = true AND c.expose_to_ai = true
  AND d.enabled = true AND d.expose_to_ai = true
ORDER BY c.alias, d.name
`

type ListExposedMcpToolsForAiRow struct {
	Alias       string
	Name        string
	Description pgtype.Text
	InputSchema json.RawMessage
	WriteSide   bool
}

func (q *Queries) ListExposedMcpToolsForAi(ctx context.Context, orgID string) ([]ListExposedMcpToolsForAiRow, error) {
	rows, err := q.db.Query(ctx, listExposedMcpToolsForAi, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExposedMcpToolsForAiRow
	for rows.Next() {
		var i ListExposedMcpToolsForAiRow
		if err := rows.Scan(
			&i.Alias,
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.WriteSide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpConnections = `-- name: ListMcpConnections :many
SELECT id, org_id, alias, transport, command, args, url, env_refs, enabled, status, status_reason, expose_to_ai, last_discovery_at, created_by, created_at, updated_at FROM mcp_connections WHERE org_id = $1 ORDER BY alias ASC LIMIT 200
`

func (q *Queries) ListMcpConnections(ctx context.Context, orgID string) ([]McpConnection, error) {
	rows, err := q.db.Query(ctx, listMcpConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Alias,
			&i.Transport,
			&i.Command,
			&i.Args,
			&i.Url,
			&i.EnvRefs,
			&i.Enabled,
			&i.Status,
			&i.StatusReason,
			&i.ExposeToAi,
			&i.LastDiscoveryAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpConnectionsForHealth = `-- name: ListMcpConnectionsForHealth :many
SELECT id, alias, transport, env_refs, enabled, status FROM mcp_connections
WHERE org_id = $1 ORDER BY alias LIMIT 200
`

type ListMcpConnectionsForHealthRow struct {
	ID        string
	Alias     string
	Transport string
	EnvRefs   json.RawMessage
	Enabled   bool
	Status    string
}

func (q *Queries) ListMcpConnectionsForHealth(ctx context.Context, orgID string) ([]ListMcpConnectionsForHealthRow, error) {
	rows, err := q.db.Query(ctx, listMcpConnectionsForHealth, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMcpConnectionsForHealthRow
	for rows.Next() {
		var i ListMcpConnectionsForHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Transport,
			&i.EnvRefs,
			&i.Enabled,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpToolDescriptorsByConnection = `-- name: ListMcpToolDescriptorsByConnection :many
SELECT id, connection_id, name, description, input_schema, write_side, enabled, rate_limit_per_min, expose_to_ai, created_at, updated_at FROM mcp_tool_descriptors WHERE connection_id = $1 ORDER BY name LIMIT 200
`

func (q *Queries) ListMcpToolDescriptorsByConnection(ctx context.Context, connectionID string) ([]McpToolDescriptor, error) {
	rows, err := q.db.Query(ctx, listMcpToolDescriptorsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpToolDescriptor
	for rows.Next() {
		var i McpToolDescriptor
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.WriteSide,
			&i.Enabled,
			&i.RateLimitPerMin,
			&i.ExposeToAi,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackInteractionConnections = `-- name: ListSlackInteractionConnections :many
SELECT id, org_id, name, team_id, signing_credential_name, user_mappings, enabled, created_by, created_at, updated_at FROM slack_interaction_connections WHERE org_id = $1 ORDER BY name LIMIT 100
`

func (q *Queries) ListSlackInteractionConnections(ctx context.Context, orgID string) ([]SlackInteractionConnection, error) {
	rows, err := q.db.Query(ctx, listSlackInteractionConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlackInteractionConnection
	for rows.Next() {
		var i SlackInteractionConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TeamID,
			&i.SigningCredentialName,
			&i.UserMappings,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpstreamHealthSources = `-- name: ListUpstreamHealthSources :many
SELECT id, org_id, name, kind, url, expected_components, check_interval_seconds, enabled, last_status, last_degraded, last_checked_at, last_error_reason, created_by, created_at, updated_at FROM upstream_health_sources
WHERE org_id = $1
ORDER BY lower(name)
`

func (q *Queries) ListUpstreamHealthSources(ctx context.Context, orgID string) ([]UpstreamHealthSource, error) {
	rows, err := q.db.Query(ctx, listUpstreamHealthSources, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamHealthSource
	for rows.Next() {
		var i UpstreamHealthSource
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.ExpectedComponents,
			&i.CheckIntervalSeconds,
			&i.Enabled,
			&i.LastStatus,
			&i.LastDegraded,
			&i.LastCheckedAt,
			&i.LastErrorReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCredentialByName = `-- name: LockCredentialByName :one
SELECT id, kind, secret_ref, updated_at FROM credentials
WHERE org_id = $1 AND name = $2 FOR UPDATE
`

type LockCredentialByNameParams struct {
	OrgID string
	Name  string
}

type LockCredentialByNameRow struct {
	ID        string
	Kind      string
	SecretRef string
	UpdatedAt time.Time
}

func (q *Queries) LockCredentialByName(ctx context.Context, arg LockCredentialByNameParams) (LockCredentialByNameRow, error) {
	row := q.db.QueryRow(ctx, lockCredentialByName, arg.OrgID, arg.Name)
	var i LockCredentialByNameRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SecretRef,
		&i.UpdatedAt,
	)
	return i, err
}

const markTriggerEventOutcome = `-- name: MarkTriggerEventOutcome :execrows
UPDATE trigger_events
SET status = $3, skipped_reason = $4
WHERE org_id = $1 AND id = $2 AND status = 'received'
`

type MarkTriggerEventOutcomeParams struct {
	OrgID         string
	ID            string
	Status        string
	SkippedReason pgtype.Text
}

func (q *Queries) MarkTriggerEventOutcome(ctx context.Context, arg MarkTriggerEventOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTriggerEventOutcome,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.SkippedReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextCredentialSecretVersion = `-- name: NextCredentialSecretVersion :one
SELECT (coalesce(max(version), 0) + 1)::int AS next_version
FROM credential_secret_versions
WHERE org_id = $1 AND credential_id = $2
`

type NextCredentialSecretVersionParams struct {
	OrgID        string
	CredentialID string
}

func (q *Queries) NextCredentialSecretVersion(ctx context.Context, arg NextCredentialSecretVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextCredentialSecretVersion, arg.OrgID, arg.CredentialID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const pauseWorkflowsForUpstream = `-- name: PauseWorkflowsForUpstream :many
UPDATE workflows
SET status = 'paused_upstream_degraded', paused_reason = $3
WHERE org_id = $1 AND id = ANY($2::text[]) AND status = 'active'
RETURNING id
`

type PauseWorkflowsForUpstreamParams struct {
	OrgID        string
	Column2      []string
	PausedReason pgtype.Text
}

func (q *Queries) PauseWorkflowsForUpstream(ctx context.Context, arg PauseWorkflowsForUpstreamParams) ([]string, error) {
	rows, err := q.db.Query(ctx, pauseWorkflowsForUpstream, arg.OrgID, arg.Column2, arg.PausedReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredSlackReceipts = `-- name: PurgeExpiredSlackReceipts :exec
DELETE FROM slack_interaction_receipts
WHERE org_id = $1 AND connection_id = $2 AND created_at < $3
`

type PurgeExpiredSlackReceiptsParams struct {
	OrgID        string
	ConnectionID string
	CreatedAt    time.Time
}

func (q *Queries) PurgeExpiredSlackReceipts(ctx context.Context, arg PurgeExpiredSlackReceiptsParams) error {
	_, err := q.db.Exec(ctx, purgeExpiredSlackReceipts, arg.OrgID, arg.ConnectionID, arg.CreatedAt)
	return err
}

const recordUpstreamPollError = `-- name: RecordUpstreamPollError :exec
UPDATE upstream_health_sources
SET last_checked_at = now(), last_error_reason = $3, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type RecordUpstreamPollErrorParams struct {
	OrgID           string
	ID              string
	LastErrorReason pgtype.Text
}

func (q *Queries) RecordUpstreamPollError(ctx context.Context, arg RecordUpstreamPollErrorParams) error {
	_, err := q.db.Exec(ctx, recordUpstreamPollError, arg.OrgID, arg.ID, arg.LastErrorReason)
	return err
}

const recordUpstreamStatus = `-- name: RecordUpstreamStatus :exec
UPDATE upstream_health_sources
SET last_status = $3, last_degraded = $4, last_checked_at = now(),
    last_error_reason = NULL, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type RecordUpstreamStatusParams struct {
	OrgID        string
	ID           string
	LastStatus   pgtype.Text
	LastDegraded bool
}

func (q *Queries) RecordUpstreamStatus(ctx context.Context, arg RecordUpstreamStatusParams) error {
	_, err := q.db.Exec(ctx, recordUpstreamStatus,
		arg.OrgID,
		arg.ID,
		arg.LastStatus,
		arg.LastDegraded,
	)
	return err
}

const resumeWorkflowsForUpstream = `-- name: ResumeWorkflowsForUpstream :many
UPDATE workflows
SET status = 'active', paused_reason = NULL
WHERE org_id = $1 AND id = ANY($2::text[]) AND status = 'paused_upstream_degraded'
RETURNING id
`

type ResumeWorkflowsForUpstreamParams struct {
	OrgID   string
	Column2 []string
}

func (q *Queries) ResumeWorkflowsForUpstream(ctx context.Context, arg ResumeWorkflowsForUpstreamParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resumeWorkflowsForUpstream, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredentialSecretVersion = `-- name: RevokeCredentialSecretVersion :exec
UPDATE credential_secret_versions SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeCredentialSecretVersionParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RevokeCredentialSecretVersion(ctx context.Context, arg RevokeCredentialSecretVersionParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialSecretVersion, arg.ID, arg.OrgID)
	return err
}

const rotateCredentialSecretRefCAS = `-- name: RotateCredentialSecretRefCAS :one
UPDATE credentials SET secret_ref = $3, updated_at = now()
WHERE org_id = $1 AND name = $2 AND updated_at = $4
RETURNING updated_at
`

type RotateCredentialSecretRefCASParams struct {
	OrgID        string
	Name         string
	NewSecretRef string
	IfMatch      time.Time
}

func (q *Queries) RotateCredentialSecretRefCAS(ctx context.Context, arg RotateCredentialSecretRefCASParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, rotateCredentialSecretRefCAS,
		arg.OrgID,
		arg.Name,
		arg.NewSecretRef,
		arg.IfMatch,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const setCredentialExpiry = `-- name: SetCredentialExpiry :one
UPDATE credentials SET expires_at = $3, updated_at = now()
WHERE org_id = $1 AND name = $2
  AND ($4::timestamptz IS NULL OR updated_at = $4)
RETURNING updated_at
`

type SetCredentialExpiryParams struct {
	OrgID     string
	Name      string
	ExpiresAt *time.Time
	IfMatch   *time.Time
}

func (q *Queries) SetCredentialExpiry(ctx context.Context, arg SetCredentialExpiryParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, setCredentialExpiry,
		arg.OrgID,
		arg.Name,
		arg.ExpiresAt,
		arg.IfMatch,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const setMcpConnectionStatus = `-- name: SetMcpConnectionStatus :exec
UPDATE mcp_connections
SET status = $3, status_reason = $4, last_discovery_at = $5, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type SetMcpConnectionStatusParams struct {
	OrgID           string
	ID              string
	Status          string
	StatusReason    pgtype.Text
	LastDiscoveryAt *time.Time
}

func (q *Queries) SetMcpConnectionStatus(ctx context.Context, arg SetMcpConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, setMcpConnectionStatus,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.StatusReason,
		arg.LastDiscoveryAt,
	)
	return err
}

const updateCredentialSecretRef = `-- name: UpdateCredentialSecretRef :exec
UPDATE credentials SET secret_ref = $3, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type UpdateCredentialSecretRefParams struct {
	OrgID     string
	ID        string
	SecretRef string
}

func (q *Queries) UpdateCredentialSecretRef(ctx context.Context, arg UpdateCredentialSecretRefParams) error {
	_, err := q.db.Exec(ctx, updateCredentialSecretRef, arg.OrgID, arg.ID, arg.SecretRef)
	return err
}

const updateMcpToolFlags = `-- name: UpdateMcpToolFlags :one
UPDATE mcp_tool_descriptors
SET enabled = $3, write_side = $4, rate_limit_per_min = $5, expose_to_ai = $6, updated_at = now()
WHERE connection_id = $1 AND name = $2
RETURNING id, connection_id, name, description, input_schema, write_side, enabled, rate_limit_per_min, expose_to_ai, created_at, updated_at
`

type UpdateMcpToolFlagsParams struct {
	ConnectionID    string
	Name            string
	Enabled         bool
	WriteSide       bool
	RateLimitPerMin pgtype.Int4
	ExposeToAi      bool
}

func (q *Queries) UpdateMcpToolFlags(ctx context.Context, arg UpdateMcpToolFlagsParams) (McpToolDescriptor, error) {
	row := q.db.QueryRow(ctx, updateMcpToolFlags,
		arg.ConnectionID,
		arg.Name,
		arg.Enabled,
		arg.WriteSide,
		arg.RateLimitPerMin,
		arg.ExposeToAi,
	)
	var i McpToolDescriptor
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.WriteSide,
		&i.Enabled,
		&i.RateLimitPerMin,
		&i.ExposeToAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSlackInteractionConnection = `-- name: UpdateSlackInteractionConnection :execrows
UPDATE slack_interaction_connections
SET name = $3, team_id = $4, signing_credential_name = $5, user_mappings = $6,
    enabled = $7, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type UpdateSlackInteractionConnectionParams struct {
	OrgID                 string
	ID                    string
	Name                  string
	TeamID                string
	SigningCredentialName string
	UserMappings          json.RawMessage
	Enabled               bool
}

func (q *Queries) UpdateSlackInteractionConnection(ctx context.Context, arg UpdateSlackInteractionConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSlackInteractionConnection,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.TeamID,
		arg.SigningCredentialName,
		arg.UserMappings,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUpstreamHealthSource = `-- name: UpdateUpstreamHealthSource :one
UPDATE upstream_health_sources
SET name = $3, kind = $4, url = $5, expected_components = $6,
    check_interval_seconds = $7, enabled = $8, updated_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, kind, url, expected_components, check_interval_seconds, enabled, last_status, last_degraded, last_checked_at, last_error_reason, created_by, created_at, updated_at
`

type UpdateUpstreamHealthSourceParams struct {
	OrgID                string
	ID                   string
	Name                 string
	Kind                 string
	Url                  string
	ExpectedComponents   json.RawMessage
	CheckIntervalSeconds int32
	Enabled              bool
}

func (q *Queries) UpdateUpstreamHealthSource(ctx context.Context, arg UpdateUpstreamHealthSourceParams) (UpstreamHealthSource, error) {
	row := q.db.QueryRow(ctx, updateUpstreamHealthSource,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Url,
		arg.ExpectedComponents,
		arg.CheckIntervalSeconds,
		arg.Enabled,
	)
	var i UpstreamHealthSource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.ExpectedComponents,
		&i.CheckIntervalSeconds,
		&i.Enabled,
		&i.LastStatus,
		&i.LastDegraded,
		&i.LastCheckedAt,
		&i.LastErrorReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMcpToolDescriptor = `-- name: UpsertMcpToolDescriptor :exec
INSERT INTO mcp_tool_descriptors (id, connection_id, name, description, input_schema, write_side, enabled, rate_limit_per_min)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (connection_id, name) DO UPDATE SET
  description = EXCLUDED.description,
  input_schema = EXCLUDED.input_schema,
  updated_at = now()
`

type UpsertMcpToolDescriptorParams struct {
	ID              string
	ConnectionID    string
	Name            string
	Description     pgtype.Text
	InputSchema     json.RawMessage
	WriteSide       bool
	Enabled         bool
	RateLimitPerMin pgtype.Int4
}

func (q *Queries) UpsertMcpToolDescriptor(ctx context.Context, arg UpsertMcpToolDescriptorParams) error {
	_, err := q.db.Exec(ctx, upsertMcpToolDescriptor,
		arg.ID,
		arg.ConnectionID,
		arg.Name,
		arg.Description,
		arg.InputSchema,
		arg.WriteSide,
		arg.Enabled,
		arg.RateLimitPerMin,
	)
	return err
}
