// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertDispatch struct {
	ID             string
	OrgID          string
	PolicyID       string
	DedupeKey      string
	DispatchedAt   time.Time
	Outcome        string
	ChannelResults json.RawMessage
	TriggerPayload json.RawMessage
}

type AlertPolicy struct {
	ID              string
	OrgID           string
	Name            string
	Trigger         string
	Parameters      json.RawMessage
	Channels        json.RawMessage
	CooldownSeconds int32
	Enabled         bool
	CreatedBy       pgtype.Text
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AuditLog struct {
	ID         string
	OrgID      string
	UserID     pgtype.Text
	Action     string
	TargetType pgtype.Text
	TargetID   pgtype.Text
	Metadata   json.RawMessage
	CreatedAt  *time.Time
	HoldUntil  *time.Time
}

type AuthSession struct {
	ID        string
	UserID    string
	Email     string
	OrgID     string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type AutoHealingRun struct {
	ID                      string
	OrgID                   string
	DeadLetterID            string
	Signature               string
	Status                  string
	ProposedPatchJson       json.RawMessage
	ApproachLabel           pgtype.Text
	Confidence              pgtype.Int4
	ValidationRunID         pgtype.Text
	ValidationSignature     pgtype.Text
	DecisionActor           pgtype.Text
	DeclineReason           pgtype.Text
	LoopAttemptCount        int32
	Metadata                json.RawMessage
	CreatedAt               time.Time
	UpdatedAt               time.Time
	PublicationReceipt      pgtype.Text
	PublicationRepairAfter  *time.Time
	PublicationAttempts     int32
	ValidationEvidenceLevel pgtype.Text
}

type ConfidenceCalibration struct {
	ID             string
	OrgID          string
	ApproachLabel  string
	AcceptRate     float32
	SampleSize     int32
	CurveSlope     float32
	CurveIntercept float32
	LastComputedAt time.Time
}

type Credential struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	SecretRef string
	Metadata  json.RawMessage
	CreatedBy pgtype.Text
	CreatedAt *time.Time
	UpdatedAt time.Time
	ExpiresAt *time.Time
}

type CredentialSecretVersion struct {
	ID           string
	OrgID        string
	CredentialID string
	Version      int32
	Ciphertext   string
	DataNonce    string
	DataTag      string
	WrappedKey   string
	WrapNonce    string
	WrapTag      string
	KeyVersion   int32
	CreatedBy    pgtype.Text
	CreatedAt    time.Time
	RevokedAt    *time.Time
}

type DeadLetter struct {
	ID               string
	OrgID            string
	RunID            string
	NodeID           string
	Attempt          int32
	WorkflowJson     json.RawMessage
	NodeJson         json.RawMessage
	ErrorJson        json.RawMessage
	Status           string
	ReplayedAt       *time.Time
	CreatedAt        *time.Time
	ReplayClaimToken pgtype.Text
	ReplayClaimedAt  *time.Time
	ReplayMode       pgtype.Text
}

type EvalDataset struct {
	ID            string
	OrgID         string
	Name          string
	Description   string
	WorkflowID    pgtype.Text
	ExampleCount  int32
	RetentionDays pgtype.Int4
	CreatedBy     pgtype.Text
	CreatedAt     time.Time
}

type EvalExample struct {
	ID                    string
	OrgID                 string
	DatasetID             string
	SourceFeedbackID      string
	WorkflowID            pgtype.Text
	DeadLetterID          pgtype.Text
	FailureSignature      string
	InputContext          string
	ExpectedApproachLabel string
	Accepted              bool
	SuggestionMode        string
	CreatedAt             time.Time
}

type Experiment struct {
	ID            string
	OrgID         string
	Name          string
	Kind          string
	ControlRef    string
	CandidateRef  string
	EvalDatasetID string
	ScorerKind    string
	Status        string
	SummaryJson   json.RawMessage
	CreatedBy     pgtype.Text
	CreatedAt     time.Time
	CompletedAt   *time.Time
}

type ExternalRecoveryCase struct {
	ID                  string
	OrgID               string
	ConnectionID        string
	SubjectKey          string
	SubjectKind         string
	ExternalWorkflowID  string
	ExternalRunID       string
	ExternalStepID      pgtype.Text
	State               string
	FailureSnapshotJson json.RawMessage
	EvidenceJson        json.RawMessage
	FirstDetectedAt     time.Time
	LastObservedAt      time.Time
	ObservedRecoveredAt *time.Time
	LastSequence        int64
	LastEventID         string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ExternalRun struct {
	ID                 string
	OrgID              string
	ConnectionID       string
	ExternalWorkflowID string
	ExternalRunID      string
	Status             string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	SnapshotJson       json.RawMessage
	EvidenceJson       json.RawMessage
	LastSequence       int64
	LastEventID        pgtype.Text
	LastObservedAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ExternalRunStep struct {
	ID                 string
	OrgID              string
	ConnectionID       string
	ExternalWorkflowID string
	ExternalRunID      string
	ExternalStepID     string
	Name               string
	Status             string
	Attempt            int32
	StartedAt          *time.Time
	CompletedAt        *time.Time
	SnapshotJson       json.RawMessage
	EvidenceJson       json.RawMessage
	LastSequence       int64
	LastEventID        pgtype.Text
	LastObservedAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ExternalRuntimeConnection struct {
	ID                    string
	OrgID                 string
	Name                  string
	RuntimeKey            string
	SigningCredentialName string
	Enabled               bool
	CreatedBy             string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type ExternalRuntimeEvent struct {
	ID              string
	OrgID           string
	ConnectionID    string
	EventID         string
	Source          string
	EventType       string
	Subject         pgtype.Text
	EventTime       time.Time
	Sequence        int64
	PayloadJson     json.RawMessage
	ProjectionState string
	ReceivedAt      time.Time
}

type ExternalWorkflow struct {
	ID                 string
	OrgID              string
	ConnectionID       string
	ExternalWorkflowID string
	Name               string
	Version            pgtype.Text
	SnapshotJson       json.RawMessage
	EvidenceJson       json.RawMessage
	LastSequence       int64
	LastEventID        pgtype.Text
	LastObservedAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InstalledPlugin struct {
	ID          string
	OrgID       string
	PluginID    string
	ConfigJson  json.RawMessage
	InstalledBy pgtype.Text
	CreatedAt   *time.Time
}

type Invitation struct {
	ID         string
	OrgID      string
	Email      string
	Role       string
	InvitedBy  pgtype.Text
	Status     string
	AcceptedAt *time.Time
	CreatedAt  *time.Time
}

type JanuslySchemaVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type McpConnection struct {
	ID              string
	OrgID           string
	Alias           string
	Transport       string
	Command         pgtype.Text
	Args            json.RawMessage
	Url             pgtype.Text
	EnvRefs         json.RawMessage
	Enabled         bool
	Status          string
	StatusReason    pgtype.Text
	ExposeToAi      bool
	LastDiscoveryAt *time.Time
	CreatedBy       pgtype.Text
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

type McpToolDescriptor struct {
	ID              string
	ConnectionID    string
	Name            string
	Description     pgtype.Text
	InputSchema     json.RawMessage
	WriteSide       bool
	Enabled         bool
	RateLimitPerMin pgtype.Int4
	ExposeToAi      bool
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

type MemoryEntry struct {
	ID                 string
	OrgID              string
	WorkflowID         pgtype.Text
	RunID              pgtype.Text
	Kind               string
	Content            string
	Embedding          interface{}
	EmbeddingProvider  string
	EmbeddingModel     string
	EmbeddingDimension int32
	Metadata           json.RawMessage
	CreatedAt          time.Time
	RetainUntil        time.Time
	HoldUntil          *time.Time
}

type OnboardingProgress struct {
	ID          string
	OrgID       string
	UserID      string
	Step        string
	Status      string
	SkippedAt   *time.Time
	CompletedAt *time.Time
	RestartedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrgConfig struct {
	ID          string
	OrgID       string
	Key         string
	ValueJson   json.RawMessage
	Category    string
	Description string
	ValueType   string
	Source      string
	CreatedBy   pgtype.Text
	UpdatedBy   pgtype.Text
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type OrgDigestState struct {
	OrgID      string
	LastSentAt time.Time
}

type OrgMember struct {
	ID        string
	OrgID     string
	UserID    string
	Email     pgtype.Text
	Role      string
	InvitedBy pgtype.Text
	CreatedAt *time.Time
}

type OrgRole struct {
	ID                 string
	OrgID              string
	Name               string
	InheritsFrom       string
	Description        pgtype.Text
	IsBuiltin          bool
	GrantedPermissions json.RawMessage
	CreatedBy          pgtype.Text
	UpdatedBy          pgtype.Text
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
}

type Organization struct {
	ID                   string
	Name                 string
	Plan                 string
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	CreatedAt            *time.Time
}

type Prompt struct {
	ID              string
	OrgID           string
	Name            string
	Description     pgtype.Text
	PinnedVersionID pgtype.Text
	CreatedBy       pgtype.Text
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

type PromptVersion struct {
	ID           string
	OrgID        string
	PromptID     string
	Version      int32
	TemplateText string
	Variables    json.RawMessage
	Status       string
	CreatedBy    pgtype.Text
	CreatedAt    *time.Time
}

type RateLimitWindow struct {
	Name        string
	Key         string
	WindowStart time.Time
	Count       int32
	ExpiresAt   time.Time
}

type RecoveryCase struct {
	ID                string
	OrgID             string
	RunID             string
	WorkflowID        pgtype.Text
	WorkflowVersionID string
	Source            string
	DetectorID        string
	SourceNodeID      string
	DetectorKind      string
	Action            string
	Message           string
	DetailsJson       json.RawMessage
	State             string
	CreatedBy         pgtype.Text
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ResolvedAt        *time.Time
}

type RecoveryCaseTransition struct {
	ID           string
	OrgID        string
	CaseID       string
	FromState    string
	ToState      string
	ActorKind    string
	ActorID      pgtype.Text
	EvidenceJson json.RawMessage
	Reason       pgtype.Text
	OccurredAt   time.Time
}

type RecoveryFeedback struct {
	ID             string
	OrgID          string
	UserID         pgtype.Text
	DeadLetterID   string
	WorkflowID     string
	SuggestionMode string
	ApproachLabel  string
	Accepted       bool
	RawConfidence  pgtype.Int4
	Comment        pgtype.Text
	EvalConsent    bool
	CreatedAt      *time.Time
	HoldUntil      *time.Time
}

type RecoveryFeedbackHealth struct {
	ID                  string
	OrgID               string
	WorkflowID          string
	ApproachLabel       string
	FeedbackLastSeen    time.Time
	AcceptedFixLastSeen *time.Time
}

type RecoveryImpactEvent struct {
	DeadLetterID    string
	OrgID           string
	RunID           string
	NodeID          string
	UserID          pgtype.Text
	RecoveredAt     time.Time
	DowntimeEndedMs int64
}

type RecoveryImpactRollup struct {
	OrgID            string
	TotalRecovered   int32
	DowntimeEndedMs  int64
	FirstRecoveredAt *time.Time
	UpdatedAt        time.Time
}

type RecoveryItem struct {
	ID               string
	OrgID            string
	DeadLetterID     string
	WorkflowID       pgtype.Text
	Owner            pgtype.Text
	Severity         string
	Status           string
	SlaTargetAt      time.Time
	ResolutionReason pgtype.Text
	ResolvedBy       pgtype.Text
	ResolvedAt       *time.Time
	Comments         json.RawMessage
	ErrorSignature   pgtype.Text
	OccurrenceCount  int32
	FirstOccurredAt  time.Time
	LastOccurredAt   time.Time
	CreatedBy        pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FirstActionAt    *time.Time
}

type RecoveryItemChild struct {
	ID             string
	OrgID          string
	RecoveryItemID string
	DeadLetterID   string
	OccurredAt     time.Time
}

type RecoveryItemHandoff struct {
	ID                string
	OrgID             string
	RecoveryItemID    string
	Destination       string
	CredentialName    string
	ExternalID        pgtype.Text
	ExternalUrl       pgtype.Text
	IdempotencyKey    string
	LastOutcome       string
	LastStatusCode    pgtype.Int4
	LastError         pgtype.Text
	LastLatencyMs     pgtype.Int4
	DispatchCount     int32
	FirstDispatchedAt time.Time
	LastDispatchedAt  time.Time
	CreatedBy         pgtype.Text
}

type RecoveryPlaybook struct {
	ID                         string
	OrgID                      string
	WorkflowID                 pgtype.Text
	Signature                  string
	Version                    int32
	Status                     string
	Title                      string
	InstructionsMarkdown       string
	EvidenceRequirementsJson   json.RawMessage
	SourceWorkflowVersionID    string
	ApproachLabel              string
	SuccessfulUses             int32
	Regressions                int32
	LastValidatedAt            *time.Time
	LastValidationRunID        pgtype.Text
	LastAppliedValidationRunID pgtype.Text
	ActivatedAt                *time.Time
	RetiredAt                  *time.Time
	CreatedBy                  pgtype.Text
	UpdatedBy                  pgtype.Text
	CreatedAt                  *time.Time
	UpdatedAt                  *time.Time
}

type ReplayCampaign struct {
	ID               string
	OrgID            string
	Name             string
	ClusterSignature string
	FilterJson       json.RawMessage
	PacingMs         int32
	Status           string
	TotalCount       int32
	ReplayedCount    int32
	FailedCount      int32
	CancelledCount   int32
	CreatedBy        string
	CancelledBy      pgtype.Text
	NextDispatchAt   time.Time
	StartedAt        time.Time
	CompletedAt      *time.Time
	CancelledAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ReplayCampaignItem struct {
	ID           string
	OrgID        string
	CampaignID   string
	DeadLetterID string
	Position     int32
	Status       string
	AttemptCount int32
	ClaimToken   pgtype.Text
	ClaimedAt    *time.Time
	Error        pgtype.Text
	CompletedAt  *time.Time
	CreatedAt    time.Time
}

type RoutingStat struct {
	ID           string
	OrgID        string
	NodeID       string
	Pulls        int32
	Value        float32
	MeanReward   float32
	SuccessCount int32
	FailureCount int32
	UpdatedAt    *time.Time
}

type Run struct {
	ID                                   string
	OrgID                                string
	WorkflowVersionID                    string
	Status                               string
	InputJson                            json.RawMessage
	OutputJson                           json.RawMessage
	ParentRunID                          pgtype.Text
	ParentNodeID                         pgtype.Text
	TraceID                              pgtype.Text
	ReplayMode                           pgtype.Text
	CreatedBy                            pgtype.Text
	CreatedAt                            *time.Time
	RecoveryPlaybookValidationRecordedAt *time.Time
	RecoveryPlaybookAppliedRecordedAt    *time.Time
	ParentLinkKind                       pgtype.Text
	ParentNotificationAfter              *time.Time
	WorkflowRolloutID                    pgtype.Text
	WorkflowRolloutVariant               pgtype.Text
	ValidationEvidenceLevel              pgtype.Text
	OutcomeStatus                        pgtype.Text
	SemanticViolationCount               int32
}

type RunEvent struct {
	ID        string
	RunID     string
	NodeID    pgtype.Text
	Type      string
	Payload   json.RawMessage
	CreatedAt *time.Time
	HoldUntil *time.Time
}

type RunNode struct {
	ID                          string
	RunID                       string
	NodeID                      string
	Status                      string
	StateJson                   json.RawMessage
	Attempts                    pgtype.Int4
	StartedAt                   *time.Time
	FinishedAt                  *time.Time
	ErrorJson                   json.RawMessage
	RecoveryDeadLetterID        pgtype.Text
	RecoveryRequestedBy         pgtype.Text
	RecoveryClaimToken          pgtype.Text
	RecoveryPlaybookID          pgtype.Text
	RecoveryValidationRunID     pgtype.Text
	WaitingRepairAfter          *time.Time
	QueuePublicationRepairAfter *time.Time
	QueuePublicationGeneration  int32
}

type RunStartIdempotency struct {
	OrgID          string
	IdempotencyKey string
	RunID          string
	CreatedAt      time.Time
}

type RunWakeup struct {
	RunNodeID string
	WakeAt    time.Time
	Reason    string
}

type ScheduleEntry struct {
	ID                string
	OrgID             string
	WorkflowID        string
	WorkflowVersionID string
	NodeID            string
	CronExpression    string
	Enabled           bool
	LastRunAt         *time.Time
	LastRunID         pgtype.Text
	CreatedBy         pgtype.Text
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
	NextFireAt        *time.Time
}

type ScimDirectory struct {
	ID                  string
	OrgID               string
	ProviderDirectoryID string
	DirectoryType       pgtype.Text
	DefaultRole         string
	Status              string
	LastSyncedAt        *time.Time
	CreatedAt           *time.Time
	UpdatedAt           *time.Time
}

type ScimGroupRoleMapping struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
	Role            string
	CreatedBy       pgtype.Text
	UpdatedBy       pgtype.Text
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

type ScimGroupState struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderGroupID string
	Name            string
	LastSyncedAt    *time.Time
}

type ScimProcessedEvent struct {
	EventID         string
	OrgID           string
	ScimDirectoryID string
	EventType       string
	ProcessedAt     *time.Time
}

type ScimUserGroup struct {
	ID              string
	OrgID           string
	ScimDirectoryID string
	ProviderUserID  string
	ProviderGroupID string
	AddedAt         *time.Time
}

type ScimUserState struct {
	ID                 string
	OrgID              string
	ScimDirectoryID    string
	ProviderUserID     string
	Email              string
	FirstName          pgtype.Text
	LastName           pgtype.Text
	Active             bool
	LastEventID        pgtype.Text
	LastEventTimestamp *time.Time
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
}

type SlackInteractionConnection struct {
	ID                    string
	OrgID                 string
	Name                  string
	TeamID                string
	SigningCredentialName string
	UserMappings          json.RawMessage
	Enabled               bool
	CreatedBy             string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type SlackInteractionReceipt struct {
	ID           string
	OrgID        string
	ConnectionID string
	CreatedAt    time.Time
}

type Snippet struct {
	ID          string
	OrgID       string
	Name        string
	Description string
	Category    string
	Tags        json.RawMessage
	Builtin     bool
	NodesJson   json.RawMessage
	EdgesJson   json.RawMessage
	EntryNodeID pgtype.Text
	CreatedBy   pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SsoConnection struct {
	ID                   string
	OrgID                string
	Provider             string
	ProviderConnectionID string
	Status               string
	EnforcedSso          bool
	ConfigJson           json.RawMessage
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
}

type SsoStateNonce struct {
	ID        string
	OrgID     string
	Nonce     string
	ExpiresAt time.Time
	CreatedAt *time.Time
}

type TriggerEvent struct {
	ID                     string
	OrgID                  string
	TriggerType            string
	WorkflowID             pgtype.Text
	WorkflowVersionID      string
	NodeID                 string
	Status                 string
	RunID                  pgtype.Text
	DedupeKey              pgtype.Text
	PayloadJson            json.RawMessage
	SkippedReason          pgtype.Text
	CreatedAt              *time.Time
	BackfillClaimToken     pgtype.Text
	BackfillClaimedAt      *time.Time
	WorkflowRolloutID      pgtype.Text
	WorkflowRolloutVariant pgtype.Text
}

type UpstreamHealthSource struct {
	ID                   string
	OrgID                string
	Name                 string
	Kind                 string
	Url                  string
	ExpectedComponents   json.RawMessage
	CheckIntervalSeconds int32
	Enabled              bool
	LastStatus           pgtype.Text
	LastDegraded         bool
	LastCheckedAt        *time.Time
	LastErrorReason      pgtype.Text
	CreatedBy            pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type UsageEvent struct {
	ID        string
	OrgID     string
	UserID    pgtype.Text
	RunID     pgtype.Text
	Metric    string
	Quantity  int32
	Metadata  json.RawMessage
	CreatedAt *time.Time
	HoldUntil *time.Time
}

type User struct {
	ID        string
	Email     pgtype.Text
	Name      pgtype.Text
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type VerifiedDomain struct {
	ID          string
	OrgID       string
	Domain      string
	DefaultRole string
	CreatedAt   *time.Time
}

type WorkerInstance struct {
	InstanceID        string
	StartedAt         time.Time
	LastSeenAt        time.Time
	WorkerConcurrency int32
	BuildCommit       pgtype.Text
}

type Workflow struct {
	ID           string
	OrgID        string
	Name         string
	Status       string
	PausedReason pgtype.Text
	CreatedBy    pgtype.Text
	CreatedAt    *time.Time
	DeletedAt    *time.Time
}

type WorkflowBudget struct {
	ID          string
	OrgID       string
	WorkflowID  string
	MonthlyUsd  float32
	WarnPercent int32
	Policy      string
	UpdatedBy   pgtype.Text
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type WorkflowImprovement struct {
	ID            string
	OrgID         string
	WorkflowID    string
	BaseVersion   pgtype.Int4
	NewVersion    pgtype.Int4
	Action        json.RawMessage
	Reason        pgtype.Text
	BeforeMetrics json.RawMessage
	AfterMetrics  json.RawMessage
	Confidence    float32
	Status        string
	CreatedAt     *time.Time
}

type WorkflowInputPreset struct {
	ID         string
	OrgID      string
	WorkflowID string
	Name       string
	InputJson  json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type WorkflowMetadatum struct {
	ID                 string
	OrgID              string
	WorkflowID         string
	Owners             json.RawMessage
	RunbookMarkdown    pgtype.Text
	Description        pgtype.Text
	Tags               json.RawMessage
	SlackChannel       pgtype.Text
	LinearProject      pgtype.Text
	SeverityDefault    pgtype.Text
	CreatedBy          pgtype.Text
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Folder             pgtype.Text
	AiGuidanceMarkdown pgtype.Text
}

type WorkflowRecoveryQualification struct {
	ID                 string
	OrgID              string
	WorkflowID         string
	BaselineVersionID  string
	CandidateVersionID string
	DatasetVersion     string
	DatasetDigest      string
	Mode               string
	Status             string
	SummaryJson        json.RawMessage
	CreatedBy          string
	CreatedAt          time.Time
}

type WorkflowRollout struct {
	ID                        string
	OrgID                     string
	WorkflowID                string
	BaselineVersionID         string
	CanaryVersionID           string
	TrafficPercent            int32
	MinimumSampleSize         int32
	MinimumSuccessRatePercent int32
	Status                    string
	BaselineSucceeded         int32
	BaselineFailed            int32
	CanarySucceeded           int32
	CanaryFailed              int32
	RolledBackReason          pgtype.Text
	CreatedBy                 string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	EndedAt                   *time.Time
	LastOutcomeAt             *time.Time
}

type WorkflowRolloutOutcome struct {
	RunID      string
	OrgID      string
	RolloutID  string
	WorkflowID string
	Variant    string
	Status     string
	CreatedAt  time.Time
}

type WorkflowStatusPage struct {
	OrgID      string
	WorkflowID string
	Token      string
	CreatedAt  time.Time
}

type WorkflowVersion struct {
	ID                    string
	OrgID                 string
	WorkflowID            string
	Version               int32
	DagJson               json.RawMessage
	SloJson               json.RawMessage
	UpstreamHealthSources json.RawMessage
	CreatedBy             pgtype.Text
	CreatedAt             *time.Time
}
