// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSsoNonce = `-- name: ConsumeSsoNonce :one
DELETE FROM sso_state_nonces
WHERE org_id = $1 AND nonce = $2 AND expires_at > now()
RETURNING id
`

type ConsumeSsoNonceParams struct {
	OrgID string
	Nonce string
}

// DELETE ... RETURNING is the single-use claim: exactly one concurrent
// callback can consume a live nonce; expired rows never authorize a login.
func (q *Queries) ConsumeSsoNonce(ctx context.Context, arg ConsumeSsoNonceParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeSsoNonce, arg.OrgID, arg.Nonce)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createSsoConnection = `-- name: CreateSsoConnection :one
INSERT INTO sso_connections (
  id, org_id, provider, provider_connection_id, status, enforced_sso
) VALUES ($1, $2, $3, $4, 'active', $5)
RETURNING id, org_id, provider, provider_connection_id, status, enforced_sso,
          config_json, created_at, updated_at
`

type CreateSsoConnectionParams struct {
	ID                   string
	OrgID                string
	Provider             string
	ProviderConnectionID string
	EnforcedSso          bool
}

func (q *Queries) CreateSsoConnection(ctx context.Context, arg CreateSsoConnectionParams) (SsoConnection, error) {
	row := q.db.QueryRow(ctx, createSsoConnection,
		arg.ID,
		arg.OrgID,
		arg.Provider,
		arg.ProviderConnectionID,
		arg.EnforcedSso,
	)
	var i SsoConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ProviderConnectionID,
		&i.Status,
		&i.EnforcedSso,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSsoConnectionForOrg = `-- name: FindSsoConnectionForOrg :one

SELECT id, org_id, provider, provider_connection_id, status, enforced_sso,
       config_json, created_at, updated_at
FROM sso_connections
WHERE org_id = $1 AND provider = 'workos'
LIMIT 1
`

// WorkOS SSO connection metadata, one-time callback nonces, and the narrow
// three-key auth-policy read. Every tenant query carries org_id; rows remain
// orphan-tolerant by the repository-wide no-FK policy.
func (q *Queries) FindSsoConnectionForOrg(ctx context.Context, orgID string) (SsoConnection, error) {
	row := q.db.QueryRow(ctx, findSsoConnectionForOrg, orgID)
	var i SsoConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ProviderConnectionID,
		&i.Status,
		&i.EnforcedSso,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSsoConnectionByID = `-- name: GetSsoConnectionByID :one
SELECT id, org_id, provider, provider_connection_id, status, enforced_sso,
       config_json, created_at, updated_at
FROM sso_connections
WHERE id = $1 AND org_id = $2
`

type GetSsoConnectionByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetSsoConnectionByID(ctx context.Context, arg GetSsoConnectionByIDParams) (SsoConnection, error) {
	row := q.db.QueryRow(ctx, getSsoConnectionByID, arg.ID, arg.OrgID)
	var i SsoConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ProviderConnectionID,
		&i.Status,
		&i.EnforcedSso,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthPolicyConfigRows = `-- name: ListAuthPolicyConfigRows :many
SELECT key, value_json
FROM org_configs
WHERE org_id = $1
  AND key IN ('auth.allowedEmailDomains', 'auth.mfaRequired', 'auth.sessionTtlSeconds')
ORDER BY key
LIMIT 3
`

type ListAuthPolicyConfigRowsRow struct {
	Key       string
	ValueJson json.RawMessage
}

func (q *Queries) ListAuthPolicyConfigRows(ctx context.Context, orgID string) ([]ListAuthPolicyConfigRowsRow, error) {
	rows, err := q.db.Query(ctx, listAuthPolicyConfigRows, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthPolicyConfigRowsRow
	for rows.Next() {
		var i ListAuthPolicyConfigRowsRow
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSsoConnections = `-- name: ListSsoConnections :many
SELECT id, org_id, provider, provider_connection_id, status, enforced_sso,
       config_json, created_at, updated_at
FROM sso_connections
WHERE org_id = $1
ORDER BY provider, id
LIMIT 20
`

func (q *Queries) ListSsoConnections(ctx context.Context, orgID string) ([]SsoConnection, error) {
	rows, err := q.db.Query(ctx, listSsoConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoConnection
	for rows.Next() {
		var i SsoConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.ProviderConnectionID,
			&i.Status,
			&i.EnforcedSso,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSsoNonce = `-- name: RecordSsoNonce :exec
INSERT INTO sso_state_nonces (id, org_id, nonce, expires_at)
VALUES ($1, $2, $3, $4)
`

type RecordSsoNonceParams struct {
	ID        string
	OrgID     string
	Nonce     string
	ExpiresAt time.Time
}

func (q *Queries) RecordSsoNonce(ctx context.Context, arg RecordSsoNonceParams) error {
	_, err := q.db.Exec(ctx, recordSsoNonce,
		arg.ID,
		arg.OrgID,
		arg.Nonce,
		arg.ExpiresAt,
	)
	return err
}

const revokeSsoConnection = `-- name: RevokeSsoConnection :one
UPDATE sso_connections
SET status = 'revoked', updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, provider, provider_connection_id, status, enforced_sso,
          config_json, created_at, updated_at
`

type RevokeSsoConnectionParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RevokeSsoConnection(ctx context.Context, arg RevokeSsoConnectionParams) (SsoConnection, error) {
	row := q.db.QueryRow(ctx, revokeSsoConnection, arg.ID, arg.OrgID)
	var i SsoConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ProviderConnectionID,
		&i.Status,
		&i.EnforcedSso,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSsoConnection = `-- name: UpdateSsoConnection :one
UPDATE sso_connections
SET status = coalesce($1::text, status),
    enforced_sso = coalesce($2::boolean, enforced_sso),
    provider_connection_id = coalesce($3::text, provider_connection_id),
    updated_at = now()
WHERE id = $4 AND org_id = $5
RETURNING id, org_id, provider, provider_connection_id, status, enforced_sso,
          config_json, created_at, updated_at
`

type UpdateSsoConnectionParams struct {
	Status               pgtype.Text
	EnforcedSso          pgtype.Bool
	ProviderConnectionID pgtype.Text
	ID                   string
	OrgID                string
}

func (q *Queries) UpdateSsoConnection(ctx context.Context, arg UpdateSsoConnectionParams) (SsoConnection, error) {
	row := q.db.QueryRow(ctx, updateSsoConnection,
		arg.Status,
		arg.EnforcedSso,
		arg.ProviderConnectionID,
		arg.ID,
		arg.OrgID,
	)
	var i SsoConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ProviderConnectionID,
		&i.Status,
		&i.EnforcedSso,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSsoMembership = `-- name: UpsertSsoMembership :exec
INSERT INTO org_members (id, org_id, user_id, email, role, invited_by)
VALUES ($1, $2, $3, $4, 'viewer', NULL)
ON CONFLICT (org_id, user_id) DO UPDATE
SET email = EXCLUDED.email
`

type UpsertSsoMembershipParams struct {
	ID     string
	OrgID  string
	UserID string
	Email  pgtype.Text
}

// The WorkOS profile id is the durable membership key. First login
// provisions a viewer; a returning login refreshes the verified email
// but MUST NOT touch the role — overwriting it would silently demote
// members promoted via /members/role or SCIM (and could lock an org
// out of its only admin).
func (q *Queries) UpsertSsoMembership(ctx context.Context, arg UpsertSsoMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertSsoMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Email,
	)
	return err
}
