// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireWorkflowInputPresetLock = `-- name: AcquireWorkflowInputPresetLock :exec
SELECT pg_advisory_xact_lock(hashtextextended(
  $1::text || E'\x1f' || $2::text || E'\x1finput-presets', 0))
`

type AcquireWorkflowInputPresetLockParams struct {
	OrgID      string
	WorkflowID string
}

// Serialize the bounded read+upsert across processes. A row lock cannot
// protect the empty set, so the transaction takes one tenant/workflow-scoped
// advisory lock before checking the count.
func (q *Queries) AcquireWorkflowInputPresetLock(ctx context.Context, arg AcquireWorkflowInputPresetLockParams) error {
	_, err := q.db.Exec(ctx, acquireWorkflowInputPresetLock, arg.OrgID, arg.WorkflowID)
	return err
}

const addWorkflowTagBulk = `-- name: AddWorkflowTagBulk :execrows
INSERT INTO workflow_metadata (id, org_id, workflow_id, tags, created_by)
SELECT gen_random_uuid()::text, $1, workflow_id,
       jsonb_build_array($2::text), $3
FROM unnest($4::text[]) AS workflow_id
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  tags = CASE
    WHEN workflow_metadata.tags @> jsonb_build_array($2::text)
      THEN workflow_metadata.tags
    ELSE workflow_metadata.tags || jsonb_build_array($2::text)
  END,
  updated_at = now()
`

type AddWorkflowTagBulkParams struct {
	OrgID       string
	Tag         string
	CreatedBy   pgtype.Text
	WorkflowIds []string
}

func (q *Queries) AddWorkflowTagBulk(ctx context.Context, arg AddWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, addWorkflowTagBulk,
		arg.OrgID,
		arg.Tag,
		arg.CreatedBy,
		arg.WorkflowIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const autoRollbackRollout = `-- name: AutoRollbackRollout :one
UPDATE workflow_rollouts
SET status = 'rolled_back', rolled_back_reason = $2, ended_at = now(), updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type AutoRollbackRolloutParams struct {
	ID     string
	Reason pgtype.Text
}

func (q *Queries) AutoRollbackRollout(ctx context.Context, arg AutoRollbackRolloutParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, autoRollbackRollout, arg.ID, arg.Reason)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const cancelActiveWorkflowRollout = `-- name: CancelActiveWorkflowRollout :execrows
UPDATE workflow_rollouts
SET status = 'cancelled', rolled_back_reason = $3,
    ended_at = now(), updated_at = now()
WHERE org_id = $1 AND workflow_id = $2 AND status = 'active'
`

type CancelActiveWorkflowRolloutParams struct {
	OrgID      string
	WorkflowID string
	Reason     pgtype.Text
}

func (q *Queries) CancelActiveWorkflowRollout(ctx context.Context, arg CancelActiveWorkflowRolloutParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveWorkflowRollout, arg.OrgID, arg.WorkflowID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentWorkflowRunStatuses = `-- name: CountRecentWorkflowRunStatuses :many
SELECT r.status FROM runs r
LEFT JOIN workflow_versions v ON v.id = r.workflow_version_id AND v.org_id = r.org_id
WHERE r.org_id = $1
  AND COALESCE(v.workflow_id, r.workflow_version_id) = $2
  AND r.replay_mode IS NULL
  AND r.status IN ('succeeded', 'failed')
ORDER BY r.created_at DESC
LIMIT $3
`

type CountRecentWorkflowRunStatusesParams struct {
	OrgID      string
	WorkflowID string
	PageLimit  int32
}

func (q *Queries) CountRecentWorkflowRunStatuses(ctx context.Context, arg CountRecentWorkflowRunStatusesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, countRecentWorkflowRunStatuses, arg.OrgID, arg.WorkflowID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkflowInputPresets = `-- name: CountWorkflowInputPresets :one
SELECT count(*) FROM workflow_input_presets
WHERE org_id = $1 AND workflow_id = $2
`

type CountWorkflowInputPresetsParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) CountWorkflowInputPresets(ctx context.Context, arg CountWorkflowInputPresetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowInputPresets, arg.OrgID, arg.WorkflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowVersions = `-- name: CountWorkflowVersions :one
SELECT COALESCE(MAX(version), 0)::int FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
`

type CountWorkflowVersionsParams struct {
	WorkflowID string
	OrgID      string
}

func (q *Queries) CountWorkflowVersions(ctx context.Context, arg CountWorkflowVersionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkflowVersions, arg.WorkflowID, arg.OrgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkflowFolderBulk = `-- name: DeleteWorkflowFolderBulk :execrows
UPDATE workflow_metadata SET folder = NULL, updated_at = now()
WHERE org_id = $1 AND folder = $2
`

type DeleteWorkflowFolderBulkParams struct {
	OrgID  string
	Folder pgtype.Text
}

func (q *Queries) DeleteWorkflowFolderBulk(ctx context.Context, arg DeleteWorkflowFolderBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowFolderBulk, arg.OrgID, arg.Folder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowInputPreset = `-- name: DeleteWorkflowInputPreset :execrows
DELETE FROM workflow_input_presets
WHERE org_id = $1 AND workflow_id = $2 AND name = $3
`

type DeleteWorkflowInputPresetParams struct {
	OrgID      string
	WorkflowID string
	Name       string
}

func (q *Queries) DeleteWorkflowInputPreset(ctx context.Context, arg DeleteWorkflowInputPresetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowInputPreset, arg.OrgID, arg.WorkflowID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowStatusPage = `-- name: DeleteWorkflowStatusPage :execrows
DELETE FROM workflow_status_pages WHERE org_id = $1 AND workflow_id = $2
`

type DeleteWorkflowStatusPageParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) DeleteWorkflowStatusPage(ctx context.Context, arg DeleteWorkflowStatusPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowStatusPage, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowTagBulk = `-- name: DeleteWorkflowTagBulk :execrows
UPDATE workflow_metadata
SET tags = tags - $2::text, updated_at = now()
WHERE org_id = $1 AND tags ? $2::text
`

type DeleteWorkflowTagBulkParams struct {
	OrgID string
	Tag   string
}

func (q *Queries) DeleteWorkflowTagBulk(ctx context.Context, arg DeleteWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowTagBulk, arg.OrgID, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveWorkflowRollout = `-- name: FindActiveWorkflowRollout :one
SELECT id FROM workflow_rollouts WHERE org_id = $1 AND workflow_id = $2 AND status = 'active' LIMIT 1
`

type FindActiveWorkflowRolloutParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) FindActiveWorkflowRollout(ctx context.Context, arg FindActiveWorkflowRolloutParams) (string, error) {
	row := q.db.QueryRow(ctx, findActiveWorkflowRollout, arg.OrgID, arg.WorkflowID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findWorkflowRecoveryQualification = `-- name: FindWorkflowRecoveryQualification :one
SELECT id, org_id, workflow_id, baseline_version_id, candidate_version_id, dataset_version, dataset_digest, mode, status, summary_json, created_by, created_at FROM workflow_recovery_qualifications
WHERE org_id = $1 AND workflow_id = $2 AND baseline_version_id = $3
  AND candidate_version_id = $4 AND dataset_version = $5
ORDER BY created_at DESC, id DESC LIMIT 1
`

type FindWorkflowRecoveryQualificationParams struct {
	OrgID              string
	WorkflowID         string
	BaselineVersionID  string
	CandidateVersionID string
	DatasetVersion     string
}

func (q *Queries) FindWorkflowRecoveryQualification(ctx context.Context, arg FindWorkflowRecoveryQualificationParams) (WorkflowRecoveryQualification, error) {
	row := q.db.QueryRow(ctx, findWorkflowRecoveryQualification,
		arg.OrgID,
		arg.WorkflowID,
		arg.BaselineVersionID,
		arg.CandidateVersionID,
		arg.DatasetVersion,
	)
	var i WorkflowRecoveryQualification
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CandidateVersionID,
		&i.DatasetVersion,
		&i.DatasetDigest,
		&i.Mode,
		&i.Status,
		&i.SummaryJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findWorkflowStatusPageByTokenDigest = `-- name: FindWorkflowStatusPageByTokenDigest :one
SELECT sp.org_id, sp.workflow_id, w.name AS workflow_name
FROM workflow_status_pages sp
JOIN workflows w ON w.org_id = sp.org_id AND w.id = sp.workflow_id
WHERE sp.token_digest = $1 AND w.deleted_at IS NULL
`

type FindWorkflowStatusPageByTokenDigestRow struct {
	OrgID        string
	WorkflowID   string
	WorkflowName string
}

func (q *Queries) FindWorkflowStatusPageByTokenDigest(ctx context.Context, tokenDigest string) (FindWorkflowStatusPageByTokenDigestRow, error) {
	row := q.db.QueryRow(ctx, findWorkflowStatusPageByTokenDigest, tokenDigest)
	var i FindWorkflowStatusPageByTokenDigestRow
	err := row.Scan(&i.OrgID, &i.WorkflowID, &i.WorkflowName)
	return i, err
}

const finishWorkflowRolloutCAS = `-- name: FinishWorkflowRolloutCAS :one
UPDATE workflow_rollouts
SET status = $4,
    rolled_back_reason = CASE WHEN $4 = 'rolled_back' THEN $5 ELSE NULL END,
    ended_at = now(), updated_at = now()
WHERE id = $1 AND org_id = $2 AND workflow_id = $3 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type FinishWorkflowRolloutCASParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	NewStatus  string
	Reason     pgtype.Text
}

func (q *Queries) FinishWorkflowRolloutCAS(ctx context.Context, arg FinishWorkflowRolloutCASParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, finishWorkflowRolloutCAS,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.NewStatus,
		arg.Reason,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getActiveRolloutForOutcome = `-- name: GetActiveRolloutForOutcome :one
SELECT id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at FROM workflow_rollouts WHERE id = $1 AND org_id = $2 AND status = 'active'
`

type GetActiveRolloutForOutcomeParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetActiveRolloutForOutcome(ctx context.Context, arg GetActiveRolloutForOutcomeParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getActiveRolloutForOutcome, arg.ID, arg.OrgID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getLatestWorkflowHealthSnapshot = `-- name: GetLatestWorkflowHealthSnapshot :one
SELECT id, version, dag_json, slo_json
FROM workflow_versions
WHERE org_id = $1 AND workflow_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowHealthSnapshotParams struct {
	OrgID      string
	WorkflowID string
}

type GetLatestWorkflowHealthSnapshotRow struct {
	ID      string
	Version int32
	DagJson json.RawMessage
	SloJson json.RawMessage
}

func (q *Queries) GetLatestWorkflowHealthSnapshot(ctx context.Context, arg GetLatestWorkflowHealthSnapshotParams) (GetLatestWorkflowHealthSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowHealthSnapshot, arg.OrgID, arg.WorkflowID)
	var i GetLatestWorkflowHealthSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.DagJson,
		&i.SloJson,
	)
	return i, err
}

const getLatestWorkflowRolloutRow = `-- name: GetLatestWorkflowRolloutRow :one
SELECT wr.id, wr.org_id, wr.workflow_id, wr.baseline_version_id, wr.canary_version_id, wr.traffic_percent, wr.minimum_sample_size, wr.minimum_success_rate_percent, wr.status, wr.baseline_succeeded, wr.baseline_failed, wr.canary_succeeded, wr.canary_failed, wr.rolled_back_reason, wr.created_by, wr.created_at, wr.updated_at, wr.ended_at, wr.last_outcome_at FROM workflow_rollouts wr
JOIN workflows w ON w.id = wr.workflow_id AND w.org_id = wr.org_id
WHERE wr.org_id = $1 AND wr.workflow_id = $2 AND w.deleted_at IS NULL
ORDER BY CASE WHEN wr.status = 'active' THEN 0 ELSE 1 END, wr.created_at DESC, wr.id DESC
LIMIT 1
`

type GetLatestWorkflowRolloutRowParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetLatestWorkflowRolloutRow(ctx context.Context, arg GetLatestWorkflowRolloutRowParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowRolloutRow, arg.OrgID, arg.WorkflowID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getLatestWorkflowSlo = `-- name: GetLatestWorkflowSlo :one
SELECT slo_json FROM workflow_versions
WHERE org_id = $1 AND workflow_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowSloParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetLatestWorkflowSlo(ctx context.Context, arg GetLatestWorkflowSloParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowSlo, arg.OrgID, arg.WorkflowID)
	var slo_json json.RawMessage
	err := row.Scan(&slo_json)
	return slo_json, err
}

const getLatestWorkflowVersion = `-- name: GetLatestWorkflowVersion :one
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowVersionParams struct {
	WorkflowID string
	OrgID      string
}

type GetLatestWorkflowVersionRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) GetLatestWorkflowVersion(ctx context.Context, arg GetLatestWorkflowVersionParams) (GetLatestWorkflowVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersion, arg.WorkflowID, arg.OrgID)
	var i GetLatestWorkflowVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestWorkflowVersionReliability = `-- name: GetLatestWorkflowVersionReliability :one
SELECT version, slo_json, upstream_health_sources
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestWorkflowVersionReliabilityParams struct {
	WorkflowID string
	OrgID      string
}

type GetLatestWorkflowVersionReliabilityRow struct {
	Version               int32
	SloJson               json.RawMessage
	UpstreamHealthSources json.RawMessage
}

func (q *Queries) GetLatestWorkflowVersionReliability(ctx context.Context, arg GetLatestWorkflowVersionReliabilityParams) (GetLatestWorkflowVersionReliabilityRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersionReliability, arg.WorkflowID, arg.OrgID)
	var i GetLatestWorkflowVersionReliabilityRow
	err := row.Scan(&i.Version, &i.SloJson, &i.UpstreamHealthSources)
	return i, err
}

const getRunForRolloutOutcome = `-- name: GetRunForRolloutOutcome :one
SELECT org_id, status, replay_mode, workflow_rollout_id, workflow_rollout_variant, workflow_version_id
FROM runs WHERE id = $1
`

type GetRunForRolloutOutcomeRow struct {
	OrgID                  string
	Status                 string
	ReplayMode             pgtype.Text
	WorkflowRolloutID      pgtype.Text
	WorkflowRolloutVariant pgtype.Text
	WorkflowVersionID      string
}

func (q *Queries) GetRunForRolloutOutcome(ctx context.Context, id string) (GetRunForRolloutOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getRunForRolloutOutcome, id)
	var i GetRunForRolloutOutcomeRow
	err := row.Scan(
		&i.OrgID,
		&i.Status,
		&i.ReplayMode,
		&i.WorkflowRolloutID,
		&i.WorkflowRolloutVariant,
		&i.WorkflowVersionID,
	)
	return i, err
}

const getStatusPageLastSuccess = `-- name: GetStatusPageLastSuccess :one
SELECT max(r.created_at)::timestamptz AS last_success
FROM runs r
JOIN workflow_versions wv ON wv.id = r.workflow_version_id
WHERE r.org_id = $1 AND wv.workflow_id = $2 AND r.replay_mode IS NULL
  AND r.status = 'succeeded'
`

type GetStatusPageLastSuccessParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetStatusPageLastSuccess(ctx context.Context, arg GetStatusPageLastSuccessParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getStatusPageLastSuccess, arg.OrgID, arg.WorkflowID)
	var last_success time.Time
	err := row.Scan(&last_success)
	return last_success, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, org_id, name, status, paused_reason, created_by, created_at, deleted_at
FROM workflows
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.OrgID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.PausedReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowAiGuidance = `-- name: GetWorkflowAiGuidance :one
SELECT ai_guidance_markdown FROM workflow_metadata
WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowAiGuidanceParams struct {
	OrgID      string
	WorkflowID string
}

// Workflow-scope operator guidance for AI prompt composition.
func (q *Queries) GetWorkflowAiGuidance(ctx context.Context, arg GetWorkflowAiGuidanceParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWorkflowAiGuidance, arg.OrgID, arg.WorkflowID)
	var ai_guidance_markdown pgtype.Text
	err := row.Scan(&ai_guidance_markdown)
	return ai_guidance_markdown, err
}

const getWorkflowBreakerStatus = `-- name: GetWorkflowBreakerStatus :one
SELECT status FROM workflows
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetWorkflowBreakerStatusParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetWorkflowBreakerStatus(ctx context.Context, arg GetWorkflowBreakerStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkflowBreakerStatus, arg.OrgID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getWorkflowIngestState = `-- name: GetWorkflowIngestState :one
SELECT org_id, status, deleted_at FROM workflows WHERE id = $1
`

type GetWorkflowIngestStateRow struct {
	OrgID     string
	Status    string
	DeletedAt *time.Time
}

func (q *Queries) GetWorkflowIngestState(ctx context.Context, id string) (GetWorkflowIngestStateRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowIngestState, id)
	var i GetWorkflowIngestStateRow
	err := row.Scan(&i.OrgID, &i.Status, &i.DeletedAt)
	return i, err
}

const getWorkflowMetadata = `-- name: GetWorkflowMetadata :one
SELECT id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown FROM workflow_metadata WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowMetadataParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowMetadata(ctx context.Context, arg GetWorkflowMetadataParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, getWorkflowMetadata, arg.OrgID, arg.WorkflowID)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const getWorkflowOwnerState = `-- name: GetWorkflowOwnerState :one
SELECT org_id, deleted_at FROM workflows WHERE id = $1
`

type GetWorkflowOwnerStateRow struct {
	OrgID     string
	DeletedAt *time.Time
}

func (q *Queries) GetWorkflowOwnerState(ctx context.Context, id string) (GetWorkflowOwnerStateRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowOwnerState, id)
	var i GetWorkflowOwnerStateRow
	err := row.Scan(&i.OrgID, &i.DeletedAt)
	return i, err
}

const getWorkflowRolloutRow = `-- name: GetWorkflowRolloutRow :one
SELECT id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at FROM workflow_rollouts WHERE id = $1 AND org_id = $2 AND workflow_id = $3
`

type GetWorkflowRolloutRowParams struct {
	ID         string
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowRolloutRow(ctx context.Context, arg GetWorkflowRolloutRowParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, getWorkflowRolloutRow, arg.ID, arg.OrgID, arg.WorkflowID)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const getWorkflowSeverityDefault = `-- name: GetWorkflowSeverityDefault :one
SELECT severity_default FROM workflow_metadata WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowSeverityDefaultParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowSeverityDefault(ctx context.Context, arg GetWorkflowSeverityDefaultParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWorkflowSeverityDefault, arg.OrgID, arg.WorkflowID)
	var severity_default pgtype.Text
	err := row.Scan(&severity_default)
	return severity_default, err
}

const getWorkflowStatusPage = `-- name: GetWorkflowStatusPage :one
SELECT created_at FROM workflow_status_pages
WHERE org_id = $1 AND workflow_id = $2
`

type GetWorkflowStatusPageParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) GetWorkflowStatusPage(ctx context.Context, arg GetWorkflowStatusPageParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatusPage, arg.OrgID, arg.WorkflowID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getWorkflowVersionAnyWorkflow = `-- name: GetWorkflowVersionAnyWorkflow :one
SELECT id, org_id, workflow_id, version, dag_json FROM workflow_versions
WHERE id = $1 AND org_id = $2
`

type GetWorkflowVersionAnyWorkflowParams struct {
	ID    string
	OrgID string
}

type GetWorkflowVersionAnyWorkflowRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
}

func (q *Queries) GetWorkflowVersionAnyWorkflow(ctx context.Context, arg GetWorkflowVersionAnyWorkflowParams) (GetWorkflowVersionAnyWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionAnyWorkflow, arg.ID, arg.OrgID)
	var i GetWorkflowVersionAnyWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
	)
	return i, err
}

const getWorkflowVersionByID = `-- name: GetWorkflowVersionByID :one
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE id = $1 AND org_id = $2 AND workflow_id = $3
`

type GetWorkflowVersionByIDParams struct {
	ID         string
	OrgID      string
	WorkflowID string
}

type GetWorkflowVersionByIDRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

func (q *Queries) GetWorkflowVersionByID(ctx context.Context, arg GetWorkflowVersionByIDParams) (GetWorkflowVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByID, arg.ID, arg.OrgID, arg.WorkflowID)
	var i GetWorkflowVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Version,
		&i.DagJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowVersionByNumber = `-- name: GetWorkflowVersionByNumber :one
SELECT wv.id, wv.dag_json, wv.version
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.workflow_id = $1 AND wv.org_id = $2 AND wv.version = $3
  AND w.deleted_at IS NULL
`

type GetWorkflowVersionByNumberParams struct {
	WorkflowID string
	OrgID      string
	Version    int32
}

type GetWorkflowVersionByNumberRow struct {
	ID      string
	DagJson json.RawMessage
	Version int32
}

func (q *Queries) GetWorkflowVersionByNumber(ctx context.Context, arg GetWorkflowVersionByNumberParams) (GetWorkflowVersionByNumberRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByNumber, arg.WorkflowID, arg.OrgID, arg.Version)
	var i GetWorkflowVersionByNumberRow
	err := row.Scan(&i.ID, &i.DagJson, &i.Version)
	return i, err
}

const incrementRolloutCounters = `-- name: IncrementRolloutCounters :one
UPDATE workflow_rollouts SET
  baseline_succeeded = baseline_succeeded + $2,
  baseline_failed = baseline_failed + $3,
  canary_succeeded = canary_succeeded + $4,
  canary_failed = canary_failed + $5,
  last_outcome_at = now(), updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type IncrementRolloutCountersParams struct {
	ID                   string
	BaselineSucceededInc int32
	BaselineFailedInc    int32
	CanarySucceededInc   int32
	CanaryFailedInc      int32
}

func (q *Queries) IncrementRolloutCounters(ctx context.Context, arg IncrementRolloutCountersParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, incrementRolloutCounters,
		arg.ID,
		arg.BaselineSucceededInc,
		arg.BaselineFailedInc,
		arg.CanarySucceededInc,
		arg.CanaryFailedInc,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const insertWorkflow = `-- name: InsertWorkflow :exec

INSERT INTO workflows (id, org_id, name, created_by)
VALUES ($1, $2, $3, $4)
`

type InsertWorkflowParams struct {
	ID        string
	OrgID     string
	Name      string
	CreatedBy pgtype.Text
}

// Workflows, versions, trash, rollouts, tags/folders/metadata, health.
func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) error {
	_, err := q.db.Exec(ctx, insertWorkflow,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CreatedBy,
	)
	return err
}

const insertWorkflowRollout = `-- name: InsertWorkflowRollout :one
INSERT INTO workflow_rollouts (id, org_id, workflow_id, baseline_version_id, canary_version_id,
  traffic_percent, minimum_sample_size, minimum_success_rate_percent, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, workflow_id, baseline_version_id, canary_version_id, traffic_percent, minimum_sample_size, minimum_success_rate_percent, status, baseline_succeeded, baseline_failed, canary_succeeded, canary_failed, rolled_back_reason, created_by, created_at, updated_at, ended_at, last_outcome_at
`

type InsertWorkflowRolloutParams struct {
	ID                        string
	OrgID                     string
	WorkflowID                string
	BaselineVersionID         string
	CanaryVersionID           string
	TrafficPercent            int32
	MinimumSampleSize         int32
	MinimumSuccessRatePercent int32
	CreatedBy                 string
}

func (q *Queries) InsertWorkflowRollout(ctx context.Context, arg InsertWorkflowRolloutParams) (WorkflowRollout, error) {
	row := q.db.QueryRow(ctx, insertWorkflowRollout,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.BaselineVersionID,
		arg.CanaryVersionID,
		arg.TrafficPercent,
		arg.MinimumSampleSize,
		arg.MinimumSuccessRatePercent,
		arg.CreatedBy,
	)
	var i WorkflowRollout
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.BaselineVersionID,
		&i.CanaryVersionID,
		&i.TrafficPercent,
		&i.MinimumSampleSize,
		&i.MinimumSuccessRatePercent,
		&i.Status,
		&i.BaselineSucceeded,
		&i.BaselineFailed,
		&i.CanarySucceeded,
		&i.CanaryFailed,
		&i.RolledBackReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.LastOutcomeAt,
	)
	return i, err
}

const insertWorkflowRolloutOutcome = `-- name: InsertWorkflowRolloutOutcome :execrows
INSERT INTO workflow_rollout_outcomes (run_id, org_id, rollout_id, workflow_id, variant, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id) DO NOTHING
`

type InsertWorkflowRolloutOutcomeParams struct {
	RunID      string
	OrgID      string
	RolloutID  string
	WorkflowID string
	Variant    string
	Status     string
}

func (q *Queries) InsertWorkflowRolloutOutcome(ctx context.Context, arg InsertWorkflowRolloutOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWorkflowRolloutOutcome,
		arg.RunID,
		arg.OrgID,
		arg.RolloutID,
		arg.WorkflowID,
		arg.Variant,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWorkflowVersion = `-- name: InsertWorkflowVersion :exec
INSERT INTO workflow_versions (id, org_id, workflow_id, version, dag_json, created_by,
                               upstream_health_sources, slo_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWorkflowVersionParams struct {
	ID                    string
	OrgID                 string
	WorkflowID            string
	Version               int32
	DagJson               json.RawMessage
	CreatedBy             pgtype.Text
	UpstreamHealthSources json.RawMessage
	SloJson               json.RawMessage
}

func (q *Queries) InsertWorkflowVersion(ctx context.Context, arg InsertWorkflowVersionParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowVersion,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Version,
		arg.DagJson,
		arg.CreatedBy,
		arg.UpstreamHealthSources,
		arg.SloJson,
	)
	return err
}

const listAuthoringSubworkflowCapabilities = `-- name: ListAuthoringSubworkflowCapabilities :many
SELECT w.id, w.name, w.status, max(wv.version)::int AS latest_version
FROM workflows w
JOIN workflow_versions wv ON wv.workflow_id = w.id AND wv.org_id = w.org_id
WHERE w.org_id = $1 AND w.deleted_at IS NULL
GROUP BY w.id, w.name, w.status
ORDER BY w.name, w.id
LIMIT 201
`

type ListAuthoringSubworkflowCapabilitiesRow struct {
	ID            string
	Name          string
	Status        string
	LatestVersion int32
}

// Exact saved workflows eligible for subworkflow authoring. Unsaved,
// deleted and versionless workflows cannot be bound by a proposal.
func (q *Queries) ListAuthoringSubworkflowCapabilities(ctx context.Context, orgID string) ([]ListAuthoringSubworkflowCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listAuthoringSubworkflowCapabilities, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthoringSubworkflowCapabilitiesRow
	for rows.Next() {
		var i ListAuthoringSubworkflowCapabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedWorkflowRows = `-- name: ListDeletedWorkflowRows :many
SELECT w.id, w.org_id, w.name, w.created_by, w.created_at, w.status,
       w.paused_reason, w.deleted_at,
       (SELECT count(*) FROM runs r
        JOIN workflow_versions wv ON wv.id = r.workflow_version_id
        WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
          AND r.replay_mode IS NULL)::int AS run_count,
       COALESCE(last_run.status, '') AS last_run_status,
       COALESCE(m.tags, '[]'::jsonb) AS tags,
       m.folder,
       (SELECT count(*) FROM trigger_events te
        WHERE te.org_id = w.org_id AND te.workflow_id = w.id
          AND (te.status = 'buffered'
               OR (te.status = 'backfilling'
                   AND te.backfill_claimed_at < now() - interval '5 minutes')))::int
         AS buffered_trigger_count
FROM workflows w
LEFT JOIN workflow_metadata m ON m.org_id = w.org_id AND m.workflow_id = w.id
LEFT JOIN LATERAL (
  SELECT r.status FROM runs r
  JOIN workflow_versions wv ON wv.id = r.workflow_version_id
  WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
    AND r.replay_mode IS NULL
  ORDER BY r.created_at DESC, r.id DESC LIMIT 1
) last_run ON true
WHERE w.org_id = $1 AND w.deleted_at IS NOT NULL
  AND (w.deleted_at, w.id) < ($2::timestamptz, $3::text)
ORDER BY w.deleted_at DESC, w.id DESC
LIMIT $4
`

type ListDeletedWorkflowRowsParams struct {
	OrgID           string
	BeforeDeletedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListDeletedWorkflowRowsRow struct {
	ID                   string
	OrgID                string
	Name                 string
	CreatedBy            pgtype.Text
	CreatedAt            *time.Time
	Status               string
	PausedReason         pgtype.Text
	DeletedAt            *time.Time
	RunCount             int32
	LastRunStatus        string
	Tags                 json.RawMessage
	Folder               pgtype.Text
	BufferedTriggerCount int32
}

// The trash list: the same list-row shape with deletedAt populated,
// ordered by (deleted_at, id) DESC with its own keyset.
func (q *Queries) ListDeletedWorkflowRows(ctx context.Context, arg ListDeletedWorkflowRowsParams) ([]ListDeletedWorkflowRowsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedWorkflowRows,
		arg.OrgID,
		arg.BeforeDeletedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedWorkflowRowsRow
	for rows.Next() {
		var i ListDeletedWorkflowRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
			&i.PausedReason,
			&i.DeletedAt,
			&i.RunCount,
			&i.LastRunStatus,
			&i.Tags,
			&i.Folder,
			&i.BufferedTriggerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkflowFolders = `-- name: ListDistinctWorkflowFolders :many
SELECT DISTINCT m.folder::text AS folder
FROM workflow_metadata m
JOIN workflows w ON w.id = m.workflow_id AND w.org_id = m.org_id
WHERE m.org_id = $1 AND m.folder IS NOT NULL AND w.deleted_at IS NULL
ORDER BY folder ASC
LIMIT 200
`

func (q *Queries) ListDistinctWorkflowFolders(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkflowFolders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var folder string
		if err := rows.Scan(&folder); err != nil {
			return nil, err
		}
		items = append(items, folder)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkflowTags = `-- name: ListDistinctWorkflowTags :many
SELECT DISTINCT jsonb_array_elements_text(m.tags)::text AS tag
FROM workflow_metadata m
JOIN workflows w ON w.id = m.workflow_id AND w.org_id = m.org_id
WHERE m.org_id = $1 AND w.deleted_at IS NULL
ORDER BY tag ASC
LIMIT 200
`

func (q *Queries) ListDistinctWorkflowTags(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkflowTags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalWorkflows = `-- name: ListExternalWorkflows :many
SELECT id, org_id, connection_id, external_workflow_id, name, version, snapshot_json, evidence_json, last_sequence, last_event_id, last_observed_at, created_at, updated_at FROM external_workflows
WHERE org_id = $1
ORDER BY last_observed_at DESC NULLS LAST, external_workflow_id ASC
LIMIT 100
`

func (q *Queries) ListExternalWorkflows(ctx context.Context, orgID string) ([]ExternalWorkflow, error) {
	rows, err := q.db.Query(ctx, listExternalWorkflows, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalWorkflow
	for rows.Next() {
		var i ExternalWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.ExternalWorkflowID,
			&i.Name,
			&i.Version,
			&i.SnapshotJson,
			&i.EvidenceJson,
			&i.LastSequence,
			&i.LastEventID,
			&i.LastObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWorkflowVersionDags = `-- name: ListLatestWorkflowVersionDags :many
SELECT DISTINCT ON (wv.workflow_id) wv.workflow_id, wv.dag_json
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.org_id = $1 AND w.deleted_at IS NULL
ORDER BY wv.workflow_id, wv.version DESC
LIMIT 1000
`

type ListLatestWorkflowVersionDagsRow struct {
	WorkflowID string
	DagJson    json.RawMessage
}

func (q *Queries) ListLatestWorkflowVersionDags(ctx context.Context, orgID string) ([]ListLatestWorkflowVersionDagsRow, error) {
	rows, err := q.db.Query(ctx, listLatestWorkflowVersionDags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestWorkflowVersionDagsRow
	for rows.Next() {
		var i ListLatestWorkflowVersionDagsRow
		if err := rows.Scan(&i.WorkflowID, &i.DagJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWorkflowVersionUpstreamTags = `-- name: ListLatestWorkflowVersionUpstreamTags :many
SELECT DISTINCT ON (wv.workflow_id) wv.workflow_id, wv.upstream_health_sources
FROM workflow_versions wv
JOIN workflows w ON w.id = wv.workflow_id AND w.org_id = wv.org_id
WHERE wv.org_id = $1 AND w.deleted_at IS NULL
ORDER BY wv.workflow_id, wv.version DESC
LIMIT 1000
`

type ListLatestWorkflowVersionUpstreamTagsRow struct {
	WorkflowID            string
	UpstreamHealthSources json.RawMessage
}

func (q *Queries) ListLatestWorkflowVersionUpstreamTags(ctx context.Context, orgID string) ([]ListLatestWorkflowVersionUpstreamTagsRow, error) {
	rows, err := q.db.Query(ctx, listLatestWorkflowVersionUpstreamTags, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestWorkflowVersionUpstreamTagsRow
	for rows.Next() {
		var i ListLatestWorkflowVersionUpstreamTagsRow
		if err := rows.Scan(&i.WorkflowID, &i.UpstreamHealthSources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsWithSoftDeletedWorkflows = `-- name: ListOrgsWithSoftDeletedWorkflows :many
SELECT DISTINCT org_id FROM workflows WHERE deleted_at IS NOT NULL
`

// Per-org retention: the sweep resolves each org's catalog window and
// purges with an org-scoped cutoff.
func (q *Queries) ListOrgsWithSoftDeletedWorkflows(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listOrgsWithSoftDeletedWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var org_id string
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedActiveWorkflowIDs = `-- name: ListOwnedActiveWorkflowIDs :many
SELECT id FROM workflows
WHERE org_id = $1 AND id = ANY($2::text[]) AND deleted_at IS NULL
`

type ListOwnedActiveWorkflowIDsParams struct {
	OrgID string
	Ids   []string
}

func (q *Queries) ListOwnedActiveWorkflowIDs(ctx context.Context, arg ListOwnedActiveWorkflowIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listOwnedActiveWorkflowIDs, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeadLettersForWorkflowDelta = `-- name: ListRecentDeadLettersForWorkflowDelta :many
SELECT d.id, d.error_json, d.node_id, d.node_json
FROM dead_letters d
JOIN runs r ON r.id = d.run_id
WHERE d.org_id = $1
  AND r.org_id = $1
  AND d.created_at >= $2
  AND (r.workflow_version_id = $3
       OR r.workflow_version_id IN (SELECT v3.id FROM workflow_versions v3
            WHERE v3.workflow_id = $3 AND v3.org_id = $1))
  AND ($4::int IS NULL OR coalesce(
        (SELECT wv.version FROM workflow_versions wv
         WHERE wv.id = r.workflow_version_id AND wv.org_id = $1),
        (SELECT count(*) FROM workflow_versions v2
         WHERE v2.workflow_id = $3 AND v2.org_id = $1
           AND v2.created_at <= r.created_at))::int >= $4::int)
ORDER BY d.created_at DESC
LIMIT 100
`

type ListRecentDeadLettersForWorkflowDeltaParams struct {
	OrgID       string
	CreatedAt   *time.Time
	WorkflowID  string
	FromVersion pgtype.Int4
}

type ListRecentDeadLettersForWorkflowDeltaRow struct {
	ID        string
	ErrorJson json.RawMessage
	NodeID    string
	NodeJson  json.RawMessage
}

func (q *Queries) ListRecentDeadLettersForWorkflowDelta(ctx context.Context, arg ListRecentDeadLettersForWorkflowDeltaParams) ([]ListRecentDeadLettersForWorkflowDeltaRow, error) {
	rows, err := q.db.Query(ctx, listRecentDeadLettersForWorkflowDelta,
		arg.OrgID,
		arg.CreatedAt,
		arg.WorkflowID,
		arg.FromVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDeadLettersForWorkflowDeltaRow
	for rows.Next() {
		var i ListRecentDeadLettersForWorkflowDeltaRow
		if err := rows.Scan(
			&i.ID,
			&i.ErrorJson,
			&i.NodeID,
			&i.NodeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleEntriesForWorkflow = `-- name: ListScheduleEntriesForWorkflow :many
SELECT id, org_id, workflow_id, workflow_version_id, node_id, cron_expression, enabled, last_run_at, last_run_id, created_by, created_at, updated_at, next_fire_at FROM schedule_entries WHERE org_id = $1 AND workflow_id = $2 ORDER BY node_id
`

type ListScheduleEntriesForWorkflowParams struct {
	OrgID      string
	WorkflowID string
}

func (q *Queries) ListScheduleEntriesForWorkflow(ctx context.Context, arg ListScheduleEntriesForWorkflowParams) ([]ScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listScheduleEntriesForWorkflow, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleEntry
	for rows.Next() {
		var i ScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.NodeID,
			&i.CronExpression,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastRunID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextFireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageDailyStats = `-- name: ListStatusPageDailyStats :many
WITH days AS (
  SELECT generate_series(
    date_trunc('day', now()) - interval '6 days',
    date_trunc('day', now()),
    interval '1 day'
  )::timestamptz AS day
), counts AS (
  SELECT date_trunc('day', r.created_at)::timestamptz AS day,
         count(*) FILTER (WHERE r.status = 'succeeded')::int AS succeeded,
         count(*) FILTER (WHERE r.status = 'failed')::int AS failed
  FROM runs r
  JOIN workflow_versions wv
    ON wv.org_id = r.org_id AND wv.id = r.workflow_version_id
  WHERE r.org_id = $1 AND wv.workflow_id = $2 AND r.replay_mode IS NULL
    AND r.status IN ('succeeded', 'failed')
    AND r.created_at >= date_trunc('day', now()) - interval '6 days'
  GROUP BY 1
)
SELECT days.day,
       coalesce(counts.succeeded, 0)::int AS succeeded,
       coalesce(counts.failed, 0)::int AS failed
FROM days
LEFT JOIN counts USING (day)
ORDER BY days.day
`

type ListStatusPageDailyStatsParams struct {
	OrgID      string
	WorkflowID string
}

type ListStatusPageDailyStatsRow struct {
	Day       time.Time
	Succeeded int32
	Failed    int32
}

func (q *Queries) ListStatusPageDailyStats(ctx context.Context, arg ListStatusPageDailyStatsParams) ([]ListStatusPageDailyStatsRow, error) {
	rows, err := q.db.Query(ctx, listStatusPageDailyStats, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatusPageDailyStatsRow
	for rows.Next() {
		var i ListStatusPageDailyStatsRow
		if err := rows.Scan(&i.Day, &i.Succeeded, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnrecordedRolloutOutcomes = `-- name: ListUnrecordedRolloutOutcomes :many
SELECT r.id AS run_id, r.status FROM runs r
JOIN workflow_rollouts wr ON wr.id = r.workflow_rollout_id AND wr.org_id = r.org_id AND wr.status = 'active'
LEFT JOIN workflow_rollout_outcomes o ON o.run_id = r.id
WHERE r.workflow_rollout_id IS NOT NULL AND r.replay_mode IS NULL
  AND r.status IN ('succeeded','failed','cancelled') AND o.run_id IS NULL
ORDER BY r.created_at ASC, r.id ASC
LIMIT $1
`

type ListUnrecordedRolloutOutcomesRow struct {
	RunID  string
	Status string
}

func (q *Queries) ListUnrecordedRolloutOutcomes(ctx context.Context, pageLimit int32) ([]ListUnrecordedRolloutOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listUnrecordedRolloutOutcomes, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnrecordedRolloutOutcomesRow
	for rows.Next() {
		var i ListUnrecordedRolloutOutcomesRow
		if err := rows.Scan(&i.RunID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowInputPresets = `-- name: ListWorkflowInputPresets :many
SELECT id, name, input_json, created_by, updated_at
FROM workflow_input_presets
WHERE org_id = $1 AND workflow_id = $2
ORDER BY name
`

type ListWorkflowInputPresetsParams struct {
	OrgID      string
	WorkflowID string
}

type ListWorkflowInputPresetsRow struct {
	ID        string
	Name      string
	InputJson json.RawMessage
	CreatedBy pgtype.Text
	UpdatedAt time.Time
}

// Named run-input presets: bounded per workflow, unique by name, always
// org-scoped. The upsert is the save path from the run dialog.
func (q *Queries) ListWorkflowInputPresets(ctx context.Context, arg ListWorkflowInputPresetsParams) ([]ListWorkflowInputPresetsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowInputPresets, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowInputPresetsRow
	for rows.Next() {
		var i ListWorkflowInputPresetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InputJson,
			&i.CreatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRows = `-- name: ListWorkflowRows :many
SELECT w.id, w.org_id, w.name, w.created_by, w.created_at, w.status,
       w.paused_reason, w.deleted_at,
       (SELECT count(*) FROM runs r
        JOIN workflow_versions wv ON wv.id = r.workflow_version_id
        WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
          AND r.replay_mode IS NULL)::int AS run_count,
       COALESCE(last_run.status, '') AS last_run_status,
       COALESCE(m.tags, '[]'::jsonb) AS tags,
       m.folder,
       (SELECT count(*) FROM trigger_events te
        WHERE te.org_id = w.org_id AND te.workflow_id = w.id
          AND (te.status = 'buffered'
               OR (te.status = 'backfilling'
                   AND te.backfill_claimed_at < now() - interval '5 minutes')))::int
         AS buffered_trigger_count
FROM workflows w
LEFT JOIN workflow_metadata m ON m.org_id = w.org_id AND m.workflow_id = w.id
LEFT JOIN LATERAL (
  SELECT r.status FROM runs r
  JOIN workflow_versions wv ON wv.id = r.workflow_version_id
  WHERE r.org_id = w.org_id AND wv.workflow_id = w.id
    AND r.replay_mode IS NULL
  ORDER BY r.created_at DESC, r.id DESC LIMIT 1
) last_run ON true
WHERE w.org_id = $1 AND w.deleted_at IS NULL
  AND (w.created_at, w.id) < ($2::timestamptz, $3::text)
  AND (COALESCE($4::jsonb, '[]'::jsonb) = '[]'::jsonb
       OR COALESCE(m.tags, '[]'::jsonb) @> $4::jsonb)
  AND ($5::text IS NULL OR m.folder = $5::text)
  AND ($6::text IS NULL
       OR (w.name || chr(31) || w.id) ILIKE $6::text ESCAPE '\')
ORDER BY w.created_at DESC, w.id DESC
LIMIT $7
`

type ListWorkflowRowsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	Tags            json.RawMessage
	Folder          pgtype.Text
	SearchPattern   pgtype.Text
	PageLimit       int32
}

type ListWorkflowRowsRow struct {
	ID                   string
	OrgID                string
	Name                 string
	CreatedBy            pgtype.Text
	CreatedAt            *time.Time
	Status               string
	PausedReason         pgtype.Text
	DeletedAt            *time.Time
	RunCount             int32
	LastRunStatus        string
	Tags                 json.RawMessage
	Folder               pgtype.Text
	BufferedTriggerCount int32
}

// Workflow list rows with the read-surface aggregates: run count and last
// run status include production runs linked through saved versions only. The
// metadata join drives tags/folders and the buffered-trigger count includes
// both parked events and abandoned backfill claims after the shared 5m lease.
func (q *Queries) ListWorkflowRows(ctx context.Context, arg ListWorkflowRowsParams) ([]ListWorkflowRowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRows,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.Tags,
		arg.Folder,
		arg.SearchPattern,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRowsRow
	for rows.Next() {
		var i ListWorkflowRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
			&i.PausedReason,
			&i.DeletedAt,
			&i.RunCount,
			&i.LastRunStatus,
			&i.Tags,
			&i.Folder,
			&i.BufferedTriggerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersions = `-- name: ListWorkflowVersions :many
SELECT id, org_id, workflow_id, version, dag_json, created_by, created_at
FROM workflow_versions
WHERE workflow_id = $1 AND org_id = $2
  AND ($3::int IS NULL OR version < $3::int)
  AND ($4::int IS NULL OR version = $4::int)
ORDER BY version DESC
LIMIT $5
`

type ListWorkflowVersionsParams struct {
	WorkflowID    string
	OrgID         string
	BeforeVersion pgtype.Int4
	ExactVersion  pgtype.Int4
	PageLimit     int32
}

type ListWorkflowVersionsRow struct {
	ID         string
	OrgID      string
	WorkflowID string
	Version    int32
	DagJson    json.RawMessage
	CreatedBy  pgtype.Text
	CreatedAt  *time.Time
}

// Keyset page over a workflow's history, newest first. dag_json stays in the
// row: the version panel restores, compares and diffs from this list. An
// exact version pins one row for callers that know which one they need.
func (q *Queries) ListWorkflowVersions(ctx context.Context, arg ListWorkflowVersionsParams) ([]ListWorkflowVersionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersions,
		arg.WorkflowID,
		arg.OrgID,
		arg.BeforeVersion,
		arg.ExactVersion,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVersionsRow
	for rows.Next() {
		var i ListWorkflowVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkflowID,
			&i.Version,
			&i.DagJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersionsForRollout = `-- name: ListWorkflowVersionsForRollout :many
SELECT id, version, dag_json FROM workflow_versions
WHERE org_id = $1 AND workflow_id = $2 ORDER BY version DESC LIMIT 200
`

type ListWorkflowVersionsForRolloutParams struct {
	OrgID      string
	WorkflowID string
}

type ListWorkflowVersionsForRolloutRow struct {
	ID      string
	Version int32
	DagJson json.RawMessage
}

func (q *Queries) ListWorkflowVersionsForRollout(ctx context.Context, arg ListWorkflowVersionsForRolloutParams) ([]ListWorkflowVersionsForRolloutRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionsForRollout, arg.OrgID, arg.WorkflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVersionsForRolloutRow
	for rows.Next() {
		var i ListWorkflowVersionsForRolloutRow
		if err := rows.Scan(&i.ID, &i.Version, &i.DagJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, org_id, name, status, created_by, created_at
FROM workflows
WHERE org_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListWorkflowsParams struct {
	OrgID           string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageLimit       int32
}

type ListWorkflowsRow struct {
	ID        string
	OrgID     string
	Name      string
	Status    string
	CreatedBy pgtype.Text
	CreatedAt *time.Time
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsRow
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkflowForRollout = `-- name: LockWorkflowForRollout :one
SELECT id FROM workflows WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL FOR UPDATE
`

type LockWorkflowForRolloutParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockWorkflowForRollout(ctx context.Context, arg LockWorkflowForRolloutParams) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkflowForRollout, arg.OrgID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const queryRecentRunsAgainstWorkflowVersion = `-- name: QueryRecentRunsAgainstWorkflowVersion :one
WITH candidate_runs AS (
  SELECT r.status,
         coalesce(
           (SELECT wv.version FROM workflow_versions wv
            WHERE wv.id = r.workflow_version_id AND wv.org_id = $2),
           (SELECT count(*) FROM workflow_versions v2
            WHERE v2.workflow_id = $3 AND v2.org_id = $2
              AND v2.created_at <= r.created_at)
         )::int AS effective_version
  FROM runs r
  WHERE r.org_id = $2
    AND r.created_at >= $4
    AND r.replay_mode IS NULL
    AND (r.workflow_version_id = $3
         OR r.workflow_version_id IN (SELECT v3.id FROM workflow_versions v3
              WHERE v3.workflow_id = $3 AND v3.org_id = $2))
)
SELECT
  count(*)::int AS total_runs,
  count(*) FILTER (WHERE status = 'succeeded')::int AS succeeded,
  count(*) FILTER (WHERE status IN ('failed', 'cancelled', 'timed_out'))::int AS failed,
  count(*) FILTER (WHERE status IN ('created', 'running', 'waiting'))::int AS running
FROM candidate_runs
WHERE effective_version >= $1::int
`

type QueryRecentRunsAgainstWorkflowVersionParams struct {
	FromVersion int32
	OrgID       string
	WorkflowID  string
	Since       *time.Time
}

type QueryRecentRunsAgainstWorkflowVersionRow struct {
	TotalRuns int32
	Succeeded int32
	Failed    int32
	Running   int32
}

// The post-Apply dialog needs every production status, not just terminal
// health samples: an in-flight run is visible immediately while the score
// remains below its sample floor. Keep the effective-version rules identical
// to QueryWorkflowHealthSignals so plain runtime runs and pinned rollout runs
// land on the same side of the cutoff.
func (q *Queries) QueryRecentRunsAgainstWorkflowVersion(ctx context.Context, arg QueryRecentRunsAgainstWorkflowVersionParams) (QueryRecentRunsAgainstWorkflowVersionRow, error) {
	row := q.db.QueryRow(ctx, queryRecentRunsAgainstWorkflowVersion,
		arg.FromVersion,
		arg.OrgID,
		arg.WorkflowID,
		arg.Since,
	)
	var i QueryRecentRunsAgainstWorkflowVersionRow
	err := row.Scan(
		&i.TotalRuns,
		&i.Succeeded,
		&i.Failed,
		&i.Running,
	)
	return i, err
}

const queryWorkflowHealthSignals = `-- name: QueryWorkflowHealthSignals :one
WITH candidate_runs AS (
  -- A saved workflow's plain runs carry workflow_version_id = the WORKFLOW
  -- id (the runtime's no-rollout convention); pinned/rollout runs carry a
  -- real version-row id. The effective version for un-pinned runs is the
  -- number of versions saved at run time.
  SELECT r.id, r.status, r.created_at,
         coalesce(
           (SELECT wv.version FROM workflow_versions wv
            WHERE wv.id = r.workflow_version_id AND wv.org_id = $2),
           (SELECT count(*) FROM workflow_versions v2
            WHERE v2.workflow_id = $1 AND v2.org_id = $2
              AND v2.created_at <= r.created_at)
         )::int AS effective_version
  FROM runs r
  WHERE r.org_id = $2
    AND r.created_at >= $3
    AND r.replay_mode IS NULL
    AND (r.workflow_version_id = $1
         OR r.workflow_version_id IN (SELECT v3.id FROM workflow_versions v3
              WHERE v3.workflow_id = $1 AND v3.org_id = $2))
), window_runs AS (
  SELECT id, status, created_at FROM candidate_runs
  WHERE ($4::int IS NULL OR effective_version < $4::int)
    AND ($5::int IS NULL OR effective_version >= $5::int)
), terminal AS (
  SELECT wr.id, wr.status, wr.created_at,
         (SELECT min(e.created_at) FROM run_events e
          WHERE e.run_id = wr.id AND e.type IN ('run.succeeded','run.failed','run.cancelled','run.timed_out')) AS terminal_at
  FROM window_runs wr
  WHERE wr.status IN ('succeeded','failed','cancelled','timed_out')
)
SELECT
  (SELECT count(*) FROM terminal)::int AS total_runs,
  (SELECT count(*) FROM terminal WHERE status = 'succeeded')::int AS success_count,
  (SELECT count(*) FROM terminal WHERE status = 'failed')::int AS failure_count,
  (SELECT count(*) FROM run_events e JOIN window_runs wr ON wr.id = e.run_id
   WHERE e.type = 'node.retry')::int AS retry_count,
  (SELECT count(*) FROM dead_letters d JOIN window_runs wr ON wr.id = d.run_id
   WHERE d.status = 'open')::int AS dlq_open_count,
  coalesce((SELECT percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (t.terminal_at - t.created_at)) * 1000)
   FROM terminal t WHERE t.terminal_at IS NOT NULL), -1)::float8 AS p95_latency_ms,
  coalesce((SELECT sum((u.metadata ->> 'costUsd')::float8) FROM usage_events u
   JOIN window_runs wr ON wr.id = u.run_id
   WHERE u.metadata ? 'costUsd' AND u.metadata ->> 'costUsd' != '<nil>'), 0)::float8 AS total_cost_usd,
  coalesce((SELECT sum(u.quantity) FROM usage_events u
   JOIN window_runs wr ON wr.id = u.run_id), 0)::float8 AS total_tokens,
  (SELECT count(*) FROM workflow_versions v2
   WHERE v2.workflow_id = $1 AND v2.org_id = $2)::int AS version_count
`

type QueryWorkflowHealthSignalsParams struct {
	WorkflowID    string
	OrgID         string
	Since         *time.Time
	BeforeVersion pgtype.Int4
	FromVersion   pgtype.Int4
}

type QueryWorkflowHealthSignalsRow struct {
	TotalRuns    int32
	SuccessCount int32
	FailureCount int32
	RetryCount   int32
	DlqOpenCount int32
	P95LatencyMs float64
	TotalCostUsd float64
	TotalTokens  float64
	VersionCount int32
}

func (q *Queries) QueryWorkflowHealthSignals(ctx context.Context, arg QueryWorkflowHealthSignalsParams) (QueryWorkflowHealthSignalsRow, error) {
	row := q.db.QueryRow(ctx, queryWorkflowHealthSignals,
		arg.WorkflowID,
		arg.OrgID,
		arg.Since,
		arg.BeforeVersion,
		arg.FromVersion,
	)
	var i QueryWorkflowHealthSignalsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.SuccessCount,
		&i.FailureCount,
		&i.RetryCount,
		&i.DlqOpenCount,
		&i.P95LatencyMs,
		&i.TotalCostUsd,
		&i.TotalTokens,
		&i.VersionCount,
	)
	return i, err
}

const removeWorkflowTagBulk = `-- name: RemoveWorkflowTagBulk :execrows
UPDATE workflow_metadata
SET tags = COALESCE((
      SELECT jsonb_agg(existing)
      FROM jsonb_array_elements_text(workflow_metadata.tags) AS existing
      WHERE existing <> $1::text), '[]'::jsonb),
    updated_at = now()
WHERE org_id = $2
  AND workflow_id = ANY($3::text[])
  AND workflow_metadata.tags @> jsonb_build_array($1::text)
`

type RemoveWorkflowTagBulkParams struct {
	Tag         string
	OrgID       string
	WorkflowIds []string
}

func (q *Queries) RemoveWorkflowTagBulk(ctx context.Context, arg RemoveWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWorkflowTagBulk, arg.Tag, arg.OrgID, arg.WorkflowIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameWorkflowFolderBulk = `-- name: RenameWorkflowFolderBulk :execrows
UPDATE workflow_metadata SET folder = $2, updated_at = now()
WHERE org_id = $1 AND folder = $3
`

type RenameWorkflowFolderBulkParams struct {
	OrgID      string
	ToFolder   pgtype.Text
	FromFolder pgtype.Text
}

func (q *Queries) RenameWorkflowFolderBulk(ctx context.Context, arg RenameWorkflowFolderBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWorkflowFolderBulk, arg.OrgID, arg.ToFolder, arg.FromFolder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameWorkflowTagBulk = `-- name: RenameWorkflowTagBulk :execrows
UPDATE workflow_metadata
SET tags = (tags - $2::text) || to_jsonb($3::text),
    updated_at = now()
WHERE org_id = $1 AND tags ? $2::text
`

type RenameWorkflowTagBulkParams struct {
	OrgID   string
	FromTag string
	ToTag   string
}

func (q *Queries) RenameWorkflowTagBulk(ctx context.Context, arg RenameWorkflowTagBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameWorkflowTagBulk, arg.OrgID, arg.FromTag, arg.ToTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreWorkflow = `-- name: RestoreWorkflow :execrows
UPDATE workflows SET deleted_at = NULL
WHERE id = $1 AND org_id = $2 AND deleted_at IS NOT NULL
`

type RestoreWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RestoreWorkflow(ctx context.Context, arg RestoreWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreWorkflow, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLatestWorkflowSlo = `-- name: SetLatestWorkflowSlo :one
UPDATE workflow_versions AS wv SET slo_json = $3
WHERE wv.id = (
  SELECT latest.id FROM workflow_versions AS latest
  WHERE latest.org_id = $1 AND latest.workflow_id = $2
  ORDER BY latest.version DESC LIMIT 1
)
RETURNING wv.id
`

type SetLatestWorkflowSloParams struct {
	OrgID      string
	WorkflowID string
	SloJson    json.RawMessage
}

func (q *Queries) SetLatestWorkflowSlo(ctx context.Context, arg SetLatestWorkflowSloParams) (string, error) {
	row := q.db.QueryRow(ctx, setLatestWorkflowSlo, arg.OrgID, arg.WorkflowID, arg.SloJson)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setWorkflowFolderBulk = `-- name: SetWorkflowFolderBulk :execrows
INSERT INTO workflow_metadata (id, org_id, workflow_id, folder, created_by)
SELECT gen_random_uuid()::text, $1, workflow_id,
       $2, $3
FROM unnest($4::text[]) AS workflow_id
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  folder = excluded.folder, updated_at = now()
`

type SetWorkflowFolderBulkParams struct {
	OrgID       string
	Folder      pgtype.Text
	CreatedBy   pgtype.Text
	WorkflowIds []string
}

// Bulk folder/tag assignment used to loop one (or two) statements per
// workflow, so a single click on a large selection issued hundreds of
// sequential round trips. These do the whole selection in one statement,
// matching the folder/tag RENAME endpoints that were already set-based.
func (q *Queries) SetWorkflowFolderBulk(ctx context.Context, arg SetWorkflowFolderBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkflowFolderBulk,
		arg.OrgID,
		arg.Folder,
		arg.CreatedBy,
		arg.WorkflowIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkflowFolderOnly = `-- name: SetWorkflowFolderOnly :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, folder, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  folder = excluded.folder, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type SetWorkflowFolderOnlyParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Folder     pgtype.Text
	CreatedBy  pgtype.Text
}

func (q *Queries) SetWorkflowFolderOnly(ctx context.Context, arg SetWorkflowFolderOnlyParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, setWorkflowFolderOnly,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Folder,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const setWorkflowTagsOnly = `-- name: SetWorkflowTagsOnly :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, tags, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  tags = excluded.tags, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type SetWorkflowTagsOnlyParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Tags       json.RawMessage
	CreatedBy  pgtype.Text
}

func (q *Queries) SetWorkflowTagsOnly(ctx context.Context, arg SetWorkflowTagsOnlyParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, setWorkflowTagsOnly,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Tags,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const softDeleteWorkflow = `-- name: SoftDeleteWorkflow :execrows
UPDATE workflows SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWorkflowParams struct {
	ID    string
	OrgID string
}

func (q *Queries) SoftDeleteWorkflow(ctx context.Context, arg SoftDeleteWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkflow, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkflowName = `-- name: UpdateWorkflowName :exec
UPDATE workflows SET name = $3
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type UpdateWorkflowNameParams struct {
	ID    string
	OrgID string
	Name  string
}

func (q *Queries) UpdateWorkflowName(ctx context.Context, arg UpdateWorkflowNameParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowName, arg.ID, arg.OrgID, arg.Name)
	return err
}

const upsertWorkflowInputPreset = `-- name: UpsertWorkflowInputPreset :one
INSERT INTO workflow_input_presets (id, org_id, workflow_id, name, input_json, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, workflow_id, name) DO UPDATE SET
  input_json = excluded.input_json, updated_at = now()
RETURNING id, name, input_json, created_by, updated_at
`

type UpsertWorkflowInputPresetParams struct {
	ID         string
	OrgID      string
	WorkflowID string
	Name       string
	InputJson  json.RawMessage
	CreatedBy  pgtype.Text
}

type UpsertWorkflowInputPresetRow struct {
	ID        string
	Name      string
	InputJson json.RawMessage
	CreatedBy pgtype.Text
	UpdatedAt time.Time
}

func (q *Queries) UpsertWorkflowInputPreset(ctx context.Context, arg UpsertWorkflowInputPresetParams) (UpsertWorkflowInputPresetRow, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowInputPreset,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Name,
		arg.InputJson,
		arg.CreatedBy,
	)
	var i UpsertWorkflowInputPresetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputJson,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkflowMetadata = `-- name: UpsertWorkflowMetadata :one
INSERT INTO workflow_metadata (id, org_id, workflow_id, owners, tags, description,
                               slack_channel, linear_project, severity_default,
                               folder, runbook_markdown, ai_guidance_markdown, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (org_id, workflow_id) DO UPDATE SET
  owners = excluded.owners, tags = excluded.tags, description = excluded.description,
  slack_channel = excluded.slack_channel, linear_project = excluded.linear_project,
  severity_default = excluded.severity_default, folder = excluded.folder,
  runbook_markdown = excluded.runbook_markdown,
  ai_guidance_markdown = excluded.ai_guidance_markdown, updated_at = now()
RETURNING id, org_id, workflow_id, owners, runbook_markdown, description, tags, slack_channel, linear_project, severity_default, created_by, created_at, updated_at, folder, ai_guidance_markdown
`

type UpsertWorkflowMetadataParams struct {
	ID                 string
	OrgID              string
	WorkflowID         string
	Owners             json.RawMessage
	Tags               json.RawMessage
	Description        pgtype.Text
	SlackChannel       pgtype.Text
	LinearProject      pgtype.Text
	SeverityDefault    pgtype.Text
	Folder             pgtype.Text
	RunbookMarkdown    pgtype.Text
	AiGuidanceMarkdown pgtype.Text
	CreatedBy          pgtype.Text
}

func (q *Queries) UpsertWorkflowMetadata(ctx context.Context, arg UpsertWorkflowMetadataParams) (WorkflowMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowMetadata,
		arg.ID,
		arg.OrgID,
		arg.WorkflowID,
		arg.Owners,
		arg.Tags,
		arg.Description,
		arg.SlackChannel,
		arg.LinearProject,
		arg.SeverityDefault,
		arg.Folder,
		arg.RunbookMarkdown,
		arg.AiGuidanceMarkdown,
		arg.CreatedBy,
	)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkflowID,
		&i.Owners,
		&i.RunbookMarkdown,
		&i.Description,
		&i.Tags,
		&i.SlackChannel,
		&i.LinearProject,
		&i.SeverityDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Folder,
		&i.AiGuidanceMarkdown,
	)
	return i, err
}

const upsertWorkflowStatusPage = `-- name: UpsertWorkflowStatusPage :exec
INSERT INTO workflow_status_pages (org_id, workflow_id, token_digest)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, workflow_id)
DO UPDATE SET token_digest = EXCLUDED.token_digest, created_at = now()
`

type UpsertWorkflowStatusPageParams struct {
	OrgID       string
	WorkflowID  string
	TokenDigest string
}

// Public status pages: one opaque unguessable token per workflow. The
// token row IS the enablement — deleting it revokes the public URL
// immediately. Public reads join through workflows so a tombstoned
// workflow's page dies with it.
func (q *Queries) UpsertWorkflowStatusPage(ctx context.Context, arg UpsertWorkflowStatusPageParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowStatusPage, arg.OrgID, arg.WorkflowID, arg.TokenDigest)
	return err
}

const workflowInputPresetExists = `-- name: WorkflowInputPresetExists :one
SELECT EXISTS (
  SELECT 1 FROM workflow_input_presets
  WHERE org_id = $1 AND workflow_id = $2 AND name = $3
)
`

type WorkflowInputPresetExistsParams struct {
	OrgID      string
	WorkflowID string
	Name       string
}

func (q *Queries) WorkflowInputPresetExists(ctx context.Context, arg WorkflowInputPresetExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, workflowInputPresetExists, arg.OrgID, arg.WorkflowID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
